import assert from 'node:assert/strict';import { test } from 'node:test';
import { agentDefinitions } from '../src/digital-capabilities/agents/definitions.ts';
import { validateSchema,type Json } from '../src/digital-capabilities/schema.ts';
import { BASE_QUALIFICATION_CONTEXT } from '../src/digital-capabilities/foundation.ts';
test('agents all seven meaningful frozen contracts preserve output schemas and no communication authority',async()=>{assert.equal(agentDefinitions.length,7);for(const d of agentDefinitions){assert.ok(d.cases.length>=2);for(const c of d.cases){validateSchema(d.inputSchema,c.input);const r=await d.execute(c.input as Record<string,Json>,{...BASE_QUALIFICATION_CONTEXT,...c.context});validateSchema(d.outputSchema,r.output);assert.ok(c.check(r),d.id+':'+c.name);assert.deepEqual(await d.execute(c.input as Record<string,Json>,{...BASE_QUALIFICATION_CONTEXT,...c.context}),r);}assert.throws(()=>validateSchema(d.inputSchema,{...(d.cases[0]!.input as object),ownerAuthority:true}));}});
import { contractInput } from '../src/digital-capabilities/agents/qualification.ts';
import { receipt,proof } from '../src/digital-capabilities/business/qualification.ts';
import { canonicalJson,sha256 } from '../src/canonical.ts';
import type { ExecutionContext } from '../src/digital-capabilities/types.ts';
const hash=(x:unknown)=>sha256(canonicalJson(x));
async function invoke(id:string,input:Record<string,Json>,ctx:ExecutionContext=BASE_QUALIFICATION_CONTEXT){const d=agentDefinitions.find(d=>d.id===id)!;validateSchema(d.inputSchema,input);const r=await d.execute(input,ctx);validateSchema(d.outputSchema,r.output);return r.output as Record<string,Json>;}
async function verifiedFixture(){const compiled=await invoke('agent-task-contract-compiler',contractInput);const prior=receipt('contract','agent-task-contract-compiler',compiled);const artifacts=[{id:'answer',digest:'b'.repeat(64)}];const resultProof=proof('result','agent-criterion:cause:PASS',{contractDigest:String(compiled.contractDigest),agentId:'helper',taskClass:'analysis',revision:'r1',artifactSetDigest:hash(artifacts),criterionId:'cause'},'OWNER_OBSERVED');const cost=proof('cost','agent-cost-verified',{contractDigest:String(compiled.contractDigest),agentId:'helper',costDigest:hash(0)},'OWNER_OBSERVED');const input={contractReceiptId:prior.resultDigest,agentId:'helper',taskClass:'analysis',revision:'r1',artifacts,criterionProofs:[{criterionId:'cause',proofIds:['result']}],reportedCashMicroUsd:0,costProofIds:['cost']};const ctx={...BASE_QUALIFICATION_CONTEXT,priorCapabilityResults:[prior],evidence:[resultProof,cost]};return {input,ctx,resultProof,cost};}
test('agents exact contract, revision, artifact and independent cost proof are all required',async()=>{const f=await verifiedFixture();const verified=await invoke('agent-result-verifier',f.input,f.ctx);assert.equal(verified.status,'VERIFIED');assert.equal(verified.actualCashMicroUsd,0);assert.equal((await invoke('agent-result-verifier',{...f.input,revision:'stale'},f.ctx)).status,'INCOMPLETE_EVIDENCE');assert.equal((await invoke('agent-result-verifier',{...f.input,artifacts:[{id:'answer',digest:'c'.repeat(64)}]},f.ctx)).status,'INCOMPLETE_EVIDENCE');assert.equal((await invoke('agent-result-verifier',{...f.input,costProofIds:[]},f.ctx)).status,'INCOMPLETE_EVIDENCE');assert.equal((await invoke('agent-result-verifier',f.input,{...f.ctx,evidence:[{...f.resultProof,provenance:'SUPPLIED',integrity:'DIGESTED_INPUT'},f.cost]})).status,'INCOMPLETE_EVIDENCE');});
test('agents objective contrary result evidence dominates unsupported success and reputation preserves task scope',async()=>{const f=await verifiedFixture();const success=await invoke('agent-result-verifier',f.input,f.ctx),failure=await invoke('agent-result-verifier',f.input,{...f.ctx,evidence:[{...f.resultProof,claims:[...f.resultProof.claims,'agent-criterion:cause:FAIL']},f.cost]});assert.equal(failure.status,'FAILED');const a=receipt('success','agent-result-verifier',success),b=receipt('failure','agent-result-verifier',failure);for(const resultReceiptIds of [[a.resultDigest,b.resultDigest],[b.resultDigest,a.resultDigest]]){const ledger=await invoke('agent-reputation-ledger',{agentId:'helper',taskClass:'analysis',resultReceiptIds},{...BASE_QUALIFICATION_CONTEXT,priorCapabilityResults:[a,b]});assert.equal(ledger.verifiedFailures,1);assert.equal(ledger.verifiedSuccesses,0);assert.equal(ledger.universalTrustScore,null);}const other=await invoke('agent-reputation-ledger',{agentId:'helper',taskClass:'payment',resultReceiptIds:[a.resultDigest]},{...BASE_QUALIFICATION_CONTEXT,priorCapabilityResults:[a]});assert.equal(other.verifiedSuccesses,0);});
test('agents a proof-supported minority can defeat unsupported majority but shared evidence remains correlated',async()=>{const question='What failed?',conclusion='Dependency resolution',e=proof('proof','agent-conclusion-supported',{questionDigest:hash(question),conclusionDigest:hash(conclusion)},'OWNER_OBSERVED');const base={modelFamily:'model-a',proofProvenance:'OWNER_OBSERVED',reasoningDigest:'a'.repeat(64)};const answers=[{...base,id:'a',agentId:'a',conclusion,evidenceIds:['proof']},...['b','c','d'].map(id=>({...base,id,agentId:id,conclusion:'Network outage',evidenceIds:[]}))];const r=await invoke('agent-consensus-evaluator',{question,answers},{...BASE_QUALIFICATION_CONTEXT,evidence:[e]});assert.equal(r.status,'SUPPORTED');assert.equal(r.supportedConclusion,conclusion);assert.equal(r.majorityAcceptedAsProof,false);const correlated=await invoke('agent-consensus-evaluator',{question,answers:[answers[0]!,{...answers[0]!,id:'copy',agentId:'copy',reasoningDigest:'b'.repeat(64)}]},{...BASE_QUALIFICATION_CONTEXT,evidence:[e]});assert.equal((correlated.conclusions as Record<string,Json>[])[0]!.independentEvidenceGroups,1);});
test('agents contract rejects prohibited authority, unknown tools, credentials and paid delegation',async()=>{for(const input of [{...contractInput,requestedAuthority:'PROHIBITED'},{...contractInput,allowedTools:['execute_shell']},{...contractInput,dataBoundaries:['OWNER_SECRET']},{...contractInput,maximumCashMicroUsd:1}]){const r=await invoke('agent-task-contract-compiler',input);assert.equal(r.status,'BLOCKED');assert.equal(r.transmitAuthorized,false);assert.equal(r.effectiveDelegatedAuthority,'NONE');}});
test('agents decomposition catches nested resource writes racing with reads',async()=>{const r=await invoke('agent-work-decomposer',{goal:'Coordinate changes',tasks:[{id:'write',requiredCapabilityId:'analysis',readResources:[],writeResources:['repo:main/src'],dependsOn:[]},{id:'read',requiredCapabilityId:'analysis',readResources:['repo:main/src/config.ts'],writeResources:[],dependsOn:[]}],agents:[{id:'helper',claimedCapabilityIds:['analysis']}]});assert.equal(r.status,'BLOCKED');assert.equal((r.conflicts as Json[]).length,1);});
test('agents historical verified reputation survives execution-freshness invalidation',async()=>{const f=await verifiedFixture();const output=await invoke('agent-result-verifier',f.input,f.ctx);const history={...receipt('past-result','agent-result-verifier',output),receiptValidity:{current:false,reason:'Later authority epoch changed'}};const ledger=await invoke('agent-reputation-ledger',{agentId:'helper',taskClass:'analysis',resultReceiptIds:[history.resultDigest]},{...BASE_QUALIFICATION_CONTEXT,priorCapabilityResults:[history]});assert.equal(ledger.verifiedSuccesses,1);});
