import assert from 'node:assert/strict';
import { test } from 'node:test';
import { businessDefinitions } from '../src/digital-capabilities/business/definitions.ts';
import { validateSchema, type Json } from '../src/digital-capabilities/schema.ts';
import type { ExecutionContext } from '../src/digital-capabilities/types.ts';
const context:ExecutionContext={ownerAuthenticated:false,emergencyStopped:false,authorityContextDigest:'a'.repeat(64),constitutionDigest:'b'.repeat(64),mandateDigest:null,mandateId:null,evidence:[],currentIdentity:{},controls:[],policyDecision:{allowed:true,code:'READ',reason:'Bounded read'},benchmark:async()=>({})};
async function run(id:string,input:Record<string,Json>,ctx=context){const d=businessDefinitions.find(x=>x.id===id)!;assert.ok(d,id);validateSchema(d.inputSchema,input);const r=await d.execute(input,ctx);validateSchema(d.outputSchema,r.output);return r.output as Record<string,Json>;}
test('business requires registered implementations with meaningful frozen outputs and strict schemas',async()=>{assert.equal(businessDefinitions.length,11);for(const d of businessDefinitions){assert.ok(d.cases.length>=2,d.id);for(const c of d.cases){const output=await run(d.id,c.input as Record<string,Json>,{...context,...c.context});assert.ok(c.check({output}),d.id+':'+c.name);assert.deepEqual(await run(d.id,c.input as Record<string,Json>,{...context,...c.context}),output);assert.equal(output.externalActionPerformed,false);}assert.throws(()=>validateSchema(d.inputSchema,{...(d.cases[0]!.input as object),ownerAuthorized:true}));}});
import { acceptanceInput, acceptedFixture, businessCases, businessContext, experimentInput, proof, receipt, revision } from '../src/digital-capabilities/business/qualification.ts';
import { acceptanceScopeDigest } from '../src/digital-capabilities/business/operations.ts';
import { sha256, canonicalJson } from '../src/canonical.ts';
const hash=(v:unknown)=>sha256(canonicalJson(v));
test('business customer acceptance rejects contradictory proof, stale scope and provenance downgrade',async()=>{const f=acceptedFixture();const contradictory={...f.proof,claims:[...f.proof.claims,'customer-criterion:content:FAIL']};assert.equal((await run('customer-acceptance-verifier',f.input,{...context,evidence:[contradictory]})).status,'FAIL');assert.equal((await run('customer-acceptance-verifier',{...f.input,scope:['Different obligation']},{...context,evidence:[f.proof]})).status,'INCOMPLETE_EVIDENCE');assert.equal((await run('customer-acceptance-verifier',f.input,{...context,evidence:[{...f.proof,provenance:'SUPPLIED',claimedProvenance:'ISOLATED',integrity:'DIGESTED_INPUT'}]})).status,'INCOMPLETE_EVIDENCE');});
test('business production acceptance cannot use CI or deployment-success-only proof',async()=>{const input={...acceptanceInput,criteria:[{...acceptanceInput.criteria[0]!,provenance:'PRODUCTION'}],deploymentId:'deployment-fixture',deploymentSha:revision};const identity={jobId:'job1',revision,scopeDigest:acceptanceScopeDigest(input),criterionId:'content',deploymentId:'deployment-fixture',deploymentSha:revision};assert.equal((await run('customer-acceptance-verifier',input,{...context,evidence:[proof('criterion','customer-criterion:content:PASS',identity,'CI')]})).status,'INCOMPLETE_EVIDENCE');assert.equal((await run('customer-acceptance-verifier',input,{...context,evidence:[proof('criterion','deployment-succeeded',identity,'PRODUCTION')]})).status,'INCOMPLETE_EVIDENCE');assert.equal((await run('customer-acceptance-verifier',input,{...context,evidence:[proof('criterion','customer-criterion:content:PASS',identity,'PRODUCTION')]})).status,'PASS');});
test('business productization rejects duplicate jobs and stale receipt validity',async()=>{const c=businessCases['repeatable-service-productizer']![0]!,input=c.input as Record<string,Json>,ctx={...context,...c.context};const first=ctx.priorCapabilityResults![0]!;assert.equal((await run('repeatable-service-productizer',{...input,acceptedJobReceiptIds:[first.resultDigest,first.resultDigest]},ctx)).status,'INSUFFICIENT_EVIDENCE');assert.equal((await run('repeatable-service-productizer',input,{...ctx,priorCapabilityResults:ctx.priorCapabilityResults!.map(r=>({...r,receiptValidity:{current:false,reason:'Source changed'}}))})).status,'INSUFFICIENT_EVIDENCE');assert.equal((await run('repeatable-service-productizer',input,{...ctx,serviceCapabilityEvidence:[]})).status,'INSUFFICIENT_EVIDENCE');});
test('business experiment uses precommitted threshold and verified actual values; predicted revenue stays separate',async()=>{const design=experimentInput.design;const registered=await run('business-experiment-evaluator',experimentInput);const prior=receipt('registered','business-experiment-evaluator',registered);const result={metricValue:3,actualCashCostMicroUsd:999,actualRevenueMicroUsd:2000,predictedRevenueMicroUsd:999999};const resultProof={...proof('result','business-experiment:experiment:RESULT',{experimentId:'experiment',designDigest:hash(design),resultDigest:hash(result)}),capturedAt:'2026-09-14T00:00:00Z'};const registrationProof={...proof('registration','registered',{experimentId:'experiment'}),contentDigest:prior.resultDigest,capturedAt:'2026-09-12T00:00:00Z'};const input={...experimentInput,phase:'EVALUATE',registrationReceiptId:prior.resultDigest,result,proofIds:['result']},ctx={...context,priorCapabilityResults:[prior],evidence:[registrationProof,resultProof]};const r=await run('business-experiment-evaluator',input,ctx);assert.equal(r.status,'SUCCESS');assert.equal(r.actualRevenueMicroUsd,2000);assert.equal(r.predictedRevenueMicroUsd,999999);assert.equal((await run('business-experiment-evaluator',{...input,design:{...design,minimumThreshold:1}},ctx)).status,'INCOMPLETE_EVIDENCE');assert.equal((await run('business-experiment-evaluator',input,{...ctx,evidence:[{...registrationProof,capturedAt:'2026-09-14T00:00:00Z'},resultProof]})).status,'INCOMPLETE_EVIDENCE');assert.equal((await run('business-experiment-evaluator',input,{...ctx,evidence:[registrationProof,{...resultProof,capturedAt:'2026-09-12T00:00:00Z'}]})).status,'INCOMPLETE_EVIDENCE');});
test('business untrusted competitor links and forged approval fields are rejected',async()=>{const input=businessCases['competitive-offer-analyzer']![0]!.input as Record<string,Json>;const offer=(input.offers as Record<string,Json>[])[0]!;await assert.rejects(()=>run('competitive-offer-analyzer',{offers:[{...offer,sourceUrl:'https://user:secret@example.com'}]}),/UNSAFE_SOURCE_URL/);await assert.rejects(()=>run('competitive-offer-analyzer',{offers:[{...offer,sourceUrl:'javascript:alert(1)'}]}),/UNSAFE_SOURCE_URL/);const p=businessCases['proposal-compiler']![1]!;const r=await run('proposal-compiler',p.input as Record<string,Json>,{...context,...p.context,priorCapabilityResults:[]});assert.equal(r.approvalVerified,false);assert.equal(r.bindingOffer,false);});
test('business demand contradiction is contested and statements must match proof digest',async()=>{const c=businessCases['market-demand-validator']![0]!,input=c.input as Record<string,Json>,ctx={...context,...c.context};const original=(input.observations as Record<string,Json>[])[0]!;const counter={...original,id:'counter',kind:'COUNTEREVIDENCE',statement:'Customer declined recurring work',proofIds:['counter-proof']};const counterProof=proof('counter-proof','market-demand:counter:COUNTEREVIDENCE',{serviceId:'content-update',observationId:'counter',statementDigest:hash(counter.statement),sourceId:'customer:1'},'EXTERNAL_READ_ONLY');assert.equal((await run('market-demand-validator',{...input,observations:[original,counter]},{...ctx,evidence:[...ctx.evidence,counterProof]})).status,'CONTESTED');assert.equal((await run('market-demand-validator',{...input,observations:[{...original,statement:'Invented huge demand'}]},ctx)).status,'INSUFFICIENT_EVIDENCE');});
