import assert from 'node:assert/strict';
import { test } from 'node:test';
import { economicDefinitions,valueFixture } from '../src/digital-capabilities/economic/definitions.ts';
import { snapshotJson,validateSchema,type Json } from '../src/digital-capabilities/schema.ts';
import type { ExecutionContext } from '../src/digital-capabilities/types.ts';
const context:ExecutionContext={ownerAuthenticated:false,emergencyStopped:false,authorityContextDigest:'a'.repeat(64),constitutionDigest:'b'.repeat(64),mandateDigest:null,mandateId:null,evidence:[],currentIdentity:{},controls:[],policyDecision:{allowed:true,code:'READ_ONLY',reason:'Arithmetic only'},benchmark:async()=>null};
const cost={directCashMicroUsd:0,modelApiMicroUsd:0,infrastructureMicroUsd:0,toolingMicroUsd:0,allocatedMicroUsd:0,modeledLaborMicroUsd:0};
const resource={modelCalls:0,apiCalls:0,computeSeconds:0,timeSeconds:0,cashMicroUsd:0};
async function run(id:string,input:unknown){const d=economicDefinitions.find(d=>d.id===id);assert.ok(d);const value=snapshotJson(input);validateSchema(d.inputSchema,value);const result=await d.execute(value as Record<string,Json>,context);validateSchema(d.outputSchema,result.output);return result.output as Record<string,Json>;}
test('quote guard blocks a real loss smaller than one displayed margin ppm',async()=>{
 const result=await run('quote-margin-guard',{cost:{...cost,directCashMicroUsd:1_000_000_000_000,modelApiMicroUsd:1},riskReserveMicroUsd:0,proposedPriceMicroUsd:1_000_000_000_000,minimumMarginPpm:0});assert.equal(result.contributionMicroUsd,-1);assert.equal(result.status,'BLOCKED');
});
test('all six economic contracts reject absent/malformed inputs and unsupported authority fields',async()=>{
 assert.equal(economicDefinitions.length,6);for(const d of economicDefinitions){await assert.rejects(()=>run(d.id,{}));await assert.rejects(()=>run(d.id,{...(d.cases[0]!.input as Record<string,Json>),spendingAuthorized:true}));}
 await assert.rejects(()=>run('economic-value-of-work',{...valueFixture,successProbabilityPpm:1000001}));await assert.rejects(()=>run('economic-value-of-work',{...valueFixture,cost:{...cost,modelApiMicroUsd:-1}}));
 await assert.rejects(()=>run('service-pricing-engine',{cost,riskReserveMicroUsd:0,expectedSupportMicroUsd:0,minimumMarginPpm:1000000,demandEvidenceRefs:[],competitiveEvidenceRefs:[],valueBasis:''}));
});
test('expected-value arithmetic retains raw strategic/cost components and uses exact bounded probabilities',async()=>{
 const benefits=[0,1,999999,1000000,999999999999,1000000000000],probabilities=[0,1,333333,500000,999999,1000000];
 for(const benefit of benefits)for(const probability of probabilities){const input={...valueFixture,benefitMicroUsd:benefit,successProbabilityPpm:probability,cost:{...cost,directCashMicroUsd:17,allocatedMicroUsd:500,modeledLaborMicroUsd:10000},riskReserveMicroUsd:19,opportunityCostMicroUsd:23,strategicPoints:77,repeatabilityPoints:88};const result=await run('economic-value-of-work',input);const expected=Number(BigInt(benefit)*BigInt(probability)/1000000n);assert.equal(result.expectedBenefitMicroUsd,expected);assert.equal(result.expectedCashMicroUsd,17);assert.equal(result.comparableScoreMicroUsd,expected-59);assert.deepEqual(result.rawComponents,input);assert.equal(result.executionAuthorized,false);}
});
test('unknown expected values remain unknown and never become an invented zero-cost opportunity',async()=>{
 for(const patch of [{benefitMicroUsd:null},{benefitBasis:''},{successProbabilityPpm:null},{probabilityBasis:''},{riskReserveMicroUsd:null},{opportunityCostMicroUsd:null},{cost:{...cost,modelApiMicroUsd:null}}]){const result=await run('economic-value-of-work',{...valueFixture,...patch});assert.equal(result.comparableScoreMicroUsd,null);assert.ok((result.unknowns as Json[]).length>0);}
 const quoted=await run('quote-margin-guard',{cost:{...cost,directCashMicroUsd:null},riskReserveMicroUsd:0,proposedPriceMicroUsd:100,minimumMarginPpm:0});assert.equal(quoted.status,'INCOMPLETE_EVIDENCE');assert.equal(quoted.contributionMicroUsd,null);
});
test('pricing floor rounds upward and minimum price actually satisfies the exact requested margin',async()=>{
 for(const total of [0,1,2,17,999999,1000000])for(const margin of [0,1,333333,500000,999999]){const result=await run('service-pricing-engine',{cost:{...cost,directCashMicroUsd:total},riskReserveMicroUsd:0,expectedSupportMicroUsd:0,minimumMarginPpm:margin,demandEvidenceRefs:[],competitiveEvidenceRefs:[],valueBasis:'supplied cash floor only'});const price=Number(result.minimumPriceMicroUsd);assert.ok(BigInt(price)*BigInt(1000000-margin)>=BigInt(total)*1000000n);if(price>0)assert.ok(BigInt(price-1)*BigInt(1000000-margin)<BigInt(total)*1000000n);assert.equal((result.recommendedRangeMicroUsd as Record<string,Json>).maximum,null);assert.equal(result.offerAuthorized,false);}
 await assert.rejects(()=>run('service-pricing-engine',{cost:{...cost,directCashMicroUsd:1000000000000,modelApiMicroUsd:1000000000000,infrastructureMicroUsd:1000000000000,toolingMicroUsd:1000000000000},riskReserveMicroUsd:1000000000000,expectedSupportMicroUsd:1000000000000,minimumMarginPpm:999999,demandEvidenceRefs:[],competitiveEvidenceRefs:[],valueBasis:''}),/SAFE_INTEGER|NUMBER_BOUNDS|OVERFLOW/);
});
test('profitability separates realized revenue from forecasts, preserves failed jobs, refunds and modeled labor',async()=>{
 const entry=(id:string,kind:string,amountMicroUsd:number|null,realized=true,jobId='paid-job')=>({id,jobId,sourceId:`source-${id}`,kind,amountMicroUsd,realized});const entries=[entry('revenue','REVENUE',1000),entry('forecast','REVENUE',5000,false),entry('refund','REFUND',150),entry('api','MODEL_API',50),entry('external','DIRECT_EXTERNAL',100),entry('allocation','ALLOCATION',60,false),entry('labor','MODELED_LABOR',900,false),entry('failed-forecast','REVENUE',100000,false,'failed-job'),entry('failed-spend','MODEL_API',80,true,'failed-job')];
 const actual=await run('profitability-accountant',{entries,includeModeledLabor:false}),modeled=await run('profitability-accountant',{entries,includeModeledLabor:true});const paid=(actual.jobs as Record<string,Json>[]).find(j=>j.jobId==='paid-job')!,failed=(actual.jobs as Record<string,Json>[]).find(j=>j.jobId==='failed-job')!;assert.equal(paid.realizedRevenueMicroUsd,1000);assert.equal(paid.predictedRevenueMicroUsd,5000);assert.equal(paid.grossContributionMicroUsd,700);assert.equal(paid.netContributionMicroUsd,640);assert.equal((modeled.jobs as Record<string,Json>[]).find(j=>j.jobId==='paid-job')!.netContributionMicroUsd,-260);assert.equal(failed.netContributionMicroUsd,-80);assert.equal(actual.ledgerChanged,false);assert.equal(actual.financialAttestationCreated,false);
 const unknown=await run('profitability-accountant',{entries:[entry('known','REVENUE',1000),entry('unknown','MODEL_API',null)],includeModeledLabor:false});assert.equal((unknown.jobs as Record<string,Json>[])[0]!.netContributionMicroUsd,null);
 await assert.rejects(()=>run('profitability-accountant',{entries:[entries[0],entries[0]],includeModeledLabor:false}),/DUPLICATE_ID/);await assert.rejects(()=>run('profitability-accountant',{entries:[entry('fake-refund','REFUND',50,false)],includeModeledLabor:false}),/ACTUAL_COST_REQUIRES_REALIZED_BASIS/);
});
test('opportunity ranking blocks profitable unauthorized work and puts hard obligations before eligible higher value',async()=>{
 const opportunity=(id:string,benefit:number,patch:Record<string,unknown>={})=>({id,permission:'PERMITTED',obligation:false,prerequisitesSatisfied:true,evidenceSufficient:true,value:{...valueFixture,benefitMicroUsd:benefit,cost,successProbabilityPpm:1000000,riskReserveMicroUsd:0,opportunityCostMicroUsd:0},...patch});
 const inputs=[opportunity('cosmetic',1),opportunity('paying',10000),opportunity('speculative',1000000,{value:{...valueFixture,benefitMicroUsd:1000000,successProbabilityPpm:1,cost,riskReserveMicroUsd:0,opportunityCostMicroUsd:0}}),opportunity('reliability',50000),opportunity('unauthorized',1000000000000,{permission:'PROHIBITED'}),opportunity('commitment',10,{obligation:true}),opportunity('blocked-obligation',100,{obligation:true,prerequisitesSatisfied:false})];
 const result=await run('revenue-opportunity-ranker',{opportunities:inputs});assert.equal(result.selectedId,'commitment');assert.deepEqual((result.ranked as Record<string,Json>[]).map(r=>r.id),['commitment','reliability','paying','cosmetic','speculative']);assert.deepEqual((result.blocked as Record<string,Json>[]).map(r=>r.id),['unauthorized','blocked-obligation']);assert.equal(result.executionAuthorized,false);assert.equal(result.authorityBasis,'SUPPLIED_ELIGIBILITY_ADVISORY_ONLY');
 const allBlocked=await run('revenue-opportunity-ranker',{opportunities:[opportunity('big',999999999,{permission:'UNKNOWN'})]});assert.equal(allBlocked.selectedId,null);
});
test('resource allocation obeys every dimension and reserves scarce capacity for obligations first',async()=>{
 const ceilings={modelCalls:10,apiCalls:8,computeSeconds:30,timeSeconds:40,cashMicroUsd:100};const requests=[{id:'cosmetic',obligation:false,priority:100,resources:{...resource,modelCalls:10,cashMicroUsd:100}},{id:'contract',obligation:true,priority:0,resources:{...resource,modelCalls:7,cashMicroUsd:80}},{id:'free-read',obligation:false,priority:1,resources:{...resource,apiCalls:1}}];const result=await run('resource-budget-planner',{ceilings,alreadyUsed:resource,requests});assert.deepEqual((result.allocated as Record<string,Json>[]).map(r=>r.id),['contract','free-read']);assert.deepEqual((result.blocked as Record<string,Json>[]).map(r=>r.id),['cosmetic']);assert.equal(result.ownerCeilingChanged,false);assert.equal(result.reservationsCreated,false);assert.equal(result.executionAuthorized,false);
 let seed=16441;const next=(max:number)=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%max;};for(let trial=0;trial<60;trial++){const cap={modelCalls:next(100),apiCalls:next(100),computeSeconds:next(100),timeSeconds:next(100),cashMicroUsd:next(100)},used={...resource};for(const key of Object.keys(used) as (keyof typeof resource)[])used[key]=next(cap[key]+1);const jobs=Array.from({length:10},(_,n)=>({id:`job-${n}`,obligation:next(2)===0,priority:next(101),resources:{modelCalls:next(30),apiCalls:next(30),computeSeconds:next(30),timeSeconds:next(30),cashMicroUsd:next(30)}}));const planned=await run('resource-budget-planner',{ceilings:cap,alreadyUsed:used,requests:jobs});const allocated=planned.allocated as {id:string;resources:typeof resource}[];for(const key of Object.keys(cap) as (keyof typeof resource)[]){const consumption=allocated.reduce((sum,a)=>sum+a.resources[key],0);assert.equal(consumption+used[key]+Number((planned.remaining as Record<string,Json>)[key]),cap[key]);assert.ok(consumption+used[key]<=cap[key]);}assert.deepEqual(await run('resource-budget-planner',{ceilings:cap,alreadyUsed:used,requests:jobs}),planned);}
 await assert.rejects(()=>run('resource-budget-planner',{ceilings:resource,alreadyUsed:{...resource,cashMicroUsd:1},requests:[]}),/EXISTING_USAGE_EXCEEDS_CEILING/);
});
