import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,cp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {SaraKernel,SARA_PRINCIPAL} from '../src/kernel.ts';import {sha256} from '../src/canonical.ts';
const supplied={id:'triage-install',version:1,goal:'Triage the supplied CI failure',steps:[{capabilityId:'ci-failure-triage',input:{revision:'a'.repeat(40),changedFiles:['package-lock.json'],steps:[{id:'install',status:'FAILED',logs:'ERESOLVE unable to resolve dependency tree\nProcess completed with exit code 1'}]},evidenceReceiptIds:[],bindings:[],completion:[{path:['category'],equals:'DEPENDENCY'},{path:['retry','automaticRetryAuthorized'],equals:false}]}]};
test('high-level goal compiles to actual current contracts, executes, and resumes the same durable work after restore',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'goal-execution-')),copy=await mkdtemp(join(tmpdir(),'goal-copy-'));try{let k=await SaraKernel.boot({stateDirectory:dir,ownerTokenSha256:sha256('goal-owner')}),owner=k.authenticateOwnerToken('goal-owner');
 const first=await k.executeCapabilityGoal(owner,supplied);assert.equal(first.status,'COMPLETE');assert.equal(first.execution?.completed.length,1);const events=await k.inspectAudit();assert.equal(events.filter(e=>e.type==='digital_capability_executed').length,2);assert.ok(events.every(e=>!['job_created','ledger_recorded'].includes(e.type)));assert.equal(first.execution?.actualCashMicroUsd,0);
 await cp(dir,copy,{recursive:true});k=await SaraKernel.boot({stateDirectory:copy,ownerTokenSha256:sha256('goal-owner')});owner=k.authenticateOwnerToken('goal-owner');const again=await k.executeCapabilityGoal(owner,supplied);assert.equal(again.status,'COMPLETE');assert.equal(again.goalReceiptDigest,first.goalReceiptDigest);assert.deepEqual(again.execution?.completed,first.execution?.completed);assert.equal((await k.inspectAudit()).filter(e=>e.type==='digital_capability_executed').length,2);
 await assert.rejects(()=>k.executeCapabilityGoal(SARA_PRINCIPAL,supplied),/AUTHENTICATED_OWNER_REQUIRED/);await assert.rejects(()=>k.executeCapabilityGoal(owner,{...supplied,id:'injected',steps:[{...supplied.steps[0],capabilityId:'send-email'}]}),/INPUT_OUTSIDE_COMPILED_GOAL_SCOPE/);
 }finally{await rm(dir,{recursive:true,force:true});await rm(copy,{recursive:true,force:true});}
});
test('goal bridge identifies missing inputs and fails exact completion predicates without fabricating success',async()=>{const dir=await mkdtemp(join(tmpdir(),'goal-missing-'));try{const k=await SaraKernel.boot({stateDirectory:dir,ownerTokenSha256:sha256('goal-owner')}),owner=k.authenticateOwnerToken('goal-owner');const missing=await k.executeCapabilityGoal(owner,{...supplied,steps:[]});assert.equal(missing.status,'INCOMPLETE_EVIDENCE');assert.deepEqual(missing.missingCapabilityInputs,['ci-failure-triage']);assert.equal(missing.execution,null);const unmet=await k.executeCapabilityGoal(owner,{...supplied,id:'wrong-predicate',steps:[{...supplied.steps[0],completion:[{path:['category'],equals:'SECURITY'}]}]});assert.equal(unmet.status,'BLOCKED');assert.equal(unmet.execution?.reason,'COMPLETION_PREDICATE_FAILED');}finally{await rm(dir,{recursive:true,force:true});}});
