import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {SaraKernel,SARA_PRINCIPAL} from '../src/kernel.ts';
import {canonicalJson,sha256} from '../src/canonical.ts';
import {JEV_MODEL,JEV_QUESTION_VERSION,JEV_RESERVATION_MICROUSD,JEV_MAX_INPUT_TOKENS} from '../src/jev-second-brain.ts';
const token='synthetic-jev-budget';
async function boot(dir:string){return SaraKernel.boot({stateDirectory:dir,ownerTokenSha256:sha256(token)});}
async function configure(k:SaraKernel,monthlyLimitUsd=.01,openingChargeUsd=0){const o=k.authenticateOwnerToken(token),input={monthlyLimitUsd,openingChargeUsd,inputUsdPerMillionTokens:100,outputUsdPerMillionTokens:100};await k.configureModelBudget(o,input,{approvalId:'test-only',ownerId:o.id,action:'owner_funded_ceiling_change',targetId:'model-budget:'+sha256(canonicalJson(input)),approvedAt:new Date().toISOString()});}
async function transfer(k:SaraKernel){const o=k.authenticateOwnerToken(token),review=await k.reviewJevReallocation(o);await k.reallocateModelBudgetToJev(o,review.targetId,{approvalId:'test-transfer',ownerId:o.id,action:'owner_funded_ceiling_change',targetId:review.targetId,approvedAt:new Date().toISOString()});return o;}
const input=(principalId:string)=>({purpose:'second_brain_rerank' as const,principalId,project:'nico',model:JEV_MODEL,questionVersion:JEV_QUESTION_VERSION,requestDigest:'a'.repeat(64),maximumMicrousd:JEV_RESERVATION_MICROUSD,maximumInputTokens:JEV_MAX_INPUT_TOKENS});
test('Jev reallocation requires real existing allowance and exact authenticated approval',async()=>{const dir=await mkdtemp(join(tmpdir(),'jev-budget-'));try{const k=await boot(dir);const o=k.authenticateOwnerToken(token);assert.equal((await k.reviewJevReallocation(o)).transferableUsd,0);await assert.rejects(()=>k.reviewJevReallocation(SARA_PRINCIPAL));await configure(k);const review=await k.reviewJevReallocation(o);assert.equal(review.transferableUsd,.01);await assert.rejects(()=>k.reallocateModelBudgetToJev(o,review.targetId));await assert.rejects(()=>k.reallocateModelBudgetToJev(o,'wrong'));await transfer(k);assert.equal((await k.modelBudgetStatus()).remainingUsd,0);assert.equal((await k.jevBudgetStatus()).remainingUsd,.01);}finally{await rm(dir,{recursive:true,force:true});}});
test('Jev transfer excludes existing spent/opening amounts and preserves Luna holds',async()=>{const dir=await mkdtemp(join(tmpdir(),'jev-held-'));try{const k=await boot(dir);await configure(k,.03,.01);let calls=0;await assert.rejects(()=>k.guardPaidModelClient({routeKey:'openai:gpt-5.6-luna:paid',maximumWallTimeMs:1000,countInputTokens:async()=>50,execute:async()=>{calls++;throw Error('uncertain charge');}}).execute({prompt:'synthetic',reasoningLevel:'low',maximumOutputTokens:50}));assert.equal(calls,1);const o=k.authenticateOwnerToken(token);assert.equal((await k.reviewJevReallocation(o)).transferableUsd,.01);await transfer(k);assert.equal((await k.modelBudgetStatus()).reservedUsd,.03);assert.equal((await k.jevBudgetStatus()).allocatedUsd,.01);}finally{await rm(dir,{recursive:true,force:true});}});
test('parallel kernels/retries share atomic Jev suballocation and unknown costs remain held',async()=>{const dir=await mkdtemp(join(tmpdir(),'jev-race-'));try{const a=await boot(dir);await configure(a);const ao=await transfer(a),b=await boot(dir),bo=b.authenticateOwnerToken(token);const ab=a.jevBudget(ao),bb=b.jevBudget(bo);const results=await Promise.all(Array.from({length:10},(_,i)=>(i%2?bb:ab).reserve(input(ao.id))));assert.equal(results.filter(Boolean).length,3);for(const r of results.filter(Boolean))await ab.record({reservationId:r!.id,outcome:'timeout',costMicrousd:null,inputTokens:null,outputTokens:null});const status=await(await boot(dir)).jevBudgetStatus();assert.equal(status.reservedUsd,3*JEV_RESERVATION_MICROUSD/1e6);assert.equal(status.remainingUsd,(10000-3*JEV_RESERVATION_MICROUSD)/1e6);assert.equal((await a.modelBudgetStatus()).reservedUsd,.01);}finally{await rm(dir,{recursive:true,force:true});}});
test('Jev receipts are validated/idempotent and authority stops on emergency or month boundary',async t=>{const dir=await mkdtemp(join(tmpdir(),'jev-receipt-'));t.mock.timers.enable({apis:['Date'],now:new Date('2026-09-26T12:00:00Z')});try{const k=await boot(dir);await configure(k);const o=await transfer(k),budget=k.jevBudget(o);assert.equal(await budget.reserve({...input(o.id),model:'jev-latest'}),null);assert.equal(await budget.reserve({...input(o.id),project:'foreign'}),null);const r=await budget.reserve(input(o.id));assert.ok(r);assert.equal(await budget.stillAuthorized(r.id),true);assert.equal(await budget.stillAuthorized(r.id),false);await assert.rejects(()=>budget.record({reservationId:r.id,outcome:'usage_observed',costMicrousd:0,inputTokens:100,outputTokens:1}));const receipt={reservationId:r.id,outcome:'usage_observed',costMicrousd:5,inputTokens:100,outputTokens:1};await budget.record(receipt);await budget.record(receipt);await assert.rejects(()=>budget.record({...receipt,inputTokens:200,costMicrousd:9}));await k.setEmergencyStop(o,true);assert.equal(await budget.stillAuthorized(r.id),false);assert.equal(await budget.reserve(input(o.id)),null);await k.setEmergencyStop(o,false);t.mock.timers.setTime(new Date('2026-10-01T00:00:00Z').getTime());assert.equal((await k.jevBudgetStatus()).allocatedUsd,0);assert.equal(await budget.reserve(input(o.id)),null);assert.equal(await budget.stillAuthorized(r.id),false);}finally{t.mock.timers.reset();await rm(dir,{recursive:true,force:true});}});
test('stale funding review cannot transfer changed allowance; lowering cap freezes new Jev holds',async()=>{const dir=await mkdtemp(join(tmpdir(),'jev-stale-'));try{const k=await boot(dir);await configure(k,.02);const o=k.authenticateOwnerToken(token),review=await k.reviewJevReallocation(o);await configure(k,.02,.01);await assert.rejects(()=>k.reallocateModelBudgetToJev(o,review.targetId,{approvalId:'stale',ownerId:o.id,action:'owner_funded_ceiling_change',targetId:review.targetId,approvedAt:new Date().toISOString()}),/review changed/);await transfer(k);await configure(k,.01,.01);assert.equal(await k.jevBudget(o).reserve(input(o.id)),null);assert.equal(await k.jevBudget(SARA_PRINCIPAL).reserve(input(SARA_PRINCIPAL.id)),null);assert.equal((await k.jevBudgetStatus()).dispatchReservations,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('blocked and failed funded job snapshots remain obligations and invalidate funding review',async()=>{const dir=await mkdtemp(join(tmpdir(),'jev-job-obligation-'));try{const k=await boot(dir);await configure(k,.02);const o=k.authenticateOwnerToken(token);const job=await k.createSelfDevelopmentJob(SARA_PRINCIPAL,{objective:'Synthetic pending funded work',expectedOwnerValue:1,requiredCapabilities:[],acceptanceCriteria:['Synthetic criterion'],maximumBudgetUsd:0});const before=await k.reviewJevReallocation(o);
 // Unit fixture for durable statuses without exposing any write-capable store or changing production history.
 const readable=k as unknown as {state:()=>Promise<{jobs:typeof job[]}>};const original=readable.state.bind(k);let fixtureStatus:'blocked'|'failed'='blocked';readable.state=async()=>{const state=await original();return {...state,jobs:state.jobs.map(j=>j.id===job.id?{...j,status:fixtureStatus,workCard:{...j.workCard,maximumBudgetUsd:1}}:j)};};
 for(const status of ['blocked','failed'] as const){fixtureStatus=status;const review=await k.reviewJevReallocation(o);assert.equal(review.transferableUsd,0);assert.ok(review.fundedJobs.includes(job.id));assert.notEqual(review.targetId,before.targetId);await assert.rejects(()=>k.reallocateModelBudgetToJev(o,before.targetId),/review changed/);}
 }finally{await rm(dir,{recursive:true,force:true});}});

test('confirmed payment before fulfillment authorization preserves commitment and invalidates funding review',async()=>{const dir=await mkdtemp(join(tmpdir(),'jev-payment-obligation-'));try{const k=await SaraKernel.boot({stateDirectory:dir,ownerTokenSha256:sha256(token),bootstrapRevenueCapabilities:true});await configure(k,.02);const o=k.authenticateOwnerToken(token);const job=await k.createRevenuePilotJob(SARA_PRINCIPAL,{opportunityId:'synthetic-obligation',sourceUrl:'https://github.com/example/repo',sourceAllowsAutomatedDiscovery:true,discoveredFromPublicSource:true,repoUrl:'https://github.com/example/repo',repositoryIsPublic:true,repositoryOwnerPermissionConfirmed:true,requiresPrivateAccess:false,containsRegulatedOrPrivateData:false,requestsProductionChanges:false,requestsExploitValidation:false,primaryGoal:'release_readiness',customerBudgetUsd:149,desiredTurnaroundDays:3,recentCommitDays:1});
 const {compileCommercialTerms}=await import('../src/commercial-terms.ts');const {paymentClientSecretDigest}=await import('../src/revenue-payment.ts');const {BASE_MAINNET_CHAIN_ID,BASE_USDC_CONTRACT}=await import('../src/usdc-payment.ts');const secret='synthetic-client-secret-at-least-thirty-two-characters',recipient='0x'+'2'.repeat(40),transactionHash='0x'+'a'.repeat(64);
 const intent=await k.createRevenuePaymentIntent(SARA_PRINCIPAL,{id:'synthetic_payment_obligation',jobId:job.id,recipientAddress:recipient,clientSecretDigest:paymentClientSecretDigest(secret),customerReferenceDigest:sha256('synthetic@example.com'),terms:compileCommercialTerms({businessName:'Synthetic Test',contactEmail:'test@example.com',governingLaw:'Synthetic fixture law'})});
 const before=await k.reviewJevReallocation(o);assert.equal(before.transferableUsd,.02);
 await k.confirmRevenuePayment(SARA_PRINCIPAL,intent.id,secret,{schemaVersion:1,provider:'base-usdc-direct',chainId:BASE_MAINNET_CHAIN_ID,tokenContract:BASE_USDC_CONTRACT,transactionHash,transactionReferenceDigest:sha256(transactionHash),senderAddress:'0x'+'1'.repeat(40),recipientAddress:recipient,amountAtomic:'149000000',amountUsd:149,blockNumber:100,latestBlockNumber:111,confirmations:12,verifiedAt:new Date().toISOString()});
 assert.equal((await k.getStatus()).revenuePilotJobs.find(j=>j.id===job.id)?.revenueEvidenceId,null);
 const after=await k.reviewJevReallocation(o);assert.equal(after.transferableUsd,0);assert.ok(after.paidObligations.some(id=>id.includes(intent.id)));assert.notEqual(after.targetId,before.targetId);await assert.rejects(()=>k.reallocateModelBudgetToJev(o,before.targetId),/review changed/);assert.equal((await k.modelBudgetStatus()).remainingUsd,.02);
 // Read-only unit fixtures cover corrupt/orphaned payment associations without changing audit history.
 const readable=k as unknown as {state:()=>Promise<Record<string,unknown>>},original=readable.state.bind(k);
 for(const jobs of [[],[{...job,status:'delivered',deliveredAt:new Date().toISOString(),revenueEvidenceId:'different-ledger-id'}]]){
   readable.state=async()=>({...await original(),revenuePilotJobs:jobs,revenuePaymentIntents:[{...intent,status:'authorized',revenueEvidenceId:'synthetic-payment-ledger-id'}]});
   const orphanOrMismatch=await k.reviewJevReallocation(o);assert.equal(orphanOrMismatch.transferableUsd,0);assert.ok(orphanOrMismatch.paidObligations.includes('payment:'+intent.id));
 }
 }finally{await rm(dir,{recursive:true,force:true});}});

test('rollback baseline budget reader retains full transfer once and ignores Jev subholds across restart',async()=>{const dir=await mkdtemp(join(tmpdir(),'jev-rollback-'));try{const k=await boot(dir);await configure(k,.03,.01);const o=await transfer(k);const legacyReserved=async(kernel:SaraKernel)=>{const month=new Date().toISOString().slice(0,7);return (await kernel.inspectAudit()).filter(event=>['model_budget_reserved','model_budget_opening_charge'].includes(event.type)&&event.occurredAt.slice(0,7)===month).reduce((sum,event)=>sum+(event.data as {amountMicrousd:number}).amountMicrousd,0)/1e6;};
 assert.equal(await legacyReserved(k),.03);const budget=k.jevBudget(o);for(let i=0;i<2;i++){const r=await budget.reserve(input(o.id));assert.ok(r);await budget.record({reservationId:r.id,outcome:'timeout',costMicrousd:null,inputTokens:null,outputTokens:null});}
 assert.equal(await legacyReserved(k),.03);assert.equal((await k.modelBudgetStatus()).reservedUsd,.03);const restarted=await boot(dir);assert.equal(await legacyReserved(restarted),.03);assert.equal((await restarted.modelBudgetStatus()).remainingUsd,0);assert.equal((await restarted.jevBudgetStatus()).reservedUsd,2*JEV_RESERVATION_MICROUSD/1e6);
 const audit=await restarted.inspectAudit();assert.equal(audit.filter(e=>e.type==='model_budget_reserved'&&(e.data as {purpose?:string}).purpose==='second_brain_allocation').length,1);assert.equal(audit.filter(e=>e.type==='model_budget_jev_reserved').length,2);
 }finally{await rm(dir,{recursive:true,force:true});}});
