import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp,rm,cp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { SaraKernel,SARA_PRINCIPAL } from '../src/kernel.ts';
import { canonicalJson,sha256 } from '../src/canonical.ts';
import type { CapabilityInvocation,CapabilityResult } from '../src/digital-capabilities/types.ts';
import type { Json } from '../src/digital-capabilities/schema.ts';
const object=(v:Json)=>v as Record<string,Json>;
const revision='a'.repeat(40),priorRevision='b'.repeat(40),token='synthetic-chain-owner-token';

test('representative software defect traverses real kernel capabilities with durable evidence and truthful release/production boundaries',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'sara-software-chain-')),backup=await mkdtemp(join(tmpdir(),'sara-software-chain-copy-'));
 try{
 const kernel=await SaraKernel.boot({stateDirectory:directory,ownerTokenSha256:sha256(token)});const before=await kernel.getStatus(),auditBefore=await kernel.inspectAudit();const results:CapabilityResult[]=[];
 const invoke=async(capabilityId:string,input:unknown,evidence?:CapabilityInvocation['evidence'])=>{const references=results.map(r=>r.resultDigest);const request:CapabilityInvocation={requestId:`software-chain-${results.length+1}`,capabilityId,input,evidenceReceiptIds:references,...(evidence?{evidence}:{})};const r=await kernel.invokeCapability(SARA_PRINCIPAL,request);assert.notEqual(r.status,'INVALID_INPUT',JSON.stringify(r));assert.notEqual(object(r.output).code,'UNREGISTERED_CAPABILITY');assert.notEqual(object(r.output).code,'QUALIFICATION_FAILED');for(const ref of references)assert.ok(r.evidence.some(e=>e.contentDigest===ref&&e.provenance==='LOCAL'&&e.integrity==='KERNEL_RECEIPT'),`${capabilityId} lost ${ref}`);assert.equal(r.authority.authorizationTokenIssued,false);assert.equal(r.cost.actualCashMicroUsd,0);assert.equal(r.cost.modelApiMicroUsd,0);const{resultDigest,...unsigned}=r;assert.equal(resultDigest,sha256(canonicalJson(unsigned)));results.push(r);return r;};
 // An isolated in-test defect fixture. It never reads or changes a production report.
 const faultyExport=(approved:boolean,approvedRevision:string,requestedRevision:string)=>approved?{revision:requestedRevision,body:'fixture-report'}:null;
 const defect=faultyExport(true,priorRevision,revision);assert.equal(defect?.revision,revision,'The fixture incorrectly permits an unreviewed revision.');
 const report={problem:'An approved report export permits a newer, unreviewed revision.',approvedRevision:priorRevision,requestedRevision:revision,observed:JSON.stringify(defect),source:'isolated-test-fixture'};
 const reproduce=await invoke('bug-reproduction-planner',{report:report.problem,expected:'Reject export when reviewed revision differs from the requested exact revision.',observed:'An export for the new revision was returned.',steps:['Approve revision B in an isolated copy.','Request export of revision A using the old approval.'],target:'PRODUCTION',environment:'Controlled local TypeScript fixture'},[{sourceId:'synthetic-customer-report',content:report,claimedProvenance:'PRODUCTION'}]);assert.equal(object(reproduce.output).reproductionTarget,'ISOLATED_COPY');assert.equal(object(reproduce.output).executionAllowed,false);assert.equal(reproduce.evidence[0]!.provenance,'SUPPLIED');
 const root=await invoke('root-cause-analyzer',{symptom:report.problem,observations:[{id:'trigger',role:'TRIGGER',statement:'The requested revision differs from the reviewed revision.',evidenceRefs:[reproduce.resultDigest]},{id:'defect',role:'DEFECT',statement:'The reproduced fixture checks approval presence but omits exact reviewed-revision equality.',evidenceRefs:[reproduce.resultDigest]},{id:'counter',role:'COUNTEREXAMPLE',statement:'A matching reviewed revision also renders correctly, so a universal renderer failure is unsupported.',evidenceRefs:[reproduce.resultDigest]}],hypotheses:[{id:'binding',cause:'Approval is not bound to the exact requested revision.',supporting:['trigger','defect'],contradicting:[]},{id:'renderer',cause:'The renderer always emits the wrong revision.',supporting:[],contradicting:['counter']}]});assert.equal(object(root.output).rootCauseEstablished,false);assert.equal((object(root.output).hypotheses as Record<string,Json>[])[0]!.id,'binding');
 const diagnostic=await invoke('diagnostic-experiment-designer',{hypotheses:[{id:'binding',evidenceRefs:[root.resultDigest]},{id:'renderer',evidenceRefs:[root.resultDigest]}],experiments:[{id:'compare-local-revision-check',target:'ISOLATED',costMicroUsd:0,durationSeconds:1,predictions:[{hypothesisId:'binding',outcome:'mismatch-only-fails'},{hypothesisId:'renderer',outcome:'all-revisions-fail'}],evidenceRefs:[root.resultDigest]},{id:'mutate-production-approval',target:'PRODUCTION_MUTATION',costMicroUsd:0,durationSeconds:1,predictions:[{hypothesisId:'binding',outcome:'one'},{hypothesisId:'renderer',outcome:'two'}],evidenceRefs:[root.resultDigest]}],availableCashMicroUsd:0});assert.equal(object(diagnostic.output).selectedId,'compare-local-revision-check');assert.equal(object(diagnostic.output).executionAuthorized,false);assert.equal((object(diagnostic.output).rejected as Record<string,Json>[])[0]!.id,'mutate-production-approval');
 const fix=await invoke('minimal-fix-selector',{requiredCriteria:['bind-exact-revision','deny-stale-approval'],candidates:[{id:'hide-warning',paths:['src/ui.ts'],addressesRootCause:false,criteria:[],risk:'LOW',estimatedCashMicroUsd:0},{id:'bind-approved-revision',paths:['src/delivery.ts','tests/delivery.test.ts'],addressesRootCause:true,criteria:['bind-exact-revision','deny-stale-approval'],risk:'LOW',estimatedCashMicroUsd:0}]});assert.equal(object(fix.output).selectedId,'bind-approved-revision');assert.equal(object(fix.output).verifiedFix,false);
 const correctedExport=(approved:boolean,approvedRevision:string,requestedRevision:string)=>approved&&approvedRevision===requestedRevision?{revision:requestedRevision,body:'fixture-report'}:null;assert.equal(correctedExport(true,priorRevision,revision),null);assert.equal(correctedExport(false,revision,revision),null);assert.equal(correctedExport(true,revision,revision)?.revision,revision);
 const gaps=await invoke('test-gap-mapper',{revision,behaviors:[{id:'exact-reviewed-export',requiredKinds:['POSITIVE','NEGATIVE','AUTHORIZATION','RESTART']}],tests:[{id:'matching-revision',behaviorId:'exact-reviewed-export',kind:'POSITIVE',revision,status:'PASSED'},{id:'old-denial',behaviorId:'exact-reviewed-export',kind:'AUTHORIZATION',revision:priorRevision,status:'PASSED'}]});assert.deepEqual((object(gaps.output).gaps as Record<string,Json>[])[0]!.missingKinds,['AUTHORIZATION','NEGATIVE','RESTART']);assert.deepEqual(object(gaps.output).staleTests,['old-denial']);assert.equal(object(gaps.output).observedCoverageVerified,false);
 const impact=await invoke('repository-change-impact-analyzer',{changedFiles:['src/delivery.ts'],graph:{nodes:[{id:'delivery',path:'src/delivery.ts',kind:'AUTHORIZATION'},{id:'api',path:'src/api.ts',kind:'API'},{id:'test',path:'tests/delivery.test.ts',kind:'TEST'},{id:'docs',path:'docs/readme.md',kind:'DOCUMENTATION'}],edges:[{from:'api',to:'delivery',relation:'CALLS'},{from:'test',to:'delivery',relation:'COVERS'}]}});assert.deepEqual((object(impact.output).impacted as Record<string,Json>[]).map(n=>n.id),['delivery','api','test']);assert.equal(object(impact.output).externalChangesAuthorized,false);
 const review=await invoke('pull-request-risk-review',{revision,changes:[{path:'src/delivery.ts',diff:'- if (approval) return exportReport(requestedRevision);\n+ if (approval && approvedRevision === requestedRevision) return exportReport(requestedRevision);',declaredAreas:['AUTHORIZATION','DATA_INTEGRITY']}]});assert.ok((object(review.output).requiredVerification as string[]).includes('authorization-denial'));assert.equal(object(review.output).behaviorProven,false);assert.equal(object(review.output).mergeAuthorized,false);
 const categoryProvenance={CI:'CI',SECURITY:'CI',QUALIFICATION:'ISOLATED',CONFIGURATION:'LOCAL',MIGRATION:'LOCAL',DEPLOYMENT:'STAGING',ARTIFACT:'CI',ROLLBACK:'ISOLATED'};const artifactDigest=sha256(correctedExport.toString());
 const release=await invoke('release-readiness-gate',{revision,blockers:[],requirements:Object.entries(categoryProvenance).map(([category,provenance])=>({id:`required-${category.toLowerCase()}`,category,provenance,claim:`independent-${category.toLowerCase()}-acceptance`})),proofIds:results.map(r=>r.resultDigest),artifacts:[{id:'isolated-fix-fixture',expectedDigest:artifactDigest,observedDigest:artifactDigest}]});assert.equal(release.status,'INCOMPLETE_EVIDENCE');assert.equal(object(release.output).status,'INCOMPLETE_EVIDENCE');assert.equal(object(release.output).deploymentAuthorized,false);assert.ok((object(release.output).checks as Record<string,Json>[]).every(c=>c.passed===false));
 const productionInput={deploymentSha:revision,deploymentId:'synthetic-deployment-identity',behavior:'deny-stale-report-delivery',proofIds:results.map(r=>r.resultDigest)};const productionEvidence=[{sourceId:'supplied-deployment-status',content:{status:'successful',deploymentSha:revision,deploymentId:'synthetic-deployment-identity'},claimedProvenance:'PRODUCTION'}];const production=await invoke('production-proof-validator',productionInput,productionEvidence);assert.equal(production.status,'INCOMPLETE_EVIDENCE');assert.equal(object(production.output).productionBehaviorProven,false);assert.equal(object(production.output).deploymentSuccessAloneSufficient,false);assert.ok(production.evidence.every(e=>e.provenance==='LOCAL'||e.provenance==='SUPPLIED'));
 const after=await kernel.getStatus();for(const field of ['constitution','emergencyStopped','ownerFundedRecurringMonthlyUsd','realizedProfit','reservedSelfDevelopmentBudgetUsd','availableCompoundReserveUsd','memoryCount','learning','jobs','mutations','standingMandate','revenuePilotJobs','revenueDeliveries'] as const)assert.deepEqual(after[field],before[field],field);
 const audit=await kernel.inspectAudit();assert.deepEqual(audit.slice(0,auditBefore.length),auditBefore);const appended=audit.slice(auditBefore.length);assert.equal(appended.length,results.length);assert.ok(appended.every(e=>e.type==='digital_capability_executed'));for(let n=1;n<audit.length;n++)assert.equal(audit[n]!.previousHash,audit[n-1]!.hash);
 await cp(directory,backup,{recursive:true});const restored=await SaraKernel.boot({stateDirectory:backup,ownerTokenSha256:sha256(token)});const restoredAuditBefore=await restored.inspectAudit();assert.deepEqual(restoredAuditBefore.slice(0,audit.length),audit);const replay=await restored.invokeCapability(SARA_PRINCIPAL,{requestId:`software-chain-${results.length}`,capabilityId:'production-proof-validator',input:productionInput,evidenceReceiptIds:results.slice(0,-1).map(r=>r.resultDigest),evidence:productionEvidence});assert.equal(replay.replayed,true);assert.equal(replay.resultDigest,production.resultDigest);assert.equal(replay.receiptValidity?.current,true);assert.deepEqual(replay.output,production.output);assert.deepEqual(replay.evidence,production.evidence);assert.equal((await restored.inspectAudit()).length,restoredAuditBefore.length);
 }finally{await rm(directory,{recursive:true,force:true});await rm(backup,{recursive:true,force:true});}
});
