import { arraySchema as arr, digestSchema as digest, enumSchema as en, idSchema as id, integerSchema as int, objectSchema as obj, textSchema as txt, type Schema } from '../schema.ts';
import { bool, nullable as nil, provenanceSchema } from '../engineering/common.ts';
export const strings=arr(txt(4096),100),proofs=arr(txt(128),100);
export const action=en('READ','FILL','CLICK','SUBMIT','PURCHASE','TRANSFER','SUBSCRIBE','DELETE','PUBLISH','SECURITY_CHANGE','PERMISSION_CHANGE','SEND','CONTRACT','UNKNOWN');
export const actionInput=obj({action,target:txt(1024),label:txt(512,0),pageText:txt(8000,0),external:bool,estimatedCashMicroUsd:int(),credentialsInvolved:bool});
export const riskOutput=obj({action,target:txt(1024),allowed:bool,authorityClass:txt(64),boundary:en('READ','DRAFT','FINANCIAL','CONTRACTUAL','SECURITY','EXTERNAL_MUTATION','UNKNOWN'),reason:txt(1024),code:txt(128),injectionDetected:bool,externalActionPerformed:bool,authorityGranted:bool});
export const page=obj({pageId:id,sourceUrl:txt(2048),revision:txt(128),title:txt(512,0),elements:arr(obj({id,role:en('HEADING','TEXT','LINK','BUTTON','INPUT','FORM'),text:txt(4096,0),href:nil(txt(2048)),fieldType:nil(en('TEXT','EMAIL','NUMBER','PASSWORD','TOKEN','CHECKBOX')),value:nil(txt(2048,0))}),100)});
const capture=obj({pageId:id,revision:txt(128),width:int(1,128),height:int(1,128),rgba:arr(int(0,255),65536,4)});
const flags={externalActionPerformed:bool,authorityGranted:bool};
export const webSchemas:Record<string,{input:Schema;output:Schema}>={
 'browser-task-planner':{input:obj({goal:txt(2048),steps:arr(obj({id,action:actionInput,dependsOn:arr(id,100)}),100)}),output:obj({goal:txt(2048),steps:arr(obj({id,classification:riskOutput}),100),executionOrder:arr(id,100),blockedStepIds:arr(id,100),status:en('PLAN_READY','BLOCKED'),...flags})},
 'website-state-reader':{input:obj({page,sandboxHtml:txt(65536,0)},['page']),output:obj({pageId:id,revision:txt(128),sourceUrl:txt(2048),title:txt(512,0),headings:strings,text:strings,links:arr(obj({id,label:txt(4096,0),url:nil(txt(2048))}),100),forms:arr(id,100),redactedFieldIds:arr(id,100),snapshotDigest:digest,provenance:en('SUPPLIED','ISOLATED'),sandboxBrowserObserved:bool,externalStateObserved:bool,injectionDetected:bool,...flags})},
 'form-completion-planner':{input:obj({page,values:arr(obj({fieldId:id,value:txt(2048,0)}),100),requiredFieldIds:arr(id,100),submitAction:actionInput}),output:obj({pageId:id,revision:txt(128),preparedFields:arr(obj({fieldId:id,value:txt(2048,0)}),100),missingFields:arr(id,100),blockedFields:arr(id,100),submission:riskOutput,status:en('DRAFT_READY','INCOMPLETE_EVIDENCE','BLOCKED'),submitAuthorized:bool,...flags})},
 'web-change-verifier':{input:obj({pageId:id,revision:txt(128),expected:arr(obj({key:id,value:txt(2048,0)}),100),observed:arr(obj({key:id,value:txt(2048,0)}),100),provenance:provenanceSchema,proofIds:proofs}),output:obj({pageId:id,revision:txt(128),status:en('VERIFIED','MISMATCH','INCOMPLETE_EVIDENCE'),mismatches:arr(obj({key:id,expected:txt(2048,0),observed:nil(txt(2048,0))}),100),independentStateVerified:bool,observationDigest:digest,...flags})},
 'visual-regression-inspector':{input:obj({before:capture,after:capture,channelTolerance:int(0,255),maximumChangedBasisPoints:int(0,10000)}),output:obj({status:en('EXACT_PIXEL_MATCH','WITHIN_TOLERANCE','REGRESSION','SUBJECT_MISMATCH','DIMENSION_MISMATCH'),beforeDigest:digest,afterDigest:digest,comparedPixels:int(),changedPixels:int(),changedBasisPoints:int(0,10000),maximumChannelDelta:int(0,255),boundingBox:nil(obj({x:int(),y:int(),width:int(),height:int()})),semanticEquivalenceProven:bool,...flags})},
 'checkout-boundary-detector':{input:obj({url:txt(2048),buttonText:txt(512,0),pageText:txt(8000,0)}),output:obj({boundaryDetected:bool,categories:strings,signals:strings,requiredAuthority:en('CONSEQUENTIAL_REQUIRES_OWNER','READ_ONLY'),injectionDetected:bool,crossingAuthorized:bool,...flags})},
 'external-action-risk-classifier':{input:actionInput,output:riskOutput},
};
