import type { CapabilityDefinition } from '../types.ts';import { webSchemas } from './contracts.ts';import { webCases } from './qualification.ts';import { classify,plan,readState,form,verifyChange,visual,checkout } from './operations.ts';
const impl:Record<string,{execute:CapabilityDefinition['execute'];description:string;draft?:boolean}>={
'browser-task-planner':{execute:plan,description:'Plan dependency-ordered browser steps through the shared boundary checker, exposing consequential transitions before execution.',draft:true},
'website-state-reader':{execute:readState,description:'Read bounded source-identified page snapshots, redact credential fields and retain untrusted instruction flags; supplied snapshots do not establish live state.'},
'form-completion-planner':{execute:form,description:'Prepare bounded sandbox field representations while rejecting sensitive fields and keeping submission behind the exact authority gate.',draft:true},
'web-change-verifier':{execute:verifyChange,description:'Compare expected state with supplied observations and require independent exact-page/revision capture before verifying an external change.'},
'visual-regression-inspector':{execute:visual,description:'Compare actual supplied RGBA pixels with bounded tolerances and changed-region coordinates; no semantic equivalence or production claim.'},
'checkout-boundary-detector':{execute:checkout,description:'Detect checkout, subscription, transfer and contract language without granting authority to cross a financial boundary.'},
'external-action-risk-classifier':{execute:classify,description:'Use the existing shared autonomy checker to classify proposed browser actions and reject untrusted page authority.'},
};
export const webDefinitions:readonly CapabilityDefinition[]=Object.entries(impl).map(([id,x])=>({id,version:'1.0.0',description:x.description,inputSchema:webSchemas[id]!.input,outputSchema:webSchemas[id]!.output,effect:id==='website-state-reader'?'READ_ONLY':x.draft?'DRAFT_ONLY':'PURE',authorityClass:x.draft?'DRAFT_ONLY':'READ_ONLY',resources:['supplied-input','actor-visible-kernel-evidence-receipts',...(id==='website-state-reader'?['temporary-isolated-browser-profile']:[])],sourceFiles:['web/contracts.ts','web/operations.ts','web/qualification.ts','web/definitions.ts','web/sandbox-browser.ts','engineering/common.ts'],qualificationRequirements:['frozen-contract','malformed-input','prompt-injection-denial','shared-authority-gate','source-provenance','no-external-effect','actual-pixel-comparison',...(id==='website-state-reader'?['isolated-browser-adapter-qualification']:[])],execute:x.execute,cases:webCases[id]!}));
