// Frozen V8 verifier bytes. Never disclosed to the model prompt.
export const protectedTests = `import {add,discount,remove,total} from "../src/index.ts";
import {deepStrictEqual as eq,notStrictEqual,throws} from "node:assert/strict";
// PRIVATE_V8_INVENTORY_ORACLE
const a={sku:"A",quantity:2,unitCents:199};
const b={sku:"B-2",quantity:3,unitCents:250};
const c={sku:"C3",quantity:1,unitCents:99};
eq(add([],a),[{sku:"A",quantity:2,unitCents:199}]);
eq(add([a],b),[a,b]);
eq(add([a,b],{sku:"A",quantity:3,unitCents:199}),[{sku:"A",quantity:5,unitCents:199},b]);
eq(add([a,b],{sku:"B-2",quantity:17,unitCents:250}),[a,{sku:"B-2",quantity:20,unitCents:250}]);
throws(()=>add([a],{sku:"A",quantity:1,unitCents:200}),RangeError);
throws(()=>add([a],{sku:"A",quantity:19,unitCents:199}),RangeError);
throws(()=>add([{sku:"A",quantity:1,unitCents:100},{sku:"A",quantity:1,unitCents:100}],b),RangeError);
throws(()=>add([],{sku:"bad",quantity:1,unitCents:100}),RangeError);
throws(()=>add([],{sku:"A",quantity:0,unitCents:100}),RangeError);
throws(()=>add([],{sku:"A",quantity:21,unitCents:100}),RangeError);
throws(()=>add([],{sku:"A",quantity:1.5,unitCents:100}),RangeError);
throws(()=>add([],{sku:"A",quantity:1,unitCents:0}),RangeError);
throws(()=>add([],{sku:"A",quantity:1,unitCents:100001}),RangeError);
throws(()=>add([],{sku:"A",quantity:1,unitCents:1.5}),RangeError);
eq(discount([],0),[]);
eq(discount([a,b,c],0),[a,b,c]);
eq(discount([a,b,c],1),[{sku:"A",quantity:2,unitCents:197},{sku:"B-2",quantity:3,unitCents:247},{sku:"C3",quantity:1,unitCents:98}]);
eq(discount([a,b,c],25),[{sku:"A",quantity:2,unitCents:149},{sku:"B-2",quantity:3,unitCents:187},{sku:"C3",quantity:1,unitCents:74}]);
eq(discount([a,b,c],50),[{sku:"A",quantity:2,unitCents:99},{sku:"B-2",quantity:3,unitCents:125},{sku:"C3",quantity:1,unitCents:49}]);
eq(discount([{sku:"A",quantity:1,unitCents:1}],50),[{sku:"A",quantity:1,unitCents:1}]);
throws(()=>discount([a],-1),RangeError);
throws(()=>discount([a],51),RangeError);
throws(()=>discount([a],1.5),RangeError);
throws(()=>discount([{sku:"bad",quantity:1,unitCents:100}],1),RangeError);
eq(remove([],[]),[]);
eq(remove([],["A"]),[]);
eq(remove([a,b,c],[]),[a,b,c]);
eq(remove([a,b,c],["A"]),[b,c]);
eq(remove([a,b,c],["B-2","B-2","MISSING"]),[a,c]);
eq(remove([a,b,c],["A","B-2","C3"]),[]);
throws(()=>remove([], ["bad"]),RangeError);
throws(()=>remove([{sku:"bad",quantity:1,unitCents:100}],[]),RangeError);
eq(total([]),0);
eq(total([a]),398);
eq(total([a,b]),1148);
eq(total([a,b,c]),1247);
eq(total([{sku:"X",quantity:20,unitCents:100000}]),2000000);
throws(()=>total([{sku:"A",quantity:0,unitCents:100}]),RangeError);
throws(()=>total([{sku:"A",quantity:1,unitCents:100},{sku:"A",quantity:2,unitCents:100}]),RangeError);
const addInput=[{sku:"A",quantity:2,unitCents:199},{sku:"B-2",quantity:3,unitCents:250}];
const addOut=add(addInput,{sku:"C3",quantity:1,unitCents:99});
eq(addInput,[{sku:"A",quantity:2,unitCents:199},{sku:"B-2",quantity:3,unitCents:250}]);
notStrictEqual(addOut,addInput);const [addOutA,addOutB]=addOut;const [addInA,addInB]=addInput;notStrictEqual(addOutA,addInA);notStrictEqual(addOutB,addInB);
const mergeOut=add(addInput,{sku:"A",quantity:1,unitCents:199});
const [mergeA,mergeB]=mergeOut;notStrictEqual(mergeA,addInA);notStrictEqual(mergeB,addInB);
const discountOut=discount(addInput,10);notStrictEqual(discountOut,addInput);const [discountA,discountB]=discountOut;notStrictEqual(discountA,addInA);notStrictEqual(discountB,addInB);
const removeOut=remove(addInput,["B-2"]);notStrictEqual(removeOut,addInput);const [removeA]=removeOut;notStrictEqual(removeA,addInA);
`;
