import { arraySchema as arr, digestSchema as digest, enumSchema as en, idSchema as id, integerSchema as integer, objectSchema as obj, textSchema as txt, type Schema } from '../schema.ts';
import { bool, nullable as nil, shaSchema } from '../engineering/common.ts';
export const strings=arr(txt(2048),100),ids=arr(id,100),proofs=arr(txt(128),100);
const currency:Schema={type:'string',pattern:'^[A-Z]{3}$',minLength:3,maxLength:3};
export const trustedProvenance=en('UNIT_TEST','CI','ISOLATED','STAGING','PRODUCTION','EXTERNAL_READ_ONLY','OWNER_OBSERVED');
const flags={externalActionPerformed:bool,authorityGranted:bool};
export const criterion=obj({id,description:txt(2048),provenance:trustedProvenance,proofIds:proofs});
export const acceptanceInput=obj({jobId:id,serviceFamily:id,originalRequest:txt(4096),requiredCapabilityIds:ids,scope:strings,exclusions:strings,criteria:arr(criterion,100),deliveredRevision:shaSchema,deploymentId:nil(txt(128)),deploymentSha:nil(shaSchema),limitations:strings});
const proofCheck=obj({id:txt(128),status:txt(64),reasons:strings});
const verification=obj({criterionId:id,status:en('PASS','FAIL','INCOMPLETE_EVIDENCE'),requiredProvenance:trustedProvenance,inspected:arr(proofCheck,100)});
const accepted=obj({jobId:id,serviceFamily:id,status:en('PASS','FAIL','INCOMPLETE_EVIDENCE'),scopeDigest:digest,originalRequest:txt(4096),requiredCapabilityIds:ids,scope:strings,exclusions:strings,deliveredRevision:shaSchema,criteria:arr(verification,100),criterionDescriptions:strings,limitations:strings,independentlyVerified:bool,customerCommunicationAuthorized:bool,...flags});
const need=obj({id,description:txt(2048),customerValue:txt(2048),provenance:trustedProvenance,proofIds:proofs});
const needs=arr(need,100);
const needOut=obj({id,description:txt(2048),customerValue:txt(2048),status:en('VERIFIED','UNVERIFIED'),evidenceIds:proofs});
const design=obj({experimentId:id,hypothesis:txt(2048),metric:txt(128),minimumThreshold:integer(),direction:en('MAXIMIZE','MINIMIZE'),costCeilingMicroUsd:integer(),startedAt:txt(64)});
const observed=obj({metricValue:integer(),actualCashCostMicroUsd:integer(),actualRevenueMicroUsd:integer(),predictedRevenueMicroUsd:nil(integer())});
export const businessSchemas:Record<string,{input:Schema;output:Schema}>={
 'website-maintenance-scope-estimator':{input:obj({request:txt(4096),repository:txt(256),revision:shaSchema,changedAreas:arr(obj({path:txt(512),system:en('CONTENT','UI','API','AUTH','DATA','DEPLOYMENT','INTEGRATION'),reason:txt(1024)}),100),requiredCapabilityIds:ids,exclusions:strings,dependencies:strings,acceptanceCriteria:strings,requestedAction:en('ANALYZE','DRAFT','IMPLEMENT','DEPLOY')}),output:obj({requestedOutcome:txt(4096),repository:txt(256),revision:shaSchema,likelyAffectedSystems:strings,likelyFiles:strings,exclusions:strings,dependencies:strings,riskClass:en('LOW','MEDIUM','HIGH'),workClass:en('ANALYSIS','DRAFT','BOUNDED_CODE_CHANGE','CONSEQUENTIAL_DEPLOYMENT'),acceptanceCriteria:strings,requiredTests:strings,rollbackRequirements:strings,missingCapabilities:ids,allCapabilitiesAvailable:bool,safeAutonomousExecutionAllowed:bool,authorityReason:txt(512),...flags})},
 'market-demand-validator':{input:obj({serviceId:id,observations:arr(obj({id,sourceId:txt(256),statement:txt(2048),kind:en('SUPPORT','COUNTEREVIDENCE'),provenance:en('EXTERNAL_READ_ONLY','PRODUCTION','OWNER_OBSERVED'),proofIds:proofs}),100),inferences:strings,speculation:strings}),output:obj({serviceId:id,status:en('VALIDATED','CONTESTED','NO_SUPPORTING_DEMAND','INSUFFICIENT_EVIDENCE'),observedEvidence:arr(obj({id,sourceId:txt(256),statement:txt(2048),kind:en('SUPPORT','COUNTEREVIDENCE'),verified:bool,proofIds:proofs}),100),marketInferences:strings,speculation:strings,unknowns:strings,...flags})},
 'competitive-offer-analyzer':{input:obj({offers:arr(obj({id,sourceId:txt(256),sourceUrl:nil(txt(2048)),priceMicro:nil(integer()),currency:nil(currency),billingUnit:nil(en('ONE_TIME','MONTH','YEAR','HOUR')),scope:strings,deliverables:strings,turnaround:nil(txt(256)),exclusions:strings,guarantees:strings,positioning:nil(txt(1024)),customerSegment:nil(txt(256))}),100)}),output:obj({comparisons:arr(obj({offerId:id,sourceId:txt(256),sourceUrl:nil(txt(2048)),priceMicro:nil(integer()),currency:nil(currency),billingUnit:nil(en('ONE_TIME','MONTH','YEAR','HOUR')),scope:strings,deliverables:strings,turnaround:nil(txt(256)),exclusions:strings,guarantees:strings,positioning:nil(txt(1024)),customerSegment:nil(txt(256)),missingFields:strings,provenance:en('SUPPLIED')}),100),comparablePriceGroups:arr(obj({currency,billingUnit:txt(32),minimumMicro:integer(),maximumMicro:integer(),offerIds:ids}),100),externallyVerified:bool,...flags})},
 'proposal-compiler':{input:obj({opportunityId:id,approvalReceiptId:nil(digest),problem:txt(4096),scope:strings,deliverables:strings,exclusions:strings,acceptanceCriteria:strings,sequence:strings,priceMicro:nil(integer()),currency:nil(currency),paymentAssumptions:strings,customerResponsibilities:strings,limitations:strings}),output:obj({opportunityId:id,status:en('DRAFT','INCOMPLETE_EVIDENCE'),approvalVerified:bool,problemStatement:txt(4096),scope:strings,deliverables:strings,exclusions:strings,acceptanceCriteria:strings,sequence:strings,priceMicro:nil(integer()),currency:nil(currency),paymentAssumptions:strings,customerResponsibilities:strings,limitations:strings,missingFacts:strings,bindingOffer:bool,...flags})},
 'customer-acceptance-verifier':{input:acceptanceInput,output:accepted},
 'delivery-evidence-pack-compiler':{input:obj({jobId:id,revision:shaSchema,acceptanceReceiptId:digest,changes:strings,rollbackInformation:strings,screenshotProofIds:proofs}),output:obj({jobId:id,revision:shaSchema,status:en('DRAFT_READY','INCOMPLETE_EVIDENCE'),acceptanceReceiptId:digest,originalRequest:nil(txt(4096)),agreedScope:strings,exclusions:strings,changes:strings,criterionEvidence:arr(verification,100),screenshots:proofs,knownLimitations:strings,rollbackInformation:strings,missingEvidence:strings,deliveryAuthorized:bool,...flags})},
 'upsell-opportunity-detector':{input:obj({jobId:id,revision:shaSchema,acceptanceReceiptId:digest,needs}),output:obj({jobId:id,status:en('CANDIDATES','INSUFFICIENT_EVIDENCE'),opportunities:arr(needOut,100),unverifiedNeeds:arr(needOut,100),completedWorkVerified:bool,outreachAuthorized:bool,...flags})},
 'recurring-revenue-converter':{input:obj({jobId:id,revision:shaSchema,observations:arr(obj({occurrenceId:id,needId:id,description:txt(2048),customerValue:txt(2048),provenance:trustedProvenance,proofIds:proofs}),100),proposedCadence:nil(txt(256)),cancellationTerms:txt(1024,0),customerOwnsData:bool}),output:obj({jobId:id,status:en('CANDIDATE','INSUFFICIENT_EVIDENCE','BLOCKED'),recurringNeeds:arr(obj({needId:id,occurrenceIds:ids,customerValue:strings}),100),cadence:nil(txt(256)),cancellationTerms:txt(1024,0),customerOwnsData:bool,reason:txt(1024),advertisementAuthorized:bool,...flags})},
 'customer-retention-planner':{input:obj({jobId:id,revision:shaSchema,acceptanceReceiptId:digest,needs}),output:obj({jobId:id,status:en('DRAFT','INSUFFICIENT_EVIDENCE'),actions:arr(obj({needId:id,action:txt(2048),customerValue:txt(2048),evidenceIds:proofs}),100),unverifiedNeeds:ids,outreachAuthorized:bool,...flags})},
 'business-experiment-evaluator':{input:obj({phase:en('REGISTER','EVALUATE'),design,registrationReceiptId:nil(digest),result:nil(observed),resultProvenance:trustedProvenance,proofIds:proofs}),output:obj({experimentId:id,phase:en('REGISTER','EVALUATE'),status:en('DESIGN_RECORDED','SUCCESS','FAILED','INCOMPLETE_EVIDENCE'),design,designDigest:digest,registrationVerified:bool,resultVerified:bool,metricValue:nil(integer()),actualCashCostMicroUsd:nil(integer()),actualRevenueMicroUsd:nil(integer()),predictedRevenueMicroUsd:nil(integer()),thresholdMet:nil(bool),withinCostCeiling:nil(bool),recommendation:en('AWAIT_RESULT','CONSIDER_CONTINUATION','STOP_OR_REVISE','GATHER_EVIDENCE'),reason:txt(1024),...flags})},
 'repeatable-service-productizer':{input:obj({serviceFamily:id,acceptedJobReceiptIds:arr(digest,100),requiredCapabilityIds:ids,intakeRequirements:strings,humanOnlyBoundaries:strings}),output:obj({serviceFamily:id,status:en('CANDIDATE','INSUFFICIENT_EVIDENCE'),verifiedJobIds:ids,rejectedReceiptIds:arr(digest,100),missingCapabilities:ids,commonScope:strings,commonAcceptanceCriteria:strings,intakeRequirements:strings,humanOnlyBoundaries:strings,procedureEvidenceDigests:arr(digest,100),priceBand:nil(obj({minimumMicro:integer(),maximumMicro:integer(),currency})),expectedCostMicroUsd:nil(integer()),automationPercentage:nil(integer(0,100)),advertisementAuthorized:bool,...flags})},
};
