import { arraySchema as list, objectSchema as obj, textSchema as text, idSchema as id, integerSchema as integer, enumSchema as choice, digestSchema, type Schema } from '../schema.ts';
const nullable=(s:Schema):Schema=>({...s,nullable:true});
const bool:Schema={type:'boolean'};
const ids=list(id,256);
const texts=list(text(1024),256);
const state=choice('PENDING','COMPLETED','IN_FLIGHT','FAILED');
export const stepSchema=obj({id,status:state,dependencies:ids,effect:choice('PURE','EXTERNAL_EFFECT'),receiptDigest:nullable(digestSchema),idempotencyKey:nullable(id)});
export const failureSchema=obj({id,sourceId:id,subsystem:id,code:nullable(text(128)),message:text(8192,0),frames:list(text(512),32)});
export const reasonSchema=choice('MISSING_EVIDENCE','MISSING_CAPABILITY','MISSING_AUTHORITY','EXTERNAL_OUTAGE','FAILED_PREREQUISITE','HUMAN_ONLY','ECONOMIC_STOP','POLICY_PROHIBITION','UNKNOWN');
export const schemas:Record<string,{input:Schema;output:Schema}>={
 'failure-clusterer':{input:obj({failures:list(failureSchema,256)}),output:obj({families:list(obj({signature:digestSchema,category:text(128),subsystem:id,eventIds:ids,sourceIds:ids,occurrences:integer(),rootCauseProven:bool}),256),duplicateEventIds:ids,sourceDigest:digestSchema})},
 'retry-worthiness-classifier':{input:obj({failure:failureSchema,attempts:integer(0,100),maximumAttempts:integer(0,100),remainingBudgetMicroUsd:integer(),estimatedAttemptMicroUsd:integer(),effect:choice('PURE','EXTERNAL_EFFECT'),completion:choice('NOT_STARTED','NOT_COMPLETED','COMPLETED','UNKNOWN'),idempotencyKey:nullable(id),retryAfterSeconds:nullable(integer(0,86400))}),output:obj({category:text(128),decision:choice('CONDITIONAL_RETRY','DO_NOT_RETRY','DIAGNOSE'),reasons:texts,delaySeconds:nullable(integer(0,86400)),remainingAttempts:integer(0,100),executionAuthorized:bool,evidenceDigest:digestSchema})},
 'diagnostic-experiment-designer':{input:obj({hypotheses:list(obj({id,evidenceRefs:ids}),64),experiments:list(obj({id,target:choice('READ_ONLY','ISOLATED','PRODUCTION_MUTATION'),costMicroUsd:integer(),durationSeconds:integer(0,86400),predictions:list(obj({hypothesisId:id,outcome:id}),64),evidenceRefs:ids}),128),availableCashMicroUsd:integer()}),output:obj({selectedId:nullable(id),ranking:list(obj({id,distinguishedPairs:integer(),costMicroUsd:integer(),durationSeconds:integer(),missingPredictionIds:ids}),128),rejected:list(obj({id,reasons:texts}),128),status:choice('DRAFT_READY','INCOMPLETE_EVIDENCE'),executionAuthorized:bool,sourceDigest:digestSchema})},
 'recovery-state-reconstructor':{input:obj({jobId:id,revision:id,journal:list(stepSchema,256)}),output:obj({status:choice('CONTINUATION_IDENTIFIED','RECONCILE_EXTERNAL_COMPLETION','BLOCKED','EVIDENCE_REQUIRED','COMPLETE'),basis:choice('TRUSTED_DURABLE_STATE','SUPPLIED_JOURNAL_ONLY'),completedIds:ids,resumeIds:ids,reconcileIds:ids,blockedIds:ids,accounting:nullable(obj({spentMicroUsd:nullable(integer()),reservedMicroUsd:nullable(integer())})),auditHead:nullable(digestSchema),sourceDigest:digestSchema,executionAuthorized:bool})},
 'blocked-work-resolver':{input:obj({taskId:id,tasks:list(obj({id,completed:bool,dependencies:ids,blockers:list(obj({id,kind:reasonSchema,evidenceRefs:ids,detail:text(1024)}),64)}),256)}),output:obj({status:choice('UNBLOCKED','BLOCKED','INCOMPLETE_EVIDENCE'),roots:list(obj({taskId:id,blockerId:nullable(id),kind:reasonSchema,evidenceRefs:ids,detailDigest:digestSchema}),256),missingTaskIds:ids,cycleTaskIds:ids,nextAction:text(1024),executionAuthorized:bool})},
 'escalation-quality-controller':{input:obj({taskId:id,reason:reasonSchema,evidenceRefs:ids,alternatives:list(obj({id,outcome:choice('FAILED','UNAVAILABLE','UNTRIED','SUCCEEDED'),evidenceRefs:ids}),64),decision:nullable(text(1024)),choices:list(obj({id,effect:text(1024)}),16)}),output:obj({status:choice('OWNER_DECISION_READY','MORE_DIAGNOSIS_REQUIRED','NO_ESCALATION_REQUIRED'),taskId:id,reason:reasonSchema,evidenceRefs:ids,attemptedAlternativeIds:ids,untriedAlternativeIds:ids,decision:nullable(text(1024)),choices:list(obj({id,effect:text(1024)}),16),missingFacts:texts,transmissionAuthorized:bool})},
};
