import { arraySchema as arr, digestSchema as digest, enumSchema as en, idSchema as id, integerSchema as int, objectSchema as obj, textSchema as txt, type Schema } from '../schema.ts';
import { bool,nullable as nil,provenanceSchema } from '../engineering/common.ts';
export const strings=arr(txt(2048),100),ids=arr(id,100),proofs=arr(txt(128),100);
const authority=en('READ_ONLY','DRAFT_ONLY','REVERSIBLE_AUTHORIZED','CONSEQUENTIAL_REQUIRES_OWNER','PROHIBITED');
const flags={externalCommunicationPerformed:bool,authorityGranted:bool};
const manifestCapability=obj({id,version:txt(64),contractDigest:digest,description:txt(2048),authorityClass:txt(64)});
export const contractInput=obj({contractId:id,agentId:id,taskClass:id,goal:txt(2048),inputs:strings,outputs:strings,exclusions:strings,requestedAuthority:authority,dataBoundaries:arr(en('PUBLIC','AUTHORIZED_JOB_DATA','OWNER_SECRET','CREDENTIALS'),10),deadline:nil(txt(64)),criteria:arr(obj({id,description:txt(2048),provenance:provenanceSchema}),100),maximumCashMicroUsd:int(),allowedTools:ids,revision:txt(128)});
const artifact=obj({id,digest});
const verdict=obj({criterionId:id,status:en('PASS','FAIL','INCOMPLETE_EVIDENCE')});
export const agentSchemas:Record<string,{input:Schema;output:Schema}>={
 'agent-capability-advertisement':{input:obj({requestedCapabilityIds:ids}),output:obj({agentId:en('SARA'),capabilities:arr(manifestCapability,100),unavailableCapabilityIds:ids,manifestDigest:digest,publishAuthorized:bool,...flags})},
 'agent-capability-discovery':{input:obj({agentId:id,sourceId:txt(256),capabilities:arr(manifestCapability,100),claimedAuthority:strings}),output:obj({agentId:id,sourceId:txt(256),claims:arr(obj({id,version:txt(64),contractDigest:digest,description:txt(2048),authorityClass:txt(64),trust:en('UNVERIFIED_ASSERTION')}),100),verificationRequired:strings,authorityClaimsAccepted:bool,contactAuthorized:bool,...flags})},
 'agent-task-contract-compiler':{input:contractInput,output:obj({status:en('COMPILED_DRAFT','BLOCKED'),contract:contractInput,contractDigest:digest,violations:strings,effectiveDelegatedAuthority:en('READ_ONLY','DRAFT_ONLY','NONE'),transmitAuthorized:bool,...flags})},
 'agent-result-verifier':{input:obj({contractReceiptId:digest,agentId:id,taskClass:id,revision:txt(128),artifacts:arr(artifact,100),criterionProofs:arr(obj({criterionId:id,proofIds:proofs}),100),reportedCashMicroUsd:int(),costProofIds:proofs}),output:obj({status:en('VERIFIED','FAILED','INCOMPLETE_EVIDENCE'),agentId:id,taskClass:id,contractDigest:nil(digest),revision:txt(128),artifactSetDigest:digest,criteria:arr(verdict,100),actualCashMicroUsd:nil(int()),reportedCashMicroUsd:int(),independentlyVerified:bool,...flags})},
 'agent-reputation-ledger':{input:obj({agentId:id,taskClass:id,resultReceiptIds:arr(digest,100)}),output:obj({agentId:id,taskClass:id,verifiedSuccesses:int(),verifiedFailures:int(),unverifiedReceiptIds:arr(digest,100),contractDigests:arr(digest,100),knownActualCashMicroUsd:int(),unknownCostResults:int(),ledgerDigest:digest,persistence:en('KERNEL_INVOCATION_RECEIPT'),universalTrustScore:nil(int()),...flags})},
 'agent-work-decomposer':{input:obj({goal:txt(2048),tasks:arr(obj({id,requiredCapabilityId:id,readResources:strings,writeResources:strings,dependsOn:ids}),100),agents:arr(obj({id,claimedCapabilityIds:ids}),100)}),output:obj({goal:txt(2048),assignments:arr(obj({taskId:id,proposedAgentId:nil(id),requiredCapabilityId:id,readResources:strings,writeResources:strings,verificationRequired:bool}),100),executionOrder:ids,conflicts:arr(obj({resource:txt(2048),taskIds:ids}),100),status:en('DRAFT','BLOCKED'),delegationAuthorized:bool,...flags})},
 'agent-consensus-evaluator':{input:obj({question:txt(2048),answers:arr(obj({id,agentId:id,conclusion:txt(2048),modelFamily:txt(128),evidenceIds:proofs,proofProvenance:provenanceSchema,reasoningDigest:digest}),100)}),output:obj({question:txt(2048),status:en('SUPPORTED','CONTESTED','INSUFFICIENT_EVIDENCE'),conclusions:arr(obj({conclusion:txt(2048),answerIds:ids,independentEvidenceGroups:int(),verifiedAnswerIds:ids,rawVotes:int()}),100),supportedConclusion:nil(txt(2048)),correlationWarnings:strings,majorityAcceptedAsProof:bool,...flags})},
};
