import type { CapabilityDefinition } from '../types.ts';import { agentSchemas } from './contracts.ts';import { agentCases } from './qualification.ts';import { advertise,discover,compileContract,verifyResult,reputation,decompose,consensus } from './operations.ts';
const impl:Record<string,{execute:CapabilityDefinition['execute'];description:string;state?:boolean;draft?:boolean}>={
'agent-capability-advertisement':{execute:advertise,description:'Generate a private manifest only from current kernel-qualified enabled contracts; publication requires separate exact authority.',draft:true},
'agent-capability-discovery':{execute:discover,description:'Parse external capability manifests as unverified assertions and identify exact independent qualification requirements.'},
'agent-task-contract-compiler':{execute:compileContract,description:'Compile bounded draft inter-agent contracts with explicit outputs, authority, data exclusions, cost ceiling and acceptance proof.',draft:true},
'agent-result-verifier':{execute:verifyResult,description:'Independently verify returned artifacts against the exact prior task contract, counterparty, revision, criterion and cost evidence.'},
'agent-reputation-ledger':{execute:reputation,description:'Persist task-specific counterpart performance from independently verified result receipts, without universal trust scores.',state:true},
'agent-work-decomposer':{execute:decompose,description:'Draft dependency-ordered candidate assignments, balance work and reject overlapping write ownership before delegation.',draft:true},
'agent-consensus-evaluator':{execute:consensus,description:'Compare proof-supported conclusions while tracking shared model, reasoning and source correlation; vote count cannot establish truth.'},
};
export const agentDefinitions:readonly CapabilityDefinition[]=Object.entries(impl).map(([id,x])=>({id,version:'1.0.0',description:x.description,inputSchema:agentSchemas[id]!.input,outputSchema:agentSchemas[id]!.output,effect:x.state?'INTERNAL_STATE':x.draft?'DRAFT_ONLY':'PURE',authorityClass:x.draft?'DRAFT_ONLY':'READ_ONLY',resources:['supplied-input','actor-visible-kernel-evidence-receipts'],sourceFiles:['agents/contracts.ts','agents/operations.ts','agents/qualification.ts','agents/definitions.ts','engineering/common.ts'],qualificationRequirements:['frozen-contract','malformed-input','untrusted-agent-claims','exact-contract-evidence','no-external-communication','no-authority-delegation','determinism','kernel-replay-and-recovery'],execute:x.execute,cases:agentCases[id]!}));
