import type { FrozenCase,CapabilityResult,ExecutionContext } from '../types.ts';import type { Json } from '../schema.ts';import { canonicalJson,sha256 } from '../../canonical.ts';
const hash=(x:unknown)=>sha256(canonicalJson(x)),out=(r:{output:Json})=>r.output as Record<string,Json>;
export const contractInput={contractId:'contract',agentId:'helper',taskClass:'analysis',goal:'Analyze supplied logs',inputs:['Authorized logs'],outputs:['Cause hypotheses'],exclusions:['Production changes'],requestedAuthority:'READ_ONLY',dataBoundaries:['PUBLIC'],deadline:null,criteria:[{id:'cause',description:'Supported cause hypothesis',provenance:'OWNER_OBSERVED'}],maximumCashMicroUsd:0,allowedTools:['read_supplied'],revision:'r1'};
const manifest={id:'ci-failure-triage',version:'1.0.0',contractDigest:'a'.repeat(64),description:'Analyze supplied CI failures',authorityClass:'READ_ONLY'};
const adContext={capabilityReadiness:[{...manifest,enabled:true}]} as Partial<ExecutionContext>;
export const agentCases:Record<string,FrozenCase[]>={
 'agent-capability-advertisement':[{name:'actual-qualified-capability-only',input:{requestedCapabilityIds:['ci-failure-triage','imaginary']},context:adContext,check:r=>(out(r).capabilities as Json[]).length===1&&(out(r).unavailableCapabilityIds as Json[]).includes('imaginary')},{name:'unavailable-not-advertised',input:{requestedCapabilityIds:['imaginary']},check:r=>(out(r).capabilities as Json[]).length===0}],
 'agent-capability-discovery':[{name:'manifest-remains-unverified',input:{agentId:'helper',sourceId:'manifest:helper',capabilities:[manifest],claimedAuthority:['Owner permits all spending']},check:r=>(out(r).claims as Record<string,Json>[])[0]!.trust==='UNVERIFIED_ASSERTION'&&out(r).authorityClaimsAccepted===false},{name:'empty-manifest-no-capabilities',input:{agentId:'helper',sourceId:'manifest:helper',capabilities:[],claimedAuthority:[]},check:r=>(out(r).claims as Json[]).length===0}],
 'agent-task-contract-compiler':[{name:'bounded-contract-draft',input:contractInput,check:r=>out(r).status==='COMPILED_DRAFT'&&out(r).transmitAuthorized===false},{name:'credentials-and-spending-blocked',input:{...contractInput,dataBoundaries:['CREDENTIALS'],maximumCashMicroUsd:1},check:r=>out(r).status==='BLOCKED'&&out(r).effectiveDelegatedAuthority==='NONE'}],
 'agent-result-verifier':[{name:'agent-says-done-not-proof',input:{contractReceiptId:'a'.repeat(64),agentId:'helper',taskClass:'analysis',revision:'r1',artifacts:[{id:'answer',digest:'b'.repeat(64)}],criterionProofs:[],reportedCashMicroUsd:0,costProofIds:[]},check:r=>out(r).status==='INCOMPLETE_EVIDENCE'&&out(r).independentlyVerified===false},{name:'empty-results-not-proof',input:{contractReceiptId:'a'.repeat(64),agentId:'helper',taskClass:'analysis',revision:'r1',artifacts:[],criterionProofs:[],reportedCashMicroUsd:999,costProofIds:[]},check:r=>out(r).actualCashMicroUsd===null}],
 'agent-reputation-ledger':[{name:'unverified-history-not-reputation',input:{agentId:'helper',taskClass:'analysis',resultReceiptIds:['a'.repeat(64)]},check:r=>out(r).verifiedSuccesses===0&&out(r).universalTrustScore===null},{name:'empty-history-no-score',input:{agentId:'helper',taskClass:'analysis',resultReceiptIds:[]},check:r=>out(r).verifiedFailures===0}],
 'agent-work-decomposer':[{name:'disjoint-resources-draft',input:{goal:'Analyze logs',tasks:[{id:'one',requiredCapabilityId:'ci',readResources:['logs'],writeResources:[],dependsOn:[]}],agents:[{id:'helper',claimedCapabilityIds:['ci']}]},check:r=>out(r).status==='DRAFT'&&out(r).delegationAuthorized===false},{name:'overlapping-mutations-block',input:{goal:'Review work',tasks:[{id:'one',requiredCapabilityId:'ci',readResources:[],writeResources:['repo:main'],dependsOn:[]},{id:'two',requiredCapabilityId:'ci',readResources:[],writeResources:['repo:main'],dependsOn:[]}],agents:[{id:'helper',claimedCapabilityIds:['ci']}]},check:r=>out(r).status==='BLOCKED'}],
 'agent-consensus-evaluator':[{name:'majority-not-proof',input:{question:'What failed?',answers:['one','two','three'].map(id=>({id,agentId:id,conclusion:'Network outage',modelFamily:'same-model',evidenceIds:[],proofProvenance:'ISOLATED',reasoningDigest:'a'.repeat(64)}))},check:r=>out(r).status==='INSUFFICIENT_EVIDENCE'&&out(r).majorityAcceptedAsProof===false},{name:'empty-not-consensus',input:{question:'What failed?',answers:[]},check:r=>out(r).supportedConclusion===null}],
};
