import {verifyGenomeLabProgramCandidate} from '../../genome-lab-verifier.ts';
import {arraySchema as a,objectSchema as o,textSchema as t,enumSchema as e,digestSchema,type Json} from '../schema.ts';
import {shaSchema,bool} from './common.ts';
import type {CapabilityDefinition,ExecutionContext,ExecutionOutput} from '../types.ts';

const filesSchema=a(o({path:t(256),content:t(8192)}),8,1);
const fixtureInput={revision:'a'.repeat(40),files:[{path:'src/index.ts',content:'export const value=1;'}]};
async function reproduce(input:Record<string,Json>,ctx:ExecutionContext):Promise<ExecutionOutput>{
 const base={analysisComplete:true,executionPerformed:false,provenance:'LOCAL',sourceProvenance:'SUPPLIED',revision:input.revision!,artifactDigest:null,rootCauseEstablished:false,repairVerified:false,completedChecks:[],failureCodes:[],evidenceDigests:[]};
 if(!ctx.isolatedReproductionAuthorized||ctx.emergencyStopped)return {status:'BLOCKED',output:{...base,result:'BLOCKED',summary:ctx.emergencyStopped?'EMERGENCY_STOP':'EXACT_OWNER_REPRODUCTION_REQUEST_REQUIRED'}};
 const verification=await verifyGenomeLabProgramCandidate({candidate:{schemaVersion:1,candidateKind:'typescript_program',programName:'Owner defect reproduction',summary:'Bounded supplied fixture; not customer fulfillment or a repair',files:input.files as {path:string;content:string}[],limitations:['Only supplied fixture behavior is tested.']},objective:'Observe bounded supplied test behavior',acceptanceCriteria:['Report actual supplied fixture outcome without a root cause or repair claim'],constitutionDigest:ctx.constitutionDigest,maximumBudgetUsd:0});
 const executed=verification.completedChecks.includes('behavior_tests');
 const result=verification.passed?'FIXTURE_PASSED':executed?'FIXTURE_EXECUTION_FAILED':verification.failures.some(f=>f.kind==='policy'||f.kind==='security')?'SOURCE_REJECTED':verification.failures.some(f=>f.kind==='type'||f.kind==='syntax')?'COMPILATION_FAILED':'INFRASTRUCTURE_FAILURE';
 const summary=result==='FIXTURE_PASSED'?'The supplied isolated fixture passed. This does not establish whole-site health, a root cause or a verified repair.':result==='FIXTURE_EXECUTION_FAILED'?'The supplied isolated fixture execution failed. Assertion failure, resource limit or runtime failure must be distinguished before claiming the reported defect was reproduced.':`${result}: behavioral execution was not completed. Review the bounded diagnostic codes; no automatic retry or repair was attempted.`;
 return {output:{...base,result,executionPerformed:executed,provenance:executed?'ISOLATED':'LOCAL',artifactDigest:verification.artifactDigest,completedChecks:verification.completedChecks,failureCodes:verification.failures.map(f=>f.code),evidenceDigests:verification.evidenceDigests,summary},observed:[{basis:executed?'ISOLATED_FIXTURE_EXECUTION':'LOCAL_FIXTURE_VALIDATION',artifactDigest:verification.artifactDigest,result}],unknowns:['Supplied source revision is not independently reconciled with a repository.','No production behavior, root cause, repair, customer acceptance or revenue is established.','Recorded workflow cash excludes unallocated existing infrastructure cost.']};
}
export const reproductionDefinition:CapabilityDefinition={id:'isolated-defect-reproducer',version:'1.0.0',description:'Execute an exact owner-requested bounded TypeScript reproduction through the existing Genome Lab source guard, compiler and restricted runtime.',inputSchema:o({revision:shaSchema,files:filesSchema}),outputSchema:o({analysisComplete:bool,executionPerformed:bool,provenance:e('LOCAL','ISOLATED'),sourceProvenance:e('SUPPLIED'),revision:shaSchema,artifactDigest:{...digestSchema,nullable:true},rootCauseEstablished:bool,repairVerified:bool,completedChecks:a(t(128),16),failureCodes:a(t(256),256),evidenceDigests:a(digestSchema,256),result:e('BLOCKED','FIXTURE_PASSED','FIXTURE_EXECUTION_FAILED','SOURCE_REJECTED','COMPILATION_FAILED','INFRASTRUCTURE_FAILURE'),summary:t(1024)}),effect:'INTERNAL_STATE',authorityClass:'REVERSIBLE_AUTHORIZED',resources:['supplied-typescript-fixture','existing-permission-restricted-genome-lab-runtime'],sourceFiles:['engineering/reproduction.ts','../owner-defect-work.ts','../genome-lab.ts','../genome-lab-verifier.ts','../experimental-compiler-cache.ts'],qualificationRequirements:['exact-authenticated-owner-request','existing-sandbox-policy','source-guard','bounded-runtime','no-network-or-paid-dispatch','receipt-replay-recovery','isolated-behavior-tests-in-CI'],execute:reproduce,cases:[{name:'no-owner-request-no-execution',input:fixtureInput,check:r=>r.status==='BLOCKED'&&(r.output as Record<string,Json>).executionPerformed===false},{name:'stop-before-execution',input:fixtureInput,context:{isolatedReproductionAuthorized:true,emergencyStopped:true},check:r=>r.status==='BLOCKED'},{name:'unchanged-structure-guard',input:fixtureInput,context:{isolatedReproductionAuthorized:true},check:r=>(r.output as Record<string,Json>).result==='SOURCE_REJECTED'}]};
