import {canonicalJson,sha256} from '../canonical.ts';
import {objectSchema as o,textSchema as t,arraySchema as a,enumSchema as e,type Json} from './schema.ts';
import type {CapabilityDefinition,ExecutionContext,ExecutionOutput} from './types.ts';
import {SoftwareSourceReadError,type SoftwareSourceEvidence} from '../software-source-reader.ts';

export type SoftwareRuntime={configurationIdentity?:Readonly<{sourceDigest:string;journeyDigest:string}>;inspectSource:(repository:string,journey:string)=>Promise<SoftwareSourceEvidence>;testJourney:()=>Promise<unknown>};
const inputSchema=o({website:t(512,0),repository:t(256),journey:t(512,0),scope:e('INSPECTION','JOURNEY_TEST')});
const outputSchema=o({analysisComplete:{type:'boolean'},actor:e('SARA_RUNTIME'),result:t(128),evidence:{type:'json'},summary:t(4096),qualified:{type:'boolean'},remaining:a(t(2048),64)});
const input={website:'https://nicos-world.com/',repository:'BoneManTGRM/Nicos-Adventures',journey:'movement-to-scanner',scope:'JOURNEY_TEST'};
const output=(result:string,summary:string,evidence:Json=null,remaining:string[]=[],qualified=false):ExecutionOutput=>({output:{analysisComplete:true,actor:'SARA_RUNTIME',result,evidence,summary,qualified,remaining},unknowns:['Recorded workflow cash excludes unallocated existing infrastructure. No customer fulfillment, payment, profit, repair or live application change is established.']});
function permitted(ctx:ExecutionContext){return ctx.softwareWorkAuthorized===true&&!ctx.emergencyStopped;}
function identity(i:Record<string,Json>){return i.website==='https://nicos-world.com/'&&i.repository==='BoneManTGRM/Nicos-Adventures'&&i.journey==='movement-to-scanner';}
async function inspect(i:Record<string,Json>,ctx:ExecutionContext):Promise<ExecutionOutput>{
 if(!permitted(ctx))return {...output('BLOCKED','Exact authenticated owner software request required.'),status:'BLOCKED'};
 if(!ctx.softwareRuntime)return output('INTEGRATION_UNAVAILABLE','SARA’s public source adapter is not connected.',null,['Runtime public source integration is unavailable.']);
 try{const evidence=await ctx.softwareRuntime.inspectSource(String(i.repository),String(i.journey)||'source configuration tests');
  return {...output('SOURCE_COLLECTED',`SARA inspected ${evidence.files.length} immutable source files at ${evidence.immutableCommitSha}. Existing tests were read, not executed.`,evidence as unknown as Json,evidence.limitations),observed:[{basis:'SARA_RUNTIME_PUBLIC_SOURCE',repository:evidence.repository,revision:evidence.immutableCommitSha,tree:evidence.treeSha}]};
 }catch(error){const code=error instanceof SoftwareSourceReadError?error.code:'PROVIDER_FAILURE',boundary=error instanceof SoftwareSourceReadError?error.providerBoundary:null;const detail=boundary?`${code}; HTTP ${boundary.httpStatus}`:code;return {...output('SOURCE_UNAVAILABLE',`Repository collection did not complete (${detail}). No application defect is established.`,boundary?{providerBoundary:boundary}:null,[`Public source collection: ${detail}.`]),observed:[{basis:'SARA_RUNTIME_PUBLIC_SOURCE_ATTEMPT',repository:i.repository!,failureCode:code,...(boundary?{providerBoundary:boundary}:{})}]};}
}
async function journey(i:Record<string,Json>,ctx:ExecutionContext):Promise<ExecutionOutput>{
 if(!permitted(ctx))return {...output('BLOCKED','Exact authenticated owner software request required.'),status:'BLOCKED'};
 if(!identity(i)||i.scope!=='JOURNEY_TEST')return output('UNSUPPORTED_JOURNEY','No reviewed execution profile matches this exact target and journey.',null,['Target/journey profile is unsupported.']);
 if(!ctx.softwareRuntime)return output('INTEGRATION_UNAVAILABLE','SARA’s isolated application browser is not connected.',null,['Runtime browser integration is unavailable.']);
 try{const evidence=await ctx.softwareRuntime.testJourney() as Record<string,Json>;
  return {...output(String(evidence.status),evidence.status==='PASSED'?'The movement-to-scanner journey passed in SARA’s isolated browser using fetched site assets.':'The isolated browser journey did not complete; inspect expected versus observed steps and the environment boundary.',evidence,Array.isArray(evidence.limitations)?evidence.limitations as string[]:[]),observed:[{basis:'SARA_RUNTIME_ISOLATED_JOURNEY',website:i.website!,status:evidence.status??'UNKNOWN'}]};
 }catch{return {...output('ENVIRONMENT_UNAVAILABLE','The bounded browser environment failed before a qualified journey result.',null,['Supported sandboxed application browser is unavailable; no application defect is established.']),observed:[{basis:'SARA_RUNTIME_ISOLATED_JOURNEY_ATTEMPT',website:i.website!,status:'ENVIRONMENT_UNAVAILABLE'}]};}
}
function review(i:Record<string,Json>,ctx:ExecutionContext):ExecutionOutput{
 const prior=ctx.priorCapabilityResults??[];
 const exact=(id:string)=>prior.find(r=>r.capability.id===id&&r.status==='SUCCEEDED'&&r.receiptValidity?.current===true&&r.inputDigest===sha256(canonicalJson(i)));
 const source=exact('software-source-inspector'),test=exact('software-journey-tester');
 const sourceOutput=source?.output as Record<string,Json>|undefined,testOutput=test?.output as Record<string,Json>|undefined;
 const sourceEvidence=sourceOutput?.evidence as Record<string,Json>|null|undefined,testEvidence=testOutput?.evidence as Record<string,Json>|null|undefined;
 const sourceFiles=sourceEvidence?.files as Record<string,Json>[]|undefined;
 const sourceFilesValid=Array.isArray(sourceFiles)&&sourceFiles.length>0&&sourceFiles.length<=16&&sourceFiles.every(f=>typeof f.path==='string'&&f.trust==='UNTRUSTED_SOURCE'&&/^[a-f0-9]{40}$/u.test(String(f.gitBlobSha))&&/^[a-f0-9]{64}$/u.test(String(f.contentSha256))&&typeof f.byteLength==='number'&&f.byteLength>=0&&f.permalink===`https://github.com/${i.repository}/blob/${sourceEvidence?.immutableCommitSha}/${String(f.path).split('/').map(encodeURIComponent).join('/')}`)&&(i.scope==='INSPECTION'||['manifest','lockfile','runtime_configuration','journey_test','journey_source'].every(role=>sourceFiles.some(f=>f.role===role)));
 const sourceValid=sourceFilesValid&&sourceOutput?.result==='SOURCE_COLLECTED'&&sourceEvidence?.actor==='SARA_RUNTIME'&&sourceEvidence.repository===`https://github.com/${i.repository}`&&/^[a-f0-9]{40}$/u.test(String(sourceEvidence.immutableCommitSha));
 const steps=testEvidence?.steps as Record<string,Json>[]|undefined;
 const expected=[['Observe World Map','World Map'],['Continue adventure','Robot Home'],['Continue adventure','Robo Lab'],['Continue to the test chamber','Movement test'],['Forward','1'],['Right','2'],['Forward','3'],['Pass movement test','Scanner test']];
 const assets=testEvidence?.assets as Record<string,Json>[]|undefined;
 const assetsValid=testEvidence?.assetProvenance==='EXTERNAL_READ_ONLY'&&Array.isArray(assets)&&assets.length>0&&assets.length<=180&&new Set(assets.map(asset=>asset.url)).size===assets.length&&assets.every(asset=>typeof asset.url==='string'&&/^https:\/\/nicos-world\.com\/(?!\/)/u.test(asset.url)&&!/[?#]/u.test(asset.url)&&/^[a-f0-9]{64}$/u.test(String(asset.sha256))&&typeof asset.bytes==='number'&&asset.bytes>0&&asset.bytes<=8*1024*1024&&typeof asset.contentType==='string')&&assets.some(asset=>asset.url==='https://nicos-world.com/'&&String(asset.contentType).includes('text/html'))&&assets.some(asset=>String(asset.contentType).includes('javascript'))&&testEvidence?.assetSetDigest===sha256(canonicalJson(assets));
 const environment=testEvidence?.environment as Record<string,Json>|undefined;
 const environmentValid=environment?.sandboxArgumentsVerified===true&&environment.sandboxDisabled===false&&environment.liveStateOrCredentialsImported===false&&/^[a-f0-9]{64}$/u.test(String(environment.commandLineDigest))&&/^[a-f0-9]{64}$/u.test(String(environment.executableSha256))&&/^(?:HeadlessChrome|Chrome|Chromium)\/\d{1,3}(?:\.\d{1,5}){3}$/u.test(String(environment.browserProduct))&&/^@[a-f0-9]{40}$/u.test(String(environment.browserRevision));
 const testValid=environmentValid&&assetsValid&&testOutput?.result==='PASSED'&&testEvidence?.actor==='SARA_RUNTIME'&&testEvidence.provenance==='ISOLATED'&&testEvidence.target===i.website&&testEvidence.profile==='nicos-movement-to-scanner-v1'&&testEvidence.runtimeExceptionCount===0&&testEvidence.resourceFailureCount===0&&testEvidence.failureCode===null&&Array.isArray(steps)&&steps.length===expected.length&&steps.every((s,index)=>s.passed===true&&s.action===expected[index]![0]&&s.expected===expected[index]![1]&&s.observed===s.expected)&&typeof testEvidence.screenshotDigest==='string'&&/^[a-f0-9]{64}$/u.test(testEvidence.screenshotDigest);
 const remaining:string[]=[];
 if(!sourceValid)remaining.push('Exact current source receipt is missing or mismatched.',...((sourceOutput?.remaining as string[]|undefined)??[]));
 if(i.scope==='JOURNEY_TEST'&&!testValid)remaining.push('Exact independently checked journey evidence is incomplete or mismatched.',...((testOutput?.remaining as string[]|undefined)??[]));
 const qualified=Boolean(sourceValid&&(i.scope==='INSPECTION'||testValid));
 const summary=qualified?(i.scope==='JOURNEY_TEST'?'No defect was reproduced in the tested isolated movement-to-scanner scope.':'Bounded source inspection completed; existing test files were inspected, not executed.'):'Software work is incomplete. '+remaining.join(' ');
 return output(qualified?'SCOPED_RESULT_VERIFIED':'INCOMPLETE_EVIDENCE',summary,{sourceReceipt:source?.resultDigest??null,journeyReceipt:test?.resultDigest??null,sourceRevision:sourceEvidence?.immutableCommitSha??null,servingRevision:testEvidence?.servingRevision??null,sourceMatchesServing:false,scope:i.scope!,actor:'SARA_RUNTIME',untested:['Live authenticated site behavior','Mobile and restart persistence','Whole-site health','Source application build and existing test-suite execution','Repair preparation and integration'],infrastructureAllocation:'UNKNOWN'},remaining,qualified);
}
const common={version:'1.0.0',inputSchema,outputSchema,resources:['anonymous-public-GitHub-GET','credential-free-isolated-browser','existing-durable-receipts'],sourceFiles:['software-work.ts','software-runtime-identity.ts','software-runtime-identity.ts','../software-source-reader.ts','../software-journey-browser.ts','../owner-software-work.ts','../../railpack.json','../../scripts/prepare-software-browser.mjs'],qualificationRequirements:['exact-owner-admission','wrong-target-denial','bounded-network-and-browser','same-input-receipts','independent-observation-validation','production-owner-acceptance']};
export const softwareWorkDefinitions:CapabilityDefinition[]=[
 {...common,id:'software-source-inspector',description:'Gather bounded immutable public repository source, manifests, lockfile identities and applicable tests through SARA’s own runtime.',effect:'READ_ONLY',authorityClass:'READ_ONLY',execute:inspect,cases:[{name:'no-owner-no-fetch',input,check:r=>r.status==='BLOCKED'},{name:'stop-no-fetch',input,context:{softwareWorkAuthorized:true,emergencyStopped:true},check:r=>r.status==='BLOCKED'},{name:'missing-adapter-honest',input,context:{softwareWorkAuthorized:true},check:r=>(r.output as Record<string,Json>).result==='INTEGRATION_UNAVAILABLE'}]},
 {...common,id:'software-journey-tester',description:'Run a reviewed isolated application journey using a fresh sandboxed browser and bounded public static assets, without live state changes.',effect:'INTERNAL_STATE',authorityClass:'REVERSIBLE_AUTHORIZED',execute:journey,cases:[{name:'no-owner-no-browser',input,check:r=>r.status==='BLOCKED'},{name:'stop-no-browser',input,context:{softwareWorkAuthorized:true,emergencyStopped:true},check:r=>r.status==='BLOCKED'},{name:'wrong-target',input:{...input,website:'https://example.com/'},context:{softwareWorkAuthorized:true},check:r=>(r.output as Record<string,Json>).result==='UNSUPPORTED_JOURNEY'}]},
 {...common,id:'software-evidence-reviewer',description:'Independently validate exact software collection and journey receipts against target, observed assertions and tested scope; retain unknowns.',effect:'PURE',authorityClass:'READ_ONLY',execute:review,cases:[{name:'no-evidence-no-pass',input,check:r=>(r.output as Record<string,Json>).qualified===false}]}
];
