import { objectSchema as obj,arraySchema as list,textSchema as text,idSchema as id,digestSchema as dg,integerSchema as integer,enumSchema as choice,type Schema } from '../schema.ts';
const nullable=(s:Schema):Schema=>({...s,nullable:true});const bool:Schema={type:'boolean'};const fraction:Schema={type:'number',minimum:0,maximum:1};const ids=list(id,256),digests=list(dg,256),texts=list(text(2048),256);
const knowledgeStatus=choice('DRAFT','CANDIDATE','QUALIFIED','VERIFIED','SUPERSEDED','INVALIDATED');
export const identitySchema=list(obj({key:id,value:{type:'json'}}),64);
const measuredNumber:Schema={type:'number',minimum:0,maximum:256_000_000_000_000};
const signedNumber:Schema={type:'number',minimum:-256_000_000_000_000,maximum:256_000_000_000_000};
const metricSchema=obj({taskReferenceDigest:dg,group:choice('BASELINE','REUSE'),comparisonId:id,basisDigest:dg,evidenceId:id,elapsedMs:nullable(integer(0,1_000_000_000_000)),cashMicroUsd:nullable(integer(0,1_000_000_000_000)),retries:nullable(integer(0,1_000_000)),humanInterventions:nullable(integer(0,1_000_000)),regressions:nullable(integer(0,1_000_000)),regressionOpportunities:nullable(integer(0,1_000_000))});
const candidateSummary=obj({id,version:integer(1),status:knowledgeStatus,sourcePlaybookId:id,outcomeDigests:digests,procedure:texts,acceptanceCriteria:texts,qualificationRequired:bool});
export const schemas:Record<string,{input:Schema;output:Schema}>={
 'experience-to-procedure-compiler':{input:obj({playbookId:id,playbookVersion:integer(1),outcomeDigests:digests,expectedKnowledgeDigest:nullable(dg)}),output:obj({status:choice('CANDIDATE_READY','EVIDENCE_REQUIRED','BLOCKED'),candidate:nullable(candidateSummary),persisted:bool,sourceKnowledgeDigest:nullable(dg),reasons:texts,executionAuthorized:bool})},
 'procedure-effectiveness-scorer':{input:obj({playbookId:id,playbookVersion:integer(1),measurements:list(metricSchema,256)},['playbookId','playbookVersion']),output:obj({status:choice('MEASURED','INSUFFICIENT_EVIDENCE'),samples:integer(),successes:integer(),failures:integer(),successRate:nullable(fraction),operationsAvoided:integer(),latestOutcome:nullable(choice('VERIFIED','FAILED')),completionTimeMs:nullable(measuredNumber),cashCostMicroUsd:nullable(measuredNumber),retryCount:nullable(measuredNumber),humanInterventions:nullable(measuredNumber),regressionRate:nullable(fraction),measurementCoverage:obj({time:integer(),cash:integer(),retries:integer(),humanInterventions:integer(),regressions:integer()}),comparisons:obj({pairedSamples:integer(),meanTimeSavedMs:nullable(signedNumber),cashSavedMicroUsd:nullable(signedNumber),meanRetryReduction:nullable(signedNumber),meanHumanInterventionReduction:nullable(signedNumber),meanRegressionRateReduction:nullable(signedNumber)}),rejectedMeasurementDigests:digests,measurementEvidenceDigests:digests,outcomeDigests:digests,historyReferencesTruncated:bool,sourceKnowledgeDigest:nullable(dg)})},
 'memory-conflict-resolver':{input:obj({taskFamily:id,operation:choice('ANALYZE','SUPERSEDE'),oldId:nullable(id),oldVersion:nullable(integer(1)),replacementId:nullable(id),replacementVersion:nullable(integer(1)),oldDigest:nullable(dg),replacementDigest:nullable(dg),expectedKnowledgeDigest:nullable(dg)}),output:obj({status:choice('NO_CONFLICT_OBSERVED','CONFLICTS_REQUIRE_REVIEW','SUPERSEDED','EVIDENCE_REQUIRED','BLOCKED'),conflicts:list(obj({claimKey:id,lessonIds:list(id,8),inferenceDigests:list(dg,8)}),32),conflictsTruncated:bool,totalConflictGroups:integer(),supersessions:list(obj({oldId:id,oldVersion:integer(1),replacementKey:text(256)}),256),historyPreserved:bool,persisted:bool,sourceKnowledgeDigest:nullable(dg),reasons:texts})},
 'knowledge-expiration-manager':{input:obj({asOf:text(64),rules:list(obj({id,version:integer(1),kind:choice('PLAYBOOK','LESSON'),nature:choice('IMMUTABLE_HISTORICAL_FACT','TIME_SENSITIVE'),maximumAgeSeconds:nullable(integer(1,315360000))}),256)}),output:obj({status:choice('ASSESSED','INSUFFICIENT_EVIDENCE'),knowledge:list(obj({id,version:integer(1),state:choice('VALID','REVERIFY','UNKNOWN'),reason:text(256),ageSeconds:nullable(integer())}),256),sourceKnowledgeDigest:nullable(dg),historyChanged:bool})},
 'failure-pattern-memory':{input:obj({taskFamily:id,signature:text(1024),maximumResults:integer(1,50)}),output:obj({matches:list(obj({id,version:integer(1),similarity:fraction,revalidationRequired:bool,applicableNow:bool,evidenceDigests:list(dg,16),lessonDigest:dg,evidenceReferencesTruncated:bool,mismatchReasons:texts}),50),sourceKnowledgeDigest:nullable(dg),identityEstablished:bool})},
 'solution-reuse-ranker':{input:obj({taskFamily:id,maximumResults:integer(1,128)}),output:obj({status:choice('CANDIDATE_SELECTED','NO_APPLICABLE_PROCEDURE','INSUFFICIENT_EVIDENCE'),selectedId:nullable(id),ranking:list(obj({id,version:integer(1),eligible:bool,specificity:integer(),successes:integer(),failures:integer(),mismatchReasons:texts,evidenceReusable:bool}),128),sourceKnowledgeDigest:nullable(dg),executionAuthorized:bool})},
 'counterexample-seeker':{input:obj({taskFamily:id,claimKey:id,proposedInference:text(2048),evidenceIds:ids,maximumItems:integer(1,100)}),output:obj({status:choice('COUNTEREXAMPLES_FOUND','NONE_IN_BOUNDED_EVIDENCE','INSUFFICIENT_EVIDENCE'),counterexamples:list(obj({sourceId:id,contentDigest:dg,basis:choice('TRUSTED_CONFLICTING_LESSON','TRUSTED_NEGATIVE_CLAIM')}),100),examined:integer(0,100),remaining:integer(),conclusionProven:bool,sourceKnowledgeDigest:nullable(dg)})},
 'confidence-calibrator':{input:obj({taskFamily:id,forecasts:list(obj({taskReferenceDigest:dg,probability:fraction,evidenceId:id}),256)}),output:obj({status:choice('EMPIRICAL_CALIBRATION','INSUFFICIENT_EVIDENCE'),samples:integer(),successes:integer(),empiricalSuccessRate:nullable(fraction),smoothedProbability:nullable(fraction),brierScore:nullable(fraction),rejectedForecastDigests:digests,evidenceDigests:list(dg,512),sourceKnowledgeDigest:nullable(dg),generalizationProven:bool})},
};
