import type { CapabilityDefinition,ExecutionOutput,FrozenCase } from '../types.ts';
import type { Json } from '../schema.ts';
import { schemas } from './contracts.ts';
import { calibrate,compileCandidate,conflicts,counterexamples,effectiveness,expiration,failureMemory,rankReuse } from './implementations.ts';
const out=(r:ExecutionOutput)=>r.output as Record<string,Json>;
export const conflictInput={taskFamily:'ci_failure_diagnosis',operation:'ANALYZE',oldId:null,oldVersion:null,replacementId:null,replacementVersion:null,oldDigest:null,replacementDigest:null,expectedKnowledgeDigest:null};
const entries:Record<string,{description:string;execute:CapabilityDefinition['execute'];stateful?:boolean;cases:FrozenCase[]}>= {
 'experience-to-procedure-compiler':{description:'Compile exact freshly verified stored job histories or a current independently verified synthetic repair receipt into an unqualified candidate in the existing procedural store; no fabricated outcomes, execution authority or automatic promotion.',execute:compileCandidate,stateful:true,cases:[{name:'no-trusted-history-no-candidate',input:{playbookId:'ci-failure-diagnosis',playbookVersion:1,outcomeDigests:[],expectedKnowledgeDigest:null},check:r=>out(r).status==='EVIDENCE_REQUIRED'&&out(r).candidate===null},{name:'supplied-repair-reference-is-not-trusted-evidence',input:{sourceKind:'ISOLATED_REPAIR_RECEIPT',sourceRequestId:'synthetic-missing-repair',expectedKnowledgeDigest:null},check:r=>out(r).status==='EVIDENCE_REQUIRED'&&out(r).persisted===false&&out(r).executionAuthorized===false}]},
 'procedure-effectiveness-scorer':{description:'Measure stored success/failure and operations avoided, plus trusted measured cost/time/retry/intervention/regression metrics and exact-basis paired savings; unavailable telemetry stays unknown.',execute:effectiveness,cases:[{name:'no-history-no-invented-metrics',input:{playbookId:'ci-failure-diagnosis',playbookVersion:1},check:r=>out(r).successRate===null&&out(r).cashCostMicroUsd===null},{name:'unsupported-measurement-does-not-become-profit',input:{playbookId:'ci-failure-diagnosis',playbookVersion:1,measurements:[{taskReferenceDigest:'a'.repeat(64),group:'REUSE',comparisonId:'comparison',basisDigest:'b'.repeat(64),evidenceId:'invented',elapsedMs:1,cashMicroUsd:0,retries:0,humanInterventions:0,regressions:0,regressionOpportunities:1}]},check:r=>out(r).cashCostMicroUsd===null&&(out(r).rejectedMeasurementDigests as Json[]).length===1}]},
 'memory-conflict-resolver':{description:'Detect contradictory trusted claims and preserve explicit supersession through the existing store only under exact owner-approved fresh replacement identities.',execute:conflicts,stateful:true,cases:[{name:'missing-knowledge-is-not-conflict-free',input:conflictInput,check:r=>out(r).status==='EVIDENCE_REQUIRED'},{name:'text-cannot-request-automatic-supersession',input:{...conflictInput,operation:'SUPERSEDE'},check:r=>out(r).persisted===false}]},
 'knowledge-expiration-manager':{description:'Assess class-specific freshness while preserving immutable historical facts and retaining identity checks; never erase knowledge by age.',execute:expiration,cases:[{name:'missing-record-unknown',input:{asOf:'2026-09-12T00:00:00Z',rules:[{id:'unknown',version:1,kind:'PLAYBOOK',nature:'TIME_SENSITIVE',maximumAgeSeconds:60}]},check:r=>(out(r).knowledge as Record<string,Json>[])[0]?.state==='UNKNOWN'}]},
 'failure-pattern-memory':{description:'Retrieve task-specific verified negative lessons by bounded signature similarity, retaining applicability mismatches and mandatory revalidation.',execute:failureMemory,cases:[{name:'no-history-no-invented-repair',input:{taskFamily:'ci_failure_diagnosis',signature:'timeout',maximumResults:5},check:r=>(out(r).matches as Json[]).length===0&&out(r).identityEstablished===false}]},
 'solution-reuse-ranker':{description:'Rank existing independently verified procedures with task, identity, supersession and latest-failure exclusions using PR166 selection; ranking never grants execution authority.',execute:rankReuse,cases:[{name:'absent-store-fails-closed',input:{taskFamily:'ci_failure_diagnosis',maximumResults:5},check:r=>out(r).selectedId===null&&out(r).executionAuthorized===false}]},
 'counterexample-seeker':{description:'Search bounded applicable trusted conflicting lessons and negative evidence claims, exposing unsearched evidence and refusing truth-by-absence.',execute:counterexamples,cases:[{name:'no-evidence-does-not-confirm-claim',input:{taskFamily:'ci_failure_diagnosis',claimKey:'cause',proposedInference:'Network failure',evidenceIds:[],maximumItems:5},check:r=>out(r).status==='INSUFFICIENT_EVIDENCE'&&out(r).conclusionProven===false}]},
 'confidence-calibrator':{description:'Score digest-bound pre-outcome forecasts against actual stored task outcomes with Brier error and finite-sample smoothing; never calibrate fluent unsupported confidence.',execute:calibrate,cases:[{name:'fabricated-history-not-calibration',input:{taskFamily:'ci_failure_diagnosis',forecasts:[{taskReferenceDigest:'a'.repeat(64),probability:1,evidenceId:'fake'}]},check:r=>out(r).samples===0&&out(r).smoothedProbability===null},{name:'empty-has-no-probability',input:{taskFamily:'ci_failure_diagnosis',forecasts:[]},check:r=>out(r).status==='INSUFFICIENT_EVIDENCE'}]},
};
export const proceduralDefinitions:readonly CapabilityDefinition[]=Object.entries(entries).map(([id,e])=>({id,version:'1.0.0',description:e.description,inputSchema:schemas[id]!.input,outputSchema:schemas[id]!.output,effect:e.stateful?'INTERNAL_STATE':'READ_ONLY',authorityClass:e.stateful?'REVERSIBLE_AUTHORIZED':'READ_ONLY',...(e.stateful?{ownerOnly:true}:{}),resources:['existing-PR166-procedural-store','actor-visible-kernel-evidence-receipts'],sourceFiles:['procedural/contracts.ts','procedural/definitions.ts','procedural/implementations.ts',...(id==='experience-to-procedure-compiler'?['procedural/repair-candidate.ts','../isolated-software-repair.ts']:[]),'../procedural-intelligence.ts','../memory-fabric.ts','engineering/common.ts','evidence.ts'],qualificationRequirements:['frozen-contract','malformed-input','determinism','no-external-effect','trusted-provenance','restart-and-copy-restore','idempotent-interrupted-receipt-recovery','owner-bound-state-change','historical-evidence-retention'],execute:e.execute,cases:e.cases}));
