import { ProceduralKnowledgeStore,type ProceduralKnowledgeSnapshot,type ProceduralPlaybook,type ReuseOutcomeRecord } from '../../procedural-intelligence.ts';
import { decidePriorEvidenceReuse } from '../../memory-fabric.ts';
import { assessEvidence } from '../evidence.ts';
import { CapabilityInputError,validateSchema,type Json } from '../schema.ts';
import type { ExecutionContext,ExecutionOutput } from '../types.ts';
import { data,rows,strings,digest,unique,requireUnique,type Data } from '../engineering/common.ts';
import { schemas } from './contracts.ts';
import {verifiedRepairCandidate,repairCandidateSource} from './repair-candidate.ts';
export type ProceduralContext=ExecutionContext&{proceduralKnowledge?:ProceduralKnowledgeSnapshot|null};
const knowledge=(ctx:ExecutionContext)=>(ctx as ProceduralContext).proceduralKnowledge??null;
const key=(p:{id:string;version:number})=>`${p.id}@${p.version}`;
const kd=(k:ProceduralKnowledgeSnapshot|null)=>k?digest(k):null;
const current=(p:ProceduralPlaybook,ctx:ExecutionContext)=>decidePriorEvidenceReuse({expectedIdentity:p.procedureApplicabilityIdentity,currentIdentity:ctx.currentIdentity});
const outcomeHistory=(k:ProceduralKnowledgeSnapshot,p:{id:string;version:number})=>k.outcomes.filter(o=>o.playbookId===p.id&&o.playbookVersion===p.version);
function result(output:Data,k:ProceduralKnowledgeSnapshot|null,unknowns:string[]=[]):ExecutionOutput{return {output,observed:k?[{basis:'EXISTING_PROCEDURAL_STORE',snapshotDigest:digest(k)}]:[],unknowns:unique([...(!k?['Trusted procedural knowledge is unavailable.']:[]),...unknowns]),confidence:{level:k?'MEDIUM':'UNASSESSED',basis:k?'Deterministic analysis of persisted qualified knowledge and recorded outcomes; relevance and real-world generalization remain conditional.':'No trusted stored execution evidence.'}};}
export function compileCandidate(input:Data,ctx:ExecutionContext):ExecutionOutput {
 if(input.sourceKind==='ISOLATED_REPAIR_RECEIPT'){
  const k=knowledge(ctx),candidate=verifiedRepairCandidate(input,ctx);
  return result({status:candidate?'CANDIDATE_READY':'EVIDENCE_REQUIRED',candidate:candidate?{id:candidate.id,version:1,status:'CANDIDATE',sourcePlaybookId:null,outcomeDigests:[],procedure:candidate.procedure,acceptanceCriteria:candidate.acceptanceCriteria,qualificationRequired:true}:null,persisted:false,sourceKnowledgeDigest:kd(k),reasons:candidate?['SYNTHETIC candidate only; no procedure promotion, fabricated reuse outcome, customer work or execution authority.']:['A current exact independently verified isolated repair receipt with causal and artifact evidence is required.'],executionAuthorized:false},k);
 }
 if(input.sourceRequestId!==undefined||!input.playbookId||!input.playbookVersion||!Array.isArray(input.outcomeDigests))throw new CapabilityInputError('EXACT_PROCEDURE_SOURCE_REQUIRED');
 const k=knowledge(ctx);const reasons:string[]=[];if(!k)return result({status:'EVIDENCE_REQUIRED',candidate:null,persisted:false,sourceKnowledgeDigest:null,reasons:['Trusted procedure history required.'],executionAuthorized:false},k);
 const p=k.playbooks.find(p=>p.id===input.playbookId&&p.version===input.playbookVersion);const requested=strings(input.outcomeDigests!);if(new Set(requested).size!==requested.length)throw new CapabilityInputError('DUPLICATE_OUTCOME_DIGEST');
 if(!p||p.status!=='VERIFIED'||p.qualificationStatus!=='independently_qualified'||p.supersededBy)reasons.push('A current independently qualified source playbook is required.');
 const history=p?outcomeHistory(k,p):[];const selected=requested.map(id=>history.find(o=>digest(o)===id));
 if(!requested.length||selected.some(o=>!o||o.outcome!=='VERIFIED'||!o.freshVerificationEvidence.length))reasons.push('Every requested outcome must be an actual freshly verified successful stored job.');
 if(p&&!current(p,ctx).reusable)reasons.push('Source applicability does not match current authoritative identity.');
 if(history.some(o=>o.outcome==='FAILED'))reasons.push('This procedure version has a failed execution; an independently qualified new version is required.');
 if(reasons.length)return result({status:'EVIDENCE_REQUIRED',candidate:null,persisted:false,sourceKnowledgeDigest:kd(k),reasons,executionAuthorized:false},k);
 const candidate=buildCandidate(p!,selected as ReuseOutcomeRecord[]);
 return result({status:'CANDIDATE_READY',candidate:{id:candidate.id,version:1,status:'CANDIDATE',sourcePlaybookId:p!.id,outcomeDigests:requested.slice().sort(),procedure:candidate.procedure,acceptanceCriteria:candidate.acceptanceCriteria,qualificationRequired:true},persisted:false,sourceKnowledgeDigest:kd(k),reasons:[],executionAuthorized:false},k,['A candidate remains unqualified and cannot execute until existing independent qualification and promotion requirements are satisfied.']);
}
function buildCandidate(source:ProceduralPlaybook,outcomes:ReuseOutcomeRecord[]):ProceduralPlaybook {
 const outcomeDigests=outcomes.map(digest).sort();const id=`experience-${digest({source:digest(source),outcomeDigests}).slice(0,40)}`;
 return {...structuredClone(source),id,version:1,status:'CANDIDATE',provenance:{producerIdentity:'sara-experience-compiler',source:`playbook:${key(source)}`},sourceEvidence:unique([...source.sourceEvidence,...outcomeDigests]),qualificationStatus:'pending_independent_qualification',qualificationDigest:'',evaluatorIdentity:'unassigned',verifiedAt:null,createdAt:outcomes.map(o=>o.createdAt).sort().at(-1)!,supersedes:[],supersededBy:null,qualificationStrength:0};
}
export function effectiveness(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const k=knowledge(ctx);const history=k?outcomeHistory(k,{id:String(input.playbookId),version:Number(input.playbookVersion)}):[];const successes=history.filter(o=>o.outcome==='VERIFIED').length;
 const measurements=rows(input.measurements??[]),accepted:Data[]=[],rejected:string[]=[],measurementEvidenceDigests:string[]=[];const seen=new Set<string>();
 for(const row of measurements){const {evidenceId,...material}=row;const materialDigest=digest(material);const uniqueKey=`${String(row.taskReferenceDigest)}:${String(row.group)}`;if(seen.has(uniqueKey))throw new CapabilityInputError('DUPLICATE_PERFORMANCE_MEASUREMENT');seen.add(uniqueKey);
 const e=ctx.evidence.find(e=>e.id===evidenceId);const proofCurrent=e&&assessEvidence({record:e,requiredProvenance:[e.provenance],requiredClaims:['procedure-performance-measurement'],currentIdentity:{...ctx.currentIdentity,playbookId:input.playbookId as string,playbookVersion:input.playbookVersion as number,taskReferenceDigest:row.taskReferenceDigest as string,comparisonId:row.comparisonId as string,basisDigest:row.basisDigest as string}}).status==='VALID';
 if(!history.some(o=>o.taskReferenceDigest===row.taskReferenceDigest)||!e||e.integrity!=='KERNEL_RECEIPT'||e.provenance==='SUPPLIED'||e.contentDigest!==materialDigest||!proofCurrent||e.subject.playbookId!==input.playbookId||e.subject.playbookVersion!==input.playbookVersion||e.subject.taskReferenceDigest!==row.taskReferenceDigest||e.subject.comparisonId!==row.comparisonId||e.subject.basisDigest!==row.basisDigest||(row.regressions!==null&&(row.regressionOpportunities===null||Number(row.regressions)>Number(row.regressionOpportunities)))){rejected.push(materialDigest);continue;}
 accepted.push(row);measurementEvidenceDigests.push(e.contentDigest);
 }
 const reuse=accepted.filter(m=>m.group==='REUSE');const values=(field:string)=>reuse.filter(m=>m[field]!==null).map(m=>Number(m[field]));const average=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:null;const sum=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0):null;
 const regressionRows=reuse.filter(m=>m.regressions!==null&&Number(m.regressionOpportunities)>0);const opportunities=regressionRows.reduce((a,b)=>a+Number(b.regressionOpportunities),0);
 const pairs=accepted.filter(m=>m.group==='BASELINE').flatMap(b=>{const r=reuse.find(r=>r.taskReferenceDigest===b.taskReferenceDigest&&r.comparisonId===b.comparisonId&&r.basisDigest===b.basisDigest);return r?[{baseline:b,reuse:r}]:[];});
 const differences=(field:string)=>pairs.filter(p=>p.baseline[field]!==null&&p.reuse[field]!==null).map(p=>Number(p.baseline[field])-Number(p.reuse[field]));const regressionDiff=pairs.filter(p=>p.baseline.regressions!==null&&p.reuse.regressions!==null&&Number(p.baseline.regressionOpportunities)>0&&Number(p.reuse.regressionOpportunities)>0).map(p=>Number(p.baseline.regressions)/Number(p.baseline.regressionOpportunities)-Number(p.reuse.regressions)/Number(p.reuse.regressionOpportunities));
 return result({status:history.length?'MEASURED':'INSUFFICIENT_EVIDENCE',samples:history.length,successes,failures:history.length-successes,successRate:history.length?successes/history.length:null,operationsAvoided:history.reduce((sum,o)=>sum+o.operationsAvoided.length,0),latestOutcome:history.at(-1)?.outcome??null,completionTimeMs:average(values('elapsedMs')),cashCostMicroUsd:sum(values('cashMicroUsd')),retryCount:sum(values('retries')),humanInterventions:sum(values('humanInterventions')),regressionRate:opportunities?regressionRows.reduce((a,b)=>a+Number(b.regressions),0)/opportunities:null,measurementCoverage:{time:values('elapsedMs').length,cash:values('cashMicroUsd').length,retries:values('retries').length,humanInterventions:values('humanInterventions').length,regressions:regressionRows.length},comparisons:{pairedSamples:pairs.length,meanTimeSavedMs:average(differences('elapsedMs')),cashSavedMicroUsd:sum(differences('cashMicroUsd')),meanRetryReduction:average(differences('retries')),meanHumanInterventionReduction:average(differences('humanInterventions')),meanRegressionRateReduction:average(regressionDiff)},rejectedMeasurementDigests:rejected,measurementEvidenceDigests:unique(measurementEvidenceDigests),outcomeDigests:history.slice(-256).map(digest),historyReferencesTruncated:history.length>256,sourceKnowledgeDigest:kd(k)},k,['Performance values cover only the explicitly counted trusted measurements. Missing telemetry remains unknown. Comparative savings require paired baseline/reuse measurements for the same task and comparison basis; correlation is not proof of causation.']);
}
export function conflicts(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const k=knowledge(ctx);const groups=new Map<string,typeof k extends null?never:NonNullable<typeof k>['lessons']>();
 for(const l of k?.lessons??[]){if(l.taskFamily!==input.taskFamily||l.status!=='VERIFIED')continue;const claim=l.claimKey??l.id;groups.set(claim,[...(groups.get(claim)??[]),l]);}
 const found:Data[]=[];for(const [claimKey,lessons]of groups){if(new Set(lessons.map(l=>digest({inference:l.inference,nature:l.nature}))).size>1)found.push({claimKey,lessonIds:unique(lessons.map(l=>l.id)),inferenceDigests:unique(lessons.map(l=>digest(l.inference)))});}
 const supersessions=(k?.playbooks??[]).filter(p=>p.taskFamily===input.taskFamily&&p.supersededBy).map(p=>({oldId:p.id,oldVersion:p.version,replacementKey:p.supersededBy!}));
 return result({status:!k?'EVIDENCE_REQUIRED':input.operation==='SUPERSEDE'?'BLOCKED':found.length?'CONFLICTS_REQUIRE_REVIEW':'NO_CONFLICT_OBSERVED',conflicts:found.slice(0,32).map(c=>({...c,lessonIds:strings(c.lessonIds!).slice(0,8),inferenceDigests:strings(c.inferenceDigests!).slice(0,8)})),conflictsTruncated:found.length>32||found.some(c=>strings(c.lessonIds!).length>8||strings(c.inferenceDigests!).length>8),totalConflictGroups:found.length,supersessions,historyPreserved:true,persisted:false,sourceKnowledgeDigest:kd(k),reasons:input.operation==='SUPERSEDE'?['Exact authenticated owner application through the existing procedural store is required.']:[]},k,['Contradictory knowledge remains auditable. Different statements may be compatible in different scopes; no model opinion automatically invalidates knowledge.']);
}
function timestamp(value:string):number|null{if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value))return null;const ms=Date.parse(value);return Number.isFinite(ms)?ms:null;}
export function expiration(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const k=knowledge(ctx),at=timestamp(String(input.asOf));if(at===null)throw new CapabilityInputError('EXPLICIT_VALID_TIMEZONE_REQUIRED');const rules=rows(input.rules!);const seen=new Set<string>();const entries:Data[]=[];
 for(const r of rules){const ruleKey=`${r.kind}:${r.id}@${r.version}`;if(seen.has(ruleKey))throw new CapabilityInputError('DUPLICATE_KNOWLEDGE_RULE');seen.add(ruleKey);const p=r.kind==='PLAYBOOK'?k?.playbooks.find(p=>p.id===r.id&&p.version===r.version):k?.lessons.find(l=>l.id===r.id&&l.version===r.version);
 const verified=p?.verifiedAt?timestamp(p.verifiedAt):null;const age=verified!==null&&at>=verified?Math.floor((at-verified)/1000):null;let state='UNKNOWN',reason='No matching verified knowledge record or reliable time bound.';
 if(p&&p.status==='VERIFIED'&&verified!==null&&at>=verified){if(r.nature==='IMMUTABLE_HISTORICAL_FACT'){state='VALID';reason='Historical facts do not expire merely because time passes.';}else if(r.maximumAgeSeconds!==null){state=age!>Number(r.maximumAgeSeconds)?'REVERIFY':'VALID';reason=state==='VALID'?'Within the supplied class-specific freshness interval.':'Time-sensitive knowledge exceeds the supplied freshness interval.';}}
 entries.push({id:r.id!,version:r.version!,state,reason,ageSeconds:age});}
 return result({status:k&&entries.length?'ASSESSED':'INSUFFICIENT_EVIDENCE',knowledge:entries,sourceKnowledgeDigest:kd(k),historyChanged:false},k,['Freshness intervals are supplied advisory policy. Identity/integrity invalidation and explicit authority always apply independently of age.']);
}
export function failureMemory(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const k=knowledge(ctx);const tokens=(s:string)=>new Set(s.toLowerCase().match(/[a-z0-9_]{3,}/g)??[]);const query=tokens(String(input.signature));const matches:Data[]=[];
 for(const l of k?.lessons??[]){if(l.taskFamily!==input.taskFamily||l.nature!=='NEGATIVE'||l.status!=='VERIFIED')continue;const words=tokens(l.observation);const union=new Set([...query,...words]);const intersection=[...query].filter(w=>words.has(w)).length;if(!intersection)continue;const compatible=decidePriorEvidenceReuse({expectedIdentity:l.applicabilityIdentity,currentIdentity:ctx.currentIdentity});matches.push({id:l.id,version:l.version,similarity:intersection/union.size,revalidationRequired:true,applicableNow:compatible.reusable,evidenceDigests:l.sourceEvidence.slice(0,16).map(digest),lessonDigest:digest(l),evidenceReferencesTruncated:l.sourceEvidence.length>16,mismatchReasons:compatible.reusable?[]:[compatible.reason]});}
 matches.sort((a,b)=>Number(b.applicableNow)-Number(a.applicableNow)||Number(b.similarity)-Number(a.similarity)||String(a.id).localeCompare(String(b.id)));
 return result({matches:matches.slice(0,Number(input.maximumResults)),sourceKnowledgeDigest:kd(k),identityEstablished:false},k,['Lexical similarity retrieves prior diagnosis evidence; it does not establish that the current incident has the same root cause.']);
}
export function rankReuse(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const k=knowledge(ctx);const ranking:Data[]=[];const eligible:ProceduralPlaybook[]=[];
 for(const p of k?.playbooks??[]){if(p.taskFamily!==input.taskFamily)continue;const history=outcomeHistory(k!,p),reasons:string[]=[];if(p.status!=='VERIFIED'||p.qualificationStatus!=='independently_qualified')reasons.push('NOT_INDEPENDENTLY_VERIFIED');if(p.supersededBy)reasons.push('SUPERSEDED');const applicable=current(p,ctx);if(!applicable.reusable)reasons.push('APPLICABILITY_IDENTITY_MISMATCH');if(history.some(o=>o.outcome==='FAILED'))reasons.push('VERSION_REUSE_FAILED_QUALIFY_NEW_VERSION');const prior=decidePriorEvidenceReuse({expectedIdentity:p.evidenceReuseIdentity,currentIdentity:ctx.currentIdentity});if(!reasons.length)eligible.push(p);ranking.push({id:p.id,version:p.version,eligible:reasons.length===0,specificity:Object.keys(p.procedureApplicabilityIdentity).length,successes:history.filter(o=>o.outcome==='VERIFIED').length,failures:history.filter(o=>o.outcome==='FAILED').length,mismatchReasons:reasons,evidenceReusable:prior.reusable});}
 ranking.sort((a,b)=>Number(b.eligible)-Number(a.eligible)||Number(b.specificity)-Number(a.specificity)||Number(b.successes)-Number(a.successes)||Number(a.failures)-Number(b.failures)||String(a.id).localeCompare(String(b.id)));
 let selectedId:string|null=null;if(eligible.length){const best=ProceduralKnowledgeStore.inMemory(eligible).select({taskId:'capability-selection',description:'bounded supplied task family',taskFamily:String(input.taskFamily),identity:ctx.currentIdentity,requestedActions:[]});selectedId=best.playbook.id;const index=ranking.findIndex(r=>r.id===selectedId&&r.version===best.playbook.version);if(index>0)ranking.unshift(...ranking.splice(index,1));}
 return result({status:!k?'INSUFFICIENT_EVIDENCE':selectedId?'CANDIDATE_SELECTED':'NO_APPLICABLE_PROCEDURE',selectedId,ranking:ranking.slice(0,Number(input.maximumResults)),sourceKnowledgeDigest:kd(k),executionAuthorized:false},k,['Selected knowledge is a candidate strategy. Fresh outcome verification and existing execution authority remain required.']);
}
export function counterexamples(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const k=knowledge(ctx);const sources:Data[]=[];
 for(const l of k?.lessons??[])if(l.taskFamily===input.taskFamily&&(l.claimKey??l.id)===input.claimKey&&l.status==='VERIFIED'&&decidePriorEvidenceReuse({expectedIdentity:l.applicabilityIdentity,currentIdentity:ctx.currentIdentity}).reusable)sources.push({sourceId:l.id,contentDigest:digest(l),basis:'TRUSTED_CONFLICTING_LESSON',contradicts:l.inference!==input.proposedInference});
 for(const id of unique(strings(input.evidenceIds!))){const e=ctx.evidence.find(e=>e.id===id);if(!e||e.provenance==='SUPPLIED'||e.integrity!=='KERNEL_RECEIPT'||e.subject.claimKey!==input.claimKey||assessEvidence({record:e,requiredProvenance:[e.provenance],requiredClaims:[],currentIdentity:{...ctx.currentIdentity,claimKey:input.claimKey as string}}).status!=='VALID')continue;sources.push({sourceId:e.id,contentDigest:e.contentDigest,basis:'TRUSTED_NEGATIVE_CLAIM',contradicts:e.claims.includes(`contradicts:${String(input.claimKey)}`)});}
 const bounded=sources.slice(0,Number(input.maximumItems));const found=bounded.filter(s=>s.contradicts).map(({contradicts,...s})=>s);
 return result({status:found.length?'COUNTEREXAMPLES_FOUND':bounded.length?'NONE_IN_BOUNDED_EVIDENCE':'INSUFFICIENT_EVIDENCE',counterexamples:found,examined:bounded.length,remaining:Math.max(0,sources.length-bounded.length),conclusionProven:false,sourceKnowledgeDigest:kd(k)},k,['No counterexample in a bounded search is not proof of truth; differing trusted inferences require scope review.']);
}
export function calibrate(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const k=knowledge(ctx);const forecasts=rows(input.forecasts!);requireUnique(forecasts,'taskReferenceDigest');const rejected:string[]=[],evidenceDigests:string[]=[];let samples=0,successes=0,error=0;
 for(const f of forecasts){const outcomes=k?.outcomes.filter(o=>o.taskFamily===input.taskFamily&&o.taskReferenceDigest===f.taskReferenceDigest)??[];const e=ctx.evidence.find(e=>e.id===f.evidenceId);const forecastDigest=digest({taskReferenceDigest:f.taskReferenceDigest,probability:f.probability});const first=outcomes[0];
 if(!first||outcomes.some(o=>o.outcome!==first.outcome)||!e||e.integrity!=='KERNEL_RECEIPT'||e.provenance==='SUPPLIED'||e.contentDigest!==forecastDigest||e.subject.taskReferenceDigest!==f.taskReferenceDigest||e.subject.taskFamily!==input.taskFamily||!e.claims.includes('pre-outcome-forecast')||!e.capturedAt||timestamp(e.capturedAt)===null||timestamp(first.createdAt)===null||timestamp(e.capturedAt)!>=timestamp(first.createdAt)!){rejected.push(forecastDigest);continue;}
 samples++;const actual=first.outcome==='VERIFIED'?1:0;successes+=actual;error+=(Number(f.probability)-actual)**2;evidenceDigests.push(digest(first),e.contentDigest);
 }
 return result({status:samples?'EMPIRICAL_CALIBRATION':'INSUFFICIENT_EVIDENCE',samples,successes,empiricalSuccessRate:samples?successes/samples:null,smoothedProbability:samples?(successes+1)/(samples+2):null,brierScore:samples?error/samples:null,rejectedForecastDigests:rejected,evidenceDigests:unique(evidenceDigests),sourceKnowledgeDigest:kd(k),generalizationProven:false},k,['Calibration uses only digest-bound forecasts captured before an independently recorded outcome. Laplace smoothing avoids unsupported certainty; task/environment generalization remains unproven.']);
}
const executions:Record<string,(input:Data,ctx:ExecutionContext)=>ExecutionOutput>={'experience-to-procedure-compiler':compileCandidate,'procedure-effectiveness-scorer':effectiveness,'memory-conflict-resolver':conflicts,'knowledge-expiration-manager':expiration,'failure-pattern-memory':failureMemory,'solution-reuse-ranker':rankReuse,'counterexample-seeker':counterexamples,'confidence-calibrator':calibrate};
export async function executeProceduralCapability(id:string,input:Data,context:ExecutionContext,stateDirectory:string):Promise<ExecutionOutput>{
 const execute=executions[id];if(!execute)throw new CapabilityInputError('UNKNOWN_PROCEDURAL_CAPABILITY');validateSchema(schemas[id]!.input,input);
 const snapshot=await ProceduralKnowledgeStore.inspectExisting(stateDirectory);const ctx:ProceduralContext={...context,proceduralKnowledge:snapshot};const initial=execute(input,ctx);const output=data(initial.output);
 const mutation=id==='experience-to-procedure-compiler'&&output.status==='CANDIDATE_READY'||id==='memory-conflict-resolver'&&input.operation==='SUPERSEDE';if(!mutation)return initial;
 const ownerBound=context.ownerAuthenticated||id==='experience-to-procedure-compiler'&&input.sourceKind==='ISOLATED_REPAIR_RECEIPT'&&context.ownerProcedureCompilationAuthorized===true;
 if(!ownerBound||!context.policyDecision.allowed||context.emergencyStopped)return {...initial,output:{...output,status:'BLOCKED',reasons:['Authenticated owner admission, existing record_memory authority and emergency-stop clear are required.']},status:'BLOCKED'};
 if(id==='experience-to-procedure-compiler'&&input.sourceKind==='ISOLATED_REPAIR_RECEIPT'){
  const candidate=verifiedRepairCandidate(input,ctx);if(!candidate)throw new CapabilityInputError('EXACT_REPAIR_RECEIPT_REQUIRED');
  const store=await ProceduralKnowledgeStore.open(stateDirectory,[]);
  const existing=store.snapshot().playbooks.find(p=>p.id===candidate.id&&p.version===1);
  if(existing){const {createdAt:_,...material}=candidate;const {createdAt:__,...stored}=existing;if(digest(material)!==digest(stored))throw new CapabilityInputError('CANDIDATE_IDENTITY_CONFLICT');}
  else await store.addCandidatePlaybook(candidate);
  return {...initial,output:{...output,persisted:true}};
 }
 if(!snapshot)return initial;
 if(id==='experience-to-procedure-compiler'){
  const source=snapshot.playbooks.find(p=>p.id===input.playbookId&&p.version===input.playbookVersion)!;const history=outcomeHistory(snapshot,source).filter(o=>strings(input.outcomeDigests!).includes(digest(o)));const candidate=buildCandidate(source,history);const existing=snapshot.playbooks.find(p=>p.id===candidate.id&&p.version===1);
  if(existing){if(existing.provenance.source!==candidate.provenance.source||digest(existing.procedure)!==digest(candidate.procedure)||digest(existing.sourceEvidence)!==digest(candidate.sourceEvidence))throw new CapabilityInputError('CANDIDATE_IDENTITY_CONFLICT');return {...initial,output:{...output,candidate:{...data(output.candidate!),status:existing.status},persisted:true,sourceKnowledgeDigest:input.expectedKnowledgeDigest!}};}
  if(input.expectedKnowledgeDigest!==digest(snapshot))throw new CapabilityInputError('PROCEDURAL_STATE_CHANGED');const store=await ProceduralKnowledgeStore.open(stateDirectory,[]);if(digest(store.snapshot())!==digest(snapshot))throw new CapabilityInputError('PROCEDURAL_STATE_CHANGED');await store.addCandidatePlaybook(candidate);
  return {...initial,output:{...output,persisted:true}};
 }
 for(const field of ['oldId','oldVersion','replacementId','replacementVersion','oldDigest','replacementDigest','expectedKnowledgeDigest'])if(input[field]===null)throw new CapabilityInputError('EXACT_SUPERSESSION_IDENTITY_REQUIRED');
 const old=snapshot.playbooks.find(p=>p.id===input.oldId&&p.version===input.oldVersion),replacement=snapshot.playbooks.find(p=>p.id===input.replacementId&&p.version===input.replacementVersion);if(!old||!replacement)throw new CapabilityInputError('UNKNOWN_PLAYBOOK');
 const reason=`capability-supersession:${digest({oldId:input.oldId,oldVersion:input.oldVersion,replacementId:input.replacementId,replacementVersion:input.replacementVersion,oldDigest:input.oldDigest,replacementDigest:input.replacementDigest,expectedKnowledgeDigest:input.expectedKnowledgeDigest})}`;
 const completed=old.supersededBy===key(replacement)&&snapshot.invalidations.some(i=>i.targetId===old.id&&i.targetVersion===old.version&&i.reason===reason);
 if(!completed){if(input.expectedKnowledgeDigest!==digest(snapshot)||digest(old)!==input.oldDigest||digest(replacement)!==input.replacementDigest)throw new CapabilityInputError('PROCEDURAL_STATE_CHANGED');if(old.taskFamily!==input.taskFamily||replacement.taskFamily!==input.taskFamily||replacement.status!=='VERIFIED'||replacement.qualificationStatus!=='independently_qualified'||!current(replacement,context).reusable||!replacement.verifiedAt||!old.verifiedAt||timestamp(replacement.verifiedAt)===null||timestamp(old.verifiedAt)===null||timestamp(replacement.verifiedAt)!<=timestamp(old.verifiedAt)!)throw new CapabilityInputError('FRESH_VERIFIED_REPLACEMENT_REQUIRED');
 const replacementHistory=outcomeHistory(snapshot,replacement);const latest=replacementHistory.at(-1);if(!latest||replacementHistory.some(o=>o.outcome==='FAILED')||latest.outcome!=='VERIFIED'||!latest.freshVerificationEvidence.length)throw new CapabilityInputError('FRESH_REPLACEMENT_EXECUTION_REQUIRED');const store=await ProceduralKnowledgeStore.open(stateDirectory,[]);if(digest(store.snapshot())!==digest(snapshot))throw new CapabilityInputError('PROCEDURAL_STATE_CHANGED');await store.supersedePlaybook(old.id,old.version,replacement.id,replacement.version,reason);}
 return {...initial,output:{...output,status:'SUPERSEDED',persisted:true,sourceKnowledgeDigest:input.expectedKnowledgeDigest!,reasons:[],supersessions:[{oldId:old.id,oldVersion:old.version,replacementKey:key(replacement)}]}};
}

/** Minimum persistent dependencies for reusable capability receipts; timestamps and unrelated families do not churn proofs. */
export function proceduralDependencyDigest(id:string,input:Data,snapshot:ProceduralKnowledgeSnapshot|null):string {
 if(id==='experience-to-procedure-compiler'&&input.sourceKind==='ISOLATED_REPAIR_RECEIPT')return digest({candidates:(snapshot?.playbooks??[]).filter(p=>p.provenance.source===repairCandidateSource(String(input.sourceRequestId)))});
 if(id==='solution-reuse-ranker')return digest({playbooks:(snapshot?.playbooks??[]).filter(p=>p.taskFamily===input.taskFamily),outcomes:(snapshot?.outcomes??[]).filter(o=>o.taskFamily===input.taskFamily)});
 if(!snapshot)return digest({state:'ABSENT'});
 if(id==='experience-to-procedure-compiler'||id==='memory-conflict-resolver'&&input.operation==='SUPERSEDE')return digest(snapshot);
 if(id==='procedure-effectiveness-scorer')return digest({outcomes:snapshot.outcomes.filter(o=>o.playbookId===input.playbookId&&o.playbookVersion===input.playbookVersion)});
 if(id==='knowledge-expiration-manager'){const rules=rows(input.rules!);return digest({records:rules.map(r=>({kind:r.kind,id:r.id,version:r.version,record:r.kind==='PLAYBOOK'?(snapshot.playbooks.find(p=>p.id===r.id&&p.version===r.version)??null):(snapshot.lessons.find(l=>l.id===r.id&&l.version===r.version)??null)}))});}
 if(id==='failure-pattern-memory')return digest({lessons:snapshot.lessons.filter(l=>l.taskFamily===input.taskFamily&&l.nature==='NEGATIVE')});
 if(id==='confidence-calibrator'){const taskDigests=new Set(rows(input.forecasts!).map(f=>f.taskReferenceDigest));return digest({outcomes:snapshot.outcomes.filter(o=>o.taskFamily===input.taskFamily&&taskDigests.has(o.taskReferenceDigest))});}
 if(id==='counterexample-seeker')return digest({lessons:snapshot.lessons.filter(l=>l.taskFamily===input.taskFamily&&(l.claimKey??l.id)===input.claimKey)});
 if(id==='memory-conflict-resolver')return digest({lessons:snapshot.lessons.filter(l=>l.taskFamily===input.taskFamily),playbooks:snapshot.playbooks.filter(p=>p.taskFamily===input.taskFamily)});
 throw new CapabilityInputError('UNKNOWN_PROCEDURAL_CAPABILITY');
}
