import { arraySchema as list,objectSchema as obj,textSchema as text,idSchema as id,integerSchema as integer,enumSchema as choice,digestSchema as dg,type Schema } from '../schema.ts';
const bool:Schema={type:'boolean'};const nil=(s:Schema):Schema=>({...s,nullable:true});const ids=list(id,128),texts=list(text(1024),128);export const runIdSchema:Schema={...text(40),pattern:'^comprun_[0-9a-f]{32}$'};export const shaSchema:Schema={...text(40,40),pattern:'^[a-f0-9]{40}$'};
export const identitySchema=obj({runId:runIdSchema,repository:{...text(200),pattern:'^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'},commitSha:shaSchema,revision:integer(1),reportDigest:dg});
const mode=choice('HUMAN_REVIEWED','AUTOMATED_TECHNICAL');
export const scannerInput=obj({identity:identitySchema,scanners:list(obj({id,applicability:choice('APPLICABLE','NOT_APPLICABLE','UNKNOWN'),proofIds:ids}),64),inventoryProofIds:ids});
const scannersOutput=obj({status:choice('COMPLETE','BLOCKED','INCOMPLETE_EVIDENCE'),scanners:list(obj({id,state:choice('EXECUTION_VERIFIED','INAPPLICABILITY_VERIFIED','MISSING_EVIDENCE','UNKNOWN_APPLICABILITY')}),64),inventoryVerified:bool,sourceDigest:dg});
export const approvalInput=obj({identity:identitySchema,mode,producerId:id,reviewerId:nil(id),qcActorId:nil(id),approverId:nil(id),proofIds:ids});
const approvalOutput=obj({status:choice('VERIFIED_HUMAN_APPROVAL','VERIFIED_AUTOMATED_AUTHORIZATION','BLOCKED','INCOMPLETE_EVIDENCE'),humanReviewed:bool,independentQcVerified:bool,approvalSynthesized:bool,reasons:texts,executionAuthorized:bool});
const reviewInput=obj({identity:identitySchema,mode,scannerInput,producerId:id,specialistId:nil(id),qcActorId:nil(id),requiredHumanCandidateIds:ids,pendingCandidateIds:ids,proofIds:ids});
export const schemas:Record<string,{input:Schema;output:Schema}>={
 'nico-run-health-diagnoser':{input:obj({identity:identitySchema,stages:list(obj({id,status:choice('PENDING','RUNNING','COMPLETE','FAILED','BLOCKED'),dependsOn:ids,proofIds:ids}),64),proofIds:ids}),output:obj({status:choice('HEALTHY_PROGRESS','BLOCKED','INCOMPLETE_EVIDENCE'),primaryFailureIds:ids,cascadeIds:ids,readyStageIds:ids,unverifiedCompleteIds:ids,missingDependencies:ids,cycleStageIds:ids,runComplete:bool,nextAction:text(1024),sourceDigest:dg})},
 'nico-scanner-completeness-validator':{input:scannerInput,output:scannersOutput},
 'nico-specialist-queue-triage':{input:obj({identity:identitySchema,candidates:list(obj({id,severity:choice('CRITICAL','HIGH','MEDIUM','LOW','INFORMATIONAL'),requiresHuman:bool,ageHours:integer(0,100000),dependencies:ids,proofIds:ids}),128)}),output:obj({queue:list(obj({id,disposition:choice('SPECIALIST_REVIEW_REQUIRED','DISPOSITION_VERIFIED','AUTOMATED_TRIAGE_VERIFIED','REQUIREMENT_UNKNOWN'),blockedBy:ids,priority:integer(0,4)}),128),impersonatedSpecialist:bool,sourceDigest:dg})},
 'nico-review-readiness-validator':{input:reviewInput,output:obj({status:choice('READY_FOR_SPECIALIST_REVIEW','READY_FOR_FINAL_APPROVAL','AUTOMATED_TECHNICAL_BOUNDARY','BLOCKED','INCOMPLETE_EVIDENCE'),missingRequirements:texts,sourceVerified:bool,scannersComplete:bool,independentQcVerified:bool,humanReviewCompleted:bool,approvalGranted:bool})},
 'nico-export-integrity-verifier':{input:obj({identity:identitySchema,mode,artifactName:id,contentBase64:text(131072,0),expectedDigest:dg,proofIds:ids,artifactIdentity:nil(obj({schema:text(160),run_id:runIdSchema,revision:integer(1),report_artifact_digest:dg,artifact_digests:list(obj({name:id,digest:dg}),16)}))}),output:obj({status:choice('INTEGRITY_VERIFIED','BLOCKED','INCOMPLETE_EVIDENCE'),actualDigest:dg,bytes:integer(0,98304),canonicalBindingVerified:bool,automatedPackageVerified:bool,humanReviewed:bool,deliveryAuthorized:bool,reasons:texts})},
 'nico-bilingual-equivalence-checker':{input:obj({identity:identitySchema,producerId:id,reviewerId:nil(id),sections:list(obj({id,en:text(8192),esMx:text(8192)}),16),proofIds:ids}),output:obj({status:choice('MATERIAL_DISCREPANCY_DETECTED','VERIFIED_EQUIVALENCE','INDEPENDENT_SEMANTIC_REVIEW_REQUIRED'),discrepancies:list(obj({sectionId:id,kind:choice('NUMERIC_OR_IDENTIFIER','SEVERITY','NEGATION'),enDigest:dg,esMxDigest:dg}),48),contentDigest:dg,semanticEquivalenceProven:bool,linguisticDifferencesAllowed:bool})},
 'nico-approval-provenance-verifier':{input:approvalInput,output:approvalOutput},
 'nico-delivery-readiness-gate':{input:obj({identity:identitySchema,mode,scannerInput,approval:approvalInput,artifactDigest:dg,bilingualContentDigest:dg,proofIds:ids}),output:obj({status:choice('READY_UNDER_EXISTING_DELIVERY_AUTHORITY','BLOCKED','INCOMPLETE_EVIDENCE'),missingRequirements:texts,humanReviewed:bool,technicalOnly:bool,deliveryExecuted:bool,deliveryAuthorityGranted:bool})},
 'nico-production-proof-runner':{input:obj({identity:identitySchema,expectedDeploymentSha:nil(shaSchema),expectedDeploymentId:nil(id)}),output:obj({status:choice('PRODUCTION_IDENTITY_OBSERVED','ISOLATED_IDENTITY_OBSERVED','INCOMPLETE_EVIDENCE','BLOCKED'),provenance:choice('PRODUCTION','ISOLATED','EXTERNAL_READ_ONLY','NONE'),sourceUrl:nil(text(512)),deploymentSha:nil(shaSchema),deploymentId:nil(id),runIdentityMatched:bool,artifactIdentityMatched:bool,responseDigest:nil(dg),readRequests:integer(0,1),reasons:texts,externalMutations:integer(0,0)})},
 'nico-client-status-compiler':{input:obj({identity:identitySchema,mode,proofIds:ids}),output:obj({status:choice('ASSESSMENT_IN_PROGRESS','SPECIALIST_REVIEW_PENDING','APPROVED_AWAITING_DELIVERY','AUTOMATED_TECHNICAL_PACKAGE_READY','DELIVERY_VERIFIED','UNKNOWN'),message:text(1024),humanReviewed:nil(bool),securityCertificationClaimed:bool,protectedInternalInformationIncluded:bool,transmissionAuthorized:bool})},
};
