import type { CapabilityDefinition,ExecutionOutput,FrozenCase } from '../types.ts';
import type { Json } from '../schema.ts';
import { schemas } from './contracts.ts';
import { approval,bilingual,clientStatus,delivery,exportsIntegrity,health,queue,readiness,scanners } from './implementations.ts';
import { productionProof } from './observer.ts';
const out=(r:ExecutionOutput)=>r.output as Record<string,Json>;
export const identity={runId:`comprun_${'a'.repeat(32)}`,repository:'owner/repository',commitSha:'b'.repeat(40),revision:1,reportDigest:'c'.repeat(64)};
export const emptyScanners={identity,scanners:[],inventoryProofIds:[]};
export const emptyApproval={identity,mode:'HUMAN_REVIEWED',producerId:'sara',reviewerId:null,qcActorId:null,approverId:null,proofIds:[]};
const entries:Record<string,{description:string;execute:CapabilityDefinition['execute'];externalRead?:boolean;draft?:boolean;cases:FrozenCase[]}>= {
 'nico-run-health-diagnoser':{description:'Analyze exact-run stage dependencies, primary failure hypotheses, cascades and verified completion without advancing a run.',execute:health,cases:[{name:'empty-is-not-complete',input:{identity,stages:[],proofIds:[]},check:r=>out(r).runComplete===false},{name:'supplied-complete-is-not-proof',input:{identity,stages:[{id:'scan',status:'COMPLETE',dependsOn:[],proofIds:[]}],proofIds:[]},check:r=>(out(r).unverifiedCompleteIds as Json[]).length===1}]},
 'nico-scanner-completeness-validator':{description:'Require exact authoritative scanner inventory and per-scanner execution or inapplicability evidence; missing is never not applicable.',execute:scanners,cases:[{name:'empty-inventory-incomplete',input:emptyScanners,check:r=>out(r).status==='INCOMPLETE_EVIDENCE'},{name:'claimed-not-applicable-needs-proof',input:{...emptyScanners,scanners:[{id:'semgrep',applicability:'NOT_APPLICABLE',proofIds:[]}]},check:r=>(out(r).scanners as Record<string,Json>[])[0]?.state==='MISSING_EVIDENCE'}]},
 'nico-specialist-queue-triage':{description:'Prioritize actual supplied candidate work with evidence-backed dispositions and explicit human-review applicability, without impersonation.',execute:queue,cases:[{name:'empty-queue-no-invented-work',input:{identity,candidates:[]},check:r=>(out(r).queue as Json[]).length===0},{name:'unsupported-review-exclusion-stays-unknown',input:{identity,candidates:[{id:'finding',severity:'HIGH',requiresHuman:false,ageHours:0,dependencies:[],proofIds:[]}]},check:r=>(out(r).queue as Record<string,Json>[])[0]?.disposition==='REQUIREMENT_UNKNOWN'}]},
 'nico-review-readiness-validator':{description:'Evaluate exact immutable source, scanner inventory, human dispositions and independent QC, preserving the separately authorized automated technical mode.',execute:readiness,cases:[{name:'missing-evidence-is-not-ready-for-review',input:{identity,mode:'HUMAN_REVIEWED',scannerInput:emptyScanners,producerId:'sara',specialistId:null,qcActorId:null,requiredHumanCandidateIds:[],pendingCandidateIds:[],proofIds:[]},check:r=>out(r).status==='INCOMPLETE_EVIDENCE'&&out(r).approvalGranted===false}]},
 'nico-export-integrity-verifier':{description:'Hash actual supplied export bytes and require exact canonical provenance; route automated ZIPs through the existing NICO production package verifier.',execute:exportsIntegrity,cases:[{name:'empty-export-not-verified',input:{identity,mode:'HUMAN_REVIEWED',artifactName:'report',contentBase64:'',expectedDigest:'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',proofIds:[],artifactIdentity:null},check:r=>out(r).status==='BLOCKED'}]},
 'nico-bilingual-equivalence-checker':{description:'Compare English/es-MX numeric, identifier, severity and negation signals; full semantic equivalence requires exact independent review proof.',execute:bilingual,cases:[{name:'numeric-difference-is-material',input:{identity,producerId:'sara',reviewerId:null,sections:[{id:'risk',en:'3 findings',esMx:'5 hallazgos'}],proofIds:[]},check:r=>out(r).status==='MATERIAL_DISCREPANCY_DETECTED'},{name:'matching-numbers-not-semantic-proof',input:{identity,producerId:'sara',reviewerId:null,sections:[{id:'risk',en:'3 findings',esMx:'3 hallazgos'}],proofIds:[]},check:r=>out(r).semanticEquivalenceProven===false}]},
 'nico-approval-provenance-verifier':{description:'Validate approval against exact report identity with independent human review/QC, or separately authorized automated technical disclosure; never synthesize approval.',execute:approval,cases:[{name:'no-approval-invented',input:emptyApproval,check:r=>out(r).status==='INCOMPLETE_EVIDENCE'&&out(r).approvalSynthesized===false},{name:'automated-mode-needs-existing-policy-proof',input:{...emptyApproval,mode:'AUTOMATED_TECHNICAL'},check:r=>out(r).humanReviewed===false&&out(r).status==='INCOMPLETE_EVIDENCE'}]},
 'nico-delivery-readiness-gate':{description:'Check protected delivery prerequisites under the correct existing human or automated workflow; a readiness result grants no delivery authority.',execute:delivery,cases:[{name:'missing-protected-delivery-evidence-stops',input:{identity,mode:'HUMAN_REVIEWED',scannerInput:emptyScanners,approval:emptyApproval,artifactDigest:'d'.repeat(64),bilingualContentDigest:'e'.repeat(64),proofIds:[]},check:r=>out(r).status==='INCOMPLETE_EVIDENCE'&&out(r).deliveryExecuted===false}]},
 'nico-production-proof-runner':{description:'Perform one actual bounded existing-adapter GET and bind observed run/report identity to explicit release metadata from that same response; isolation never becomes production.',execute:productionProof,externalRead:true,cases:[{name:'unconfigured-observer-denies-without-network',input:{identity,expectedDeploymentSha:null,expectedDeploymentId:null},check:r=>out(r).status==='BLOCKED'&&out(r).readRequests===0}]},
 'nico-client-status-compiler':{description:'Draft customer-safe workflow status using exact verified facts and automated technical disclosure without exposing protected internals or transmitting.',execute:clientStatus,draft:true,cases:[{name:'no-proof-no-invented-status',input:{identity,mode:'HUMAN_REVIEWED',proofIds:[]},check:r=>out(r).status==='UNKNOWN'&&out(r).transmissionAuthorized===false}]},
};
export const nicoDefinitions:readonly CapabilityDefinition[]=Object.entries(entries).map(([id,e])=>({id,ownerOnly:e.externalRead===true,version:'1.0.0',description:e.description,inputSchema:schemas[id]!.input,outputSchema:schemas[id]!.output,effect:e.externalRead?'READ_ONLY':e.draft?'DRAFT_ONLY':'PURE',authorityClass:e.draft?'DRAFT_ONLY':'READ_ONLY',resources:['supplied-input','actor-visible-kernel-evidence-receipts',...(e.externalRead?['configured-NicoOperator.getRun']:[])],sourceFiles:['nico/contracts.ts','nico/common.ts','nico/definitions.ts','nico/implementations.ts','nico/observer.ts','../nico-operator.ts','../nico-automated-package-verifier.ts','engineering/common.ts','evidence.ts'],qualificationRequirements:['strict-contract','exact-source-and-revision','independent-review-provenance','automated-disclosure-preserved','no-consequential-nico-endpoint','frozen-adversarial-cases','actual-isolated-http-reader','production-provenance-separation'],execute:e.execute,cases:e.cases}));
