import { createHash } from 'node:crypto';
import { verifyProductionNicoPackage } from '../../nico-automated-package-verifier.ts';
import { CapabilityInputError } from '../schema.ts';
import type { ExecutionContext,ExecutionOutput } from '../types.ts';
import { data,rows,strings,digest,unique,requireUnique,suppliedAnalysis,type Data } from '../engineering/common.ts';
import { proof,humanProof,independentActor } from './common.ts';
export function scanners(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),items=rows(input.scanners!);requireUnique(items,'id');const inventoryDigest=digest(items.map(s=>({id:s.id,applicability:s.applicability})).sort((a,b)=>String(a.id).localeCompare(String(b.id))));
 const inventoryVerified=Boolean(proof(ctx,strings(input.inventoryProofIds!),identity,'nico-scanner-inventory',{scannerInventoryDigest:inventoryDigest}));
 const result=items.map(s=>{const claim=s.applicability==='APPLICABLE'?'nico-scanner-executed':'nico-scanner-inapplicability';const verified=s.applicability!=='UNKNOWN'&&proof(ctx,strings(s.proofIds!),identity,claim,{scannerId:String(s.id)});return{id:s.id!,state:s.applicability==='UNKNOWN'?'UNKNOWN_APPLICABILITY':verified?(s.applicability==='APPLICABLE'?'EXECUTION_VERIFIED':'INAPPLICABILITY_VERIFIED'):'MISSING_EVIDENCE'};});
 return suppliedAnalysis({status:inventoryVerified&&items.length&&result.every(r=>r.state==='EXECUTION_VERIFIED'||r.state==='INAPPLICABILITY_VERIFIED')?'COMPLETE':'INCOMPLETE_EVIDENCE',scanners:result,inventoryVerified,sourceDigest:digest(input)},['Scanner requirements come from an exact trusted inventory; missing evidence never means not applicable.']);
}
export function health(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),stages=rows(input.stages!);requireUnique(stages,'id');const map=new Map(stages.map(s=>[String(s.id),s]));const complete=new Set(stages.filter(s=>s.status==='COMPLETE'&&proof(ctx,strings(s.proofIds!),identity,'nico-stage-completed',{stageId:String(s.id)})).map(s=>String(s.id)));
 const failed=stages.filter(s=>s.status==='FAILED'||s.status==='BLOCKED');const primary=failed.filter(s=>!strings(s.dependsOn!).some(id=>['FAILED','BLOCKED'].includes(String(map.get(id)?.status)))).map(s=>String(s.id));const cascade=failed.filter(s=>!primary.includes(String(s.id))).map(s=>String(s.id));
 const missing=unique(stages.flatMap(s=>strings(s.dependsOn!).filter(id=>!map.has(id))));const unverified=stages.filter(s=>s.status==='COMPLETE'&&!complete.has(String(s.id))).map(s=>String(s.id));const ready=stages.filter(s=>s.status==='PENDING'&&strings(s.dependsOn!).every(id=>complete.has(id))).map(s=>String(s.id));
 const cycleIds=new Set<string>();const visited=new Set<string>();function walk(id:string,path:string[]):void{if(path.includes(id)){for(const item of path.slice(path.indexOf(id)))cycleIds.add(item);return;}if(visited.has(id))return;for(const dependency of strings(map.get(id)?.dependsOn??[]))if(map.has(dependency))walk(dependency,[...path,id]);visited.add(id);}for(const s of stages)walk(String(s.id),[]);
 const runComplete=stages.length>0&&cycleIds.size===0&&complete.size===stages.length&&Boolean(proof(ctx,strings(input.proofIds!),identity,'nico-run-completed'));
 return suppliedAnalysis({status:failed.length||cycleIds.size?'BLOCKED':missing.length||unverified.length||!stages.length?'INCOMPLETE_EVIDENCE':'HEALTHY_PROGRESS',primaryFailureIds:primary,cascadeIds:cascade,readyStageIds:ready,unverifiedCompleteIds:unverified,missingDependencies:missing,cycleStageIds:[...cycleIds].sort(),runComplete,nextAction:cycleIds.size?'Resolve the cyclic stage dependencies without advancing the run.':primary.length?`Inspect the earliest failed dependency stage ${primary[0]}.`:missing.length?'Read missing stage dependency records.':unverified.length?'Collect exact stage completion evidence.':ready.length?`A separately authorized continuation can consider stage ${ready[0]}.`:'Inspect current run status; no unverified completion is inferred.',sourceDigest:digest(input)},['A dependency ordering suggests fault domains; it does not prove causation. No run is continued by this analysis.']);
}
export function queue(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),items=rows(input.candidates!);requireUnique(items,'id');const severity=['CRITICAL','HIGH','MEDIUM','LOW','INFORMATIONAL'];const done=new Set(items.filter(c=>{const e=proof(ctx,strings(c.proofIds!),identity,'nico-specialist-disposition',{candidateId:String(c.id),actorKind:'HUMAN'});return e&&typeof e.subject.producerId==='string'&&independentActor(e.subject.actorId,e.subject.producerId);}).map(c=>String(c.id)));
 const result=items.map(c=>({id:c.id!,disposition:done.has(String(c.id))?'DISPOSITION_VERIFIED':c.requiresHuman?'SPECIALIST_REVIEW_REQUIRED':proof(ctx,strings(c.proofIds!),identity,'nico-human-review-not-required',{candidateId:String(c.id)})?'AUTOMATED_TRIAGE_VERIFIED':'REQUIREMENT_UNKNOWN',blockedBy:strings(c.dependencies!).filter(id=>!done.has(id)),priority:severity.indexOf(String(c.severity)),age:Number(c.ageHours)})).sort((a,b)=>a.priority-b.priority||a.blockedBy.length-b.blockedBy.length||b.age-a.age||String(a.id).localeCompare(String(b.id)));
 return suppliedAnalysis({queue:result.map(({age,...r})=>r),impersonatedSpecialist:false,sourceDigest:digest(input)},['Queue priority is advisory. Automated non-actionable dispositions require authoritative applicability proof and never impersonate a specialist.']);
}
export function approval(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),ids=strings(input.proofIds!),reasons:string[]=[];let human=false,qc=false,verified=false;
 if(input.mode==='AUTOMATED_TECHNICAL'){verified=Boolean(proof(ctx,ids,identity,'nico-automated-policy-authorization',{humanReviewed:false,securityCertification:false,automatedDisclosure:true}));if(!verified)reasons.push('Exact separately authorized automated-policy provenance and disclosure are required.');}
 else{human=humanProof(ctx,ids,identity,'nico-specialist-review',input.reviewerId,input.producerId);qc=humanProof(ctx,ids,identity,'nico-independent-qc',input.qcActorId,input.producerId)&&input.qcActorId!==input.reviewerId;const approved=humanProof(ctx,ids,identity,'nico-human-approval',input.approverId,input.producerId);if(!human)reasons.push('Exact independent specialist review is missing.');if(!qc)reasons.push('Independent QC from a separate actor is missing.');if(!approved)reasons.push('Exact human approval provenance is missing.');verified=human&&qc&&approved;}
 return suppliedAnalysis({status:verified?(input.mode==='AUTOMATED_TECHNICAL'?'VERIFIED_AUTOMATED_AUTHORIZATION':'VERIFIED_HUMAN_APPROVAL'):'INCOMPLETE_EVIDENCE',humanReviewed:human,independentQcVerified:qc,approvalSynthesized:false,reasons,executionAuthorized:false});
}
export function readiness(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),ids=strings(input.proofIds!),missing:string[]=[];if(digest(data(input.scannerInput!).identity)!==digest(identity))throw new CapabilityInputError('NICO_SCANNER_SUBJECT_MISMATCH');const scan=data(scanners(data(input.scannerInput!),ctx).output);const source=Boolean(proof(ctx,ids,identity,'nico-source-immutable'));if(!source)missing.push('Exact immutable source proof.');if(scan.status!=='COMPLETE')missing.push('Applicable scanner inventory and execution evidence.');if(!proof(ctx,ids,identity,'nico-canonical-report'))missing.push('Exact canonical report identity.');
 if(input.mode==='AUTOMATED_TECHNICAL')return suppliedAnalysis({status:missing.length?'INCOMPLETE_EVIDENCE':'AUTOMATED_TECHNICAL_BOUNDARY',missingRequirements:missing,sourceVerified:source,scannersComplete:scan.status==='COMPLETE',independentQcVerified:false,humanReviewCompleted:false,approvalGranted:false},['Automated technical output remains subject to the existing automated policy/package gate; no human review is invented.']);
 const required=strings(input.requiredHumanCandidateIds!),pending=strings(input.pendingCandidateIds!);if(new Set(required).size!==required.length||new Set(pending).size!==pending.length)throw new CapabilityInputError('DUPLICATE_CANDIDATE');if(pending.some(id=>!required.includes(id)))throw new CapabilityInputError('UNKNOWN_PENDING_CANDIDATE');
 const inventory=proof(ctx,ids,identity,'nico-required-human-review-inventory',{candidateInventoryDigest:digest(required.slice().sort())});if(!inventory)missing.push('Exact required specialist candidate inventory.');const reviewed=humanProof(ctx,ids,identity,'nico-specialist-review',input.specialistId,input.producerId)&&pending.length===0&&Boolean(inventory);const qc=humanProof(ctx,ids,identity,'nico-independent-qc',input.qcActorId,input.producerId)&&input.qcActorId!==input.specialistId;
 return suppliedAnalysis({status:missing.length?'INCOMPLETE_EVIDENCE':reviewed&&qc?'READY_FOR_FINAL_APPROVAL':'READY_FOR_SPECIALIST_REVIEW',missingRequirements:[...missing,...(!reviewed?['Independent specialist dispositions.']:[]),...(!qc?['Independent quality control.']:[])],sourceVerified:source,scannersComplete:scan.status==='COMPLETE',independentQcVerified:qc,humanReviewCompleted:reviewed,approvalGranted:false});
}
function decodeBase64(raw:string):Uint8Array {if(raw.length%4||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(raw))throw new CapabilityInputError('NICO_CANONICAL_BASE64_REQUIRED');const bytes=Buffer.from(raw,'base64');if(bytes.toString('base64')!==raw)throw new CapabilityInputError('NICO_CANONICAL_BASE64_REQUIRED');return bytes;}
export function exportsIntegrity(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),bytes=decodeBase64(String(input.contentBase64));const actualDigest=createHash('sha256').update(bytes).digest('hex');const ids=strings(input.proofIds!),reasons:string[]=[];const canonical=Boolean(proof(ctx,ids,identity,input.mode==='AUTOMATED_TECHNICAL'?'nico-automated-export-canonical':'nico-approved-export-canonical',{artifactName:String(input.artifactName),artifactDigest:actualDigest}));if(!bytes.length)reasons.push('Empty artifact.');if(actualDigest!==input.expectedDigest)reasons.push('Artifact bytes do not match the expected hash.');if(!canonical)reasons.push('Exact canonical export binding is not proven.');let automated=false;
 if(input.mode==='AUTOMATED_TECHNICAL'){if(!input.artifactIdentity)reasons.push('Existing NICO automated package identity is required.');else{const ai=data(input.artifactIdentity);const digestEntries=rows(ai.artifact_digests!);requireUnique(digestEntries,'name');if(ai.run_id!==identity.runId||ai.revision!==identity.revision||ai.report_artifact_digest!==identity.reportDigest)reasons.push('Automated package report identity mismatch.');else try{verifyProductionNicoPackage({body:bytes,contentType:'application/zip',digest:actualDigest},{runId:String(identity.runId),repositoryUrl:`https://github.com/${String(identity.repository)}`,commitSha:String(identity.commitSha),artifactIdentity:{schema:String(ai.schema),run_id:String(ai.run_id),revision:Number(ai.revision),report_artifact_digest:String(ai.report_artifact_digest),artifact_digests:Object.fromEntries(digestEntries.map(e=>[String(e.name),String(e.digest)]))}});automated=true;}catch{reasons.push('Existing NICO automated ZIP verifier rejected the package.');}}}
 return suppliedAnalysis({status:reasons.length?(bytes.length&&actualDigest===input.expectedDigest?'INCOMPLETE_EVIDENCE':'BLOCKED'):'INTEGRITY_VERIFIED',actualDigest,bytes:bytes.length,canonicalBindingVerified:canonical,automatedPackageVerified:automated,humanReviewed:false,deliveryAuthorized:false,reasons},['Byte integrity and canonical binding do not transmit an artifact or independently grant delivery authority.']);
}
function markers(text:string):string[]{return unique((text.match(/\bCVE-\d{4}-\d+\b|https?:\/\/[^\s)]+|\b\d+(?:[.,]\d+)*%?\b/gi)??[]).map(x=>x.toLowerCase().replace(/,/g,'.')));}
function severities(text:string):string[]{const map:Record<string,string>={critical:'critical',critico:'critical',critica:'critical',high:'high',alto:'high',alta:'high',medium:'medium',medio:'medium',media:'medium',low:'low',bajo:'low',baja:'low'};return unique((text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().match(/\b(?:critical|critico|critica|high|alto|alta|medium|medio|media|low|bajo|baja)\b/g)??[]).map(w=>map[w]!));}
export function bilingual(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),sections=rows(input.sections!);requireUnique(sections,'id');const differences:Data[]=[];
 for(const s of sections){const en=String(s.en),es=String(s.esMx),base={sectionId:s.id!,enDigest:digest(en),esMxDigest:digest(es)};if(digest(markers(en))!==digest(markers(es)))differences.push({...base,kind:'NUMERIC_OR_IDENTIFIER'});if(digest(severities(en))!==digest(severities(es)))differences.push({...base,kind:'SEVERITY'});const enNeg=/\b(?:not|no|never|without)\b/i.test(en),esNeg=/\b(?:no|nunca|sin|ning[uú]n[ao]?)\b/i.test(es);if(enNeg!==esNeg)differences.push({...base,kind:'NEGATION'});}
 const contentDigest=digest(sections);const verified=sections.length>0&&differences.length===0&&humanProof(ctx,strings(input.proofIds!),identity,'nico-bilingual-semantic-equivalence',input.reviewerId,input.producerId,{bilingualContentDigest:contentDigest});
 return suppliedAnalysis({status:differences.length?'MATERIAL_DISCREPANCY_DETECTED':verified?'VERIFIED_EQUIVALENCE':'INDEPENDENT_SEMANTIC_REVIEW_REQUIRED',discrepancies:differences,contentDigest,semanticEquivalenceProven:verified,linguisticDifferencesAllowed:true},['Deterministic numeric, identifier, severity and negation screening is incomplete semantic analysis. Legitimate linguistic differences are allowed; flagged discrepancies require review and do not prove mistranslation.']);
}
export function delivery(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),ids=strings(input.proofIds!),missing:string[]=[];const a=data(input.approval!),s=data(input.scannerInput!);if(digest(a.identity)!==digest(identity)||digest(s.identity)!==digest(identity)||a.mode!==input.mode)throw new CapabilityInputError('NICO_DELIVERY_SUBJECT_MISMATCH');const approved=data(approval(a,ctx).output),scan=data(scanners(s,ctx).output);
 if(!proof(ctx,ids,identity,'nico-source-immutable'))missing.push('Exact immutable source.');if(scan.status!=='COMPLETE')missing.push('Complete applicable scanner evidence.');if(!String(approved.status).startsWith('VERIFIED_'))missing.push('Exact workflow-specific approval or automated authorization.');
 if(!proof(ctx,ids,identity,'nico-export-integrity',{artifactDigest:String(input.artifactDigest)}))missing.push('Exact package integrity.');if(!proof(ctx,ids,identity,'nico-bilingual-equivalence',{bilingualContentDigest:String(input.bilingualContentDigest)}))missing.push('Bilingual integrity.');if(!proof(ctx,ids,identity,'nico-protected-delivery-access'))missing.push('Protected authenticated delivery channel.');if(!proof(ctx,ids,identity,'nico-delivery-authorized',{artifactDigest:String(input.artifactDigest),mode:String(input.mode)}))missing.push('Existing exact delivery authorization.');
 return suppliedAnalysis({status:missing.length?'INCOMPLETE_EVIDENCE':'READY_UNDER_EXISTING_DELIVERY_AUTHORITY',missingRequirements:missing,humanReviewed:approved.humanReviewed!,technicalOnly:input.mode==='AUTOMATED_TECHNICAL',deliveryExecuted:false,deliveryAuthorityGranted:false},['This gate does not invoke the protected delivery endpoint. The existing executor must independently recheck exact authority at execution.']);
}
export function clientStatus(input:Data,ctx:ExecutionContext):ExecutionOutput {
 const identity=data(input.identity!),ids=strings(input.proofIds!);let status='UNKNOWN',message='Current assessment status needs verified workflow evidence.',human:boolean|null=null;
 if(proof(ctx,ids,identity,'nico-run-started')){status='ASSESSMENT_IN_PROGRESS';message='The assessment is in progress.';}
 if(proof(ctx,ids,identity,'nico-specialist-review-pending')){status='SPECIALIST_REVIEW_PENDING';message='Specialist review is pending.';}
 const humanApproval=proof(ctx,ids,identity,'nico-human-approval',{actorKind:'HUMAN'});if(input.mode==='HUMAN_REVIEWED'&&humanApproval&&typeof humanApproval.subject.producerId==='string'&&independentActor(humanApproval.subject.actorId,humanApproval.subject.producerId)){status='APPROVED_AWAITING_DELIVERY';message='The reviewed revision is approved; protected delivery remains a separate step.';human=true;}
 if(input.mode==='AUTOMATED_TECHNICAL'&&proof(ctx,ids,identity,'nico-automated-policy-authorization',{humanReviewed:false,securityCertification:false,automatedDisclosure:true})){status='AUTOMATED_TECHNICAL_PACKAGE_READY';message='An authorized automated technical assessment is ready. It has not been human reviewed and is not a security certification.';human=false;}
 if(proof(ctx,ids,identity,'nico-delivery-completed',{mode:String(input.mode)})){status='DELIVERY_VERIFIED';message=input.mode==='AUTOMATED_TECHNICAL'?'Protected delivery of the automated technical assessment is verified. It was not human reviewed and is not a security certification.':'Protected delivery of the exact assessment revision is verified.';if(input.mode==='AUTOMATED_TECHNICAL')human=false;}
 return suppliedAnalysis({status,message,humanReviewed:human,securityCertificationClaimed:false,protectedInternalInformationIncluded:false,transmissionAuthorized:false});
}
