/** Plain owner-facing copy. Never reflects arbitrary provider fields or claims an error was free. */
export function jevOwnerMessage(value:unknown):string {
 const result=value&&typeof value==='object'?value as Record<string,unknown>:{};
 const local='Local search and source access remain available.';
 if(result.mode==='local_search') {
  const reasons:Record<string,string>={
   disabled:'Jev is switched off.',missing_key:'Jev needs its secure server-side key.',
   budget_denied:'No usable approved allowance is available for this Jev request.',
   query_not_approved:'Approve sharing this public query before using Jev.',
   no_authorized_candidates:'No current public records are eligible for Jev.',
   busy:'Another Jev request is already running.',cancelled:'The Jev request was cancelled.',
   timeout:'Jev did not return a result before the deadline.',rate_limited:'The provider is temporarily limiting requests.',
   malformed:'The provider response could not be validated.',access_denied:'Access changed; the Jev result was withheld.',
  };
  const reason=typeof result.reason==='string'?result.reason:'';
  return (Object.hasOwn(reasons,reason)?reasons[reason]:'A usable Jev result is unavailable.')+' '+local;
 }
 if(result.mode!=='live_shadow'&&result.mode!=='simulated_shadow')return 'Jev result unavailable. '+local;
 if(result.mode==='live_shadow'&&result.live!==true)return 'Jev result unavailable. '+local;
 const origin=result.mode==='simulated_shadow'?'Simulated test result.':result.cached===true?
  'Reused an earlier live result; no new provider call.':'A live Jev call returned a result.';
 const decision=result.reason==='uncertain_shadow'?'Jev could not choose a sufficiently relevant record.':
  result.reason==='ambiguous_shadow'?'The leading relevance scores are too close to choose one record.':
  'Jev produced suggestions for review.';
 return origin+' '+decision+' These suggestions are not yet qualified for use. Your search order is unchanged; source evidence remains the basis for project status.';
}

/** Composes into the existing owner dashboard; keeps its authentication and legacy controls. */
export function secondBrainWorkspace(html:string):string {
 const panel=String.raw`<section id="second-brain" aria-labelledby="brain-title">
 <p>PROJECT MEMORY / OWNER WORKSPACE</p><h1 id="brain-title">SARA second brain</h1>
 <p>Capture what matters. Check the source. Continue with evidence.</p>
 <p id="brain-mode">Local search · Jev disabled · no provider spending authorized</p>
 <p id="brain-status" role="status" aria-live="polite">Use Owner access to unlock your project memory.</p>
 <fieldset id="brain-fields" disabled>
 <label for="brain-project">Project</label><select id="brain-project"><option value="nico">NICO</option><option value="sara">SARA</option><option value="nicos-world">Nico’s World</option></select>
 <form id="brain-capture"><label for="brain-note">Capture a note</label><textarea id="brain-note" maxlength="8000" required placeholder="A decision, blocker, goal, or next step. Never paste credentials."></textarea>
 <label for="brain-kind">Note category</label><select id="brain-kind"><option value="note">Note</option><option value="goal">Goal</option><option value="decision">Decision</option><option value="blocker">Blocker</option><option value="constraint">Constraint</option><option value="next_action">Proposed next action</option><option value="approval">Pending approval</option></select>
 <label for="brain-source">Source link (optional; saving does not fetch it)</label><input id="brain-source" type="url" placeholder="https://github.com/…">
 <label for="brain-observed">Observed at (optional, UTC)</label><input id="brain-observed" type="text" placeholder="2026-09-26T12:00:00Z">
 <label for="brain-related">Link this note to evidence (optional; shown records only)</label><select id="brain-related"><option value="">No related record</option></select>
 <label for="brain-relation">Relationship</label><select id="brain-relation"><option value="relatedTo">Related evidence</option><option value="conflictsWith">Conflicts with this record</option><option value="supersedes">Corrects / replaces this record</option></select>
 <p>Corrections preserve history and require an Observed at time newer than the original. A related note does not resolve a blocker or grant approval.</p>
 <button type="submit">Save note</button></form>
 <details id="brain-report-panel"><summary>Report findings and repair preparation</summary>
 <p>Paste one approved NICO or other project report excerpt. This saves a private reported claim; it does not fetch the source, parse a PDF, verify a finding or execute a repair. Never include credentials.</p>
 <form id="brain-report-capture">
 <label for="brain-report-title">Finding title</label><input id="brain-report-title" required maxlength="200">
 <label for="brain-report-source">Report source link (HTTPS, no query or fragment)</label><input id="brain-report-source" type="url" required maxlength="2048">
 <label for="brain-report-text">Exact approved finding excerpt</label><textarea id="brain-report-text" required maxlength="8000"></textarea>
 <details><summary>Source identity and repair criteria (optional)</summary>
 <label for="brain-report-reportId">Report / assessment run ID</label><input id="brain-report-reportId" maxlength="200">
 <label for="brain-report-findingId">Finding ID</label><input id="brain-report-findingId" maxlength="200">
 <label for="brain-report-repository">Assessed repository (owner/name)</label><input id="brain-report-repository" maxlength="201">
 <label for="brain-report-revision">Assessed commit (full 40-character SHA)</label><input id="brain-report-revision" maxlength="40">
 <label for="brain-report-observedAt">Report observation time (UTC)</label><input id="brain-report-observedAt" placeholder="2026-09-27T12:00:00Z">
 <label for="brain-report-reproduction">Reported reproduction steps</label><textarea id="brain-report-reproduction" maxlength="2000"></textarea>
 <label for="brain-report-acceptance">Proposed acceptance criteria</label><textarea id="brain-report-acceptance" maxlength="2000"></textarea>
 <label for="brain-report-limitations">Reported limitations</label><textarea id="brain-report-limitations" maxlength="2000"></textarea>
 <label for="brain-report-related">Related evidence (optional)</label><select id="brain-report-related"><option value="">No related record</option></select>
 <label for="brain-report-relation">Relationship</label><select id="brain-report-relation"><option value="relatedTo">Related evidence</option><option value="conflictsWith">Conflicts with this record</option><option value="supersedes">Corrects / replaces this record</option></select>
 <p>Corrections preserve history and require a newer known observation time. Missing identifiers remain unknown.</p></details>
 <button type="submit">Save report finding</button></form>
 <div id="brain-report-work"></div><label for="brain-repair-brief">Selected repair preparation brief</label><textarea id="brain-repair-brief" readonly rows="12"></textarea>
 <button type="button" id="brain-repair-copy" disabled>Copy repair brief</button> <button type="button" id="brain-repair-export" disabled>Export repair brief</button></details>
 <form id="brain-search"><label for="brain-question">Find evidence or ask about project state</label><input id="brain-question" maxlength="300" type="search" placeholder="What blocks compiler qualification?"><button type="submit">Search and build brief</button></form>
 <div aria-label="Quick project questions"><button type="button" data-brain-question="What was decided?">Decisions</button> <button type="button" data-brain-question="What is blocked?">Blockers</button> <button type="button" data-brain-question="What is next?">Next steps</button> <button type="button" data-brain-question="What needs approval?">Pending approvals</button></div>
 <h2 id="brain-answer-title" tabindex="-1">Question answer</h2><p>Choose a quick question, or search for words in your evidence.</p><div id="brain-answer" aria-live="polite"></div>
 <details><summary>Ask SARA about saved evidence</summary>
 <p>Preview a specific question and up to two short source excerpts. Each question stands alone. AI analysis may be wrong; check the sources. No actions are executed.</p>
 <form id="brain-ask-form"><label for="brain-ask-query">Your project question</label><input id="brain-ask-query" required maxlength="300" placeholder="What does the compiler finding tell us?">
 <label><input id="brain-ask-private" type="checkbox">Include private saved records in the preview</label><button type="submit">Preview AI context</button></form>
 <pre id="brain-ask-preview"></pre><label><input id="brain-ask-consent" type="checkbox">I approve sending this exact question and the displayed excerpts to OpenAI for analysis.</label>
 <button id="brain-ask-send" type="button" disabled>Ask SARA with this context</button><div id="brain-ask-answer" aria-live="polite"></div></details>
 <details><summary>Keep GitHub evidence current</summary><p>Checks the latest default-branch commit, most recently updated PR and newest workflow run for this project. This is a partial snapshot, not a complete repository or deployment check.</p>
 <button id="brain-refresh-now" type="button">Refresh GitHub now</button><label><input id="brain-refresh-auto" type="checkbox">Refresh every 15 minutes while this project is open</label>
 <p id="brain-refresh-status">Automatic refresh is off. Closing the page, switching projects or disconnecting stops it.</p></details>
 <details><summary>Import public GitHub evidence</summary><p>Read-only, owner-triggered. The selected project determines the repository. No private GitHub access is inherited from this chat.</p>
 <form id="brain-import"><label for="brain-import-kind">Evidence type</label><select id="brain-import-kind"><option value="commit">Commit</option><option value="pull_request">Pull request</option><option value="workflow_run">Workflow run</option></select>
 <label for="brain-import-id">Full commit SHA or numeric PR/run ID</label><input id="brain-import-id" required maxlength="40"><label for="brain-attempt">Run attempt (workflow only)</label><input id="brain-attempt" type="number" min="1" max="10000"><button type="submit">Fetch public evidence</button></form></details>
 <details id="brain-bounty-panel" hidden><summary>Software bounty workbench</summary>
 <p>Evaluate one posted coding task before committing work. Read-only review; no worker, account, claim, submission or payment is started. Source text and advertised rewards are unverified claims.</p>
 <form id="brain-bounty-import"><label for="brain-bounty-url">Public GitHub issue URL</label><input id="brain-bounty-url" type="url" required maxlength="512" placeholder="https://github.com/owner/repository/issues/123"><button type="submit">Import task for review</button></form>
 <button id="brain-bounty-load" type="button">Review saved tasks</button><div id="brain-bounties" aria-live="polite"></div>
 <label for="brain-bounty-brief">Selected task work brief</label><textarea id="brain-bounty-brief" readonly rows="12"></textarea><button id="brain-bounty-copy" type="button" disabled>Copy task brief</button>
 </details>
 <details><summary>Jev connection and existing allowance</summary>
 <p>Jev uses only public source records and a query you approve. Suggestions remain in shadow until qualified; ordinary search stays available.</p>
 <button id="brain-budget-review" type="button">Review unused job allowance</button><pre id="brain-budget"></pre><button id="brain-budget-approve" type="button" disabled>Reallocate reviewed unused allowance</button>
 <p>Provider setup: OpenRouter uses OPENROUTER_API_KEY with SARA_JEV_PROVIDER=openrouter in SARA’s server environment. Direct TypeSafe uses TYPESAFE_API_KEY with SARA_JEV_PROVIDER=typesafe. A key alone does not authorize spending. Never paste it into a note.</p>
 <label><input id="brain-query-public" type="checkbox">I approve sending this search query and matching public project evidence to the selected provider route shown above (OpenRouter forwards it to TypeSafe).</label>
 <button id="brain-jev" type="button">Evaluate with Jev</button><pre id="brain-jev-result" role="status" aria-live="polite"></pre>
 <details><summary>Experimental match details</summary><p>Scores are uncalibrated suggestions, not verified facts. Match record IDs to Sources below.</p><pre id="brain-jev-details"></pre></details></details>
 <h2>Project overview</h2><p>Reported decisions, blockers and proposals. Search does not hide this overview; no card grants permission or independently verifies a claim.</p><div id="brain-tracking"></div>
 <details id="brain-change-panel"><summary>What changed</summary><form id="brain-changes-form"><label for="brain-since">Records saved since (UTC)</label><input id="brain-since" type="text" placeholder="2026-09-26T12:00:00Z"><button id="brain-last-day" type="button">Use last 24 hours</button><button type="submit">Show saved records</button></form><div id="brain-changes">Choose a starting time. No previous-session time is assumed.</div></details>
 <h2>Current brief</h2><textarea id="brain-handoff" readonly rows="14" aria-label="Continuation brief"></textarea>
 <button id="brain-copy" type="button">Copy handoff</button> <button id="brain-export" type="button">Export handoff</button>
 <h2>Sources and freshness</h2><div id="brain-sources"></div>
 <details><summary>History and conflicts</summary><pre id="brain-history"></pre></details>
 <details><summary>Existing obligations and runtime</summary><pre id="brain-obligations">Load after authentication.</pre></details>
 </fieldset></section><details id="brain-legacy"><summary>Legacy operations, audit and protected controls</summary>`;
 const css=String.raw`<style>
 #second-brain{max-width:960px;margin:30px auto;padding:24px;border:1px solid #45e9ff66;border-radius:16px;background:#07101e;color:#eefbff;overflow-wrap:anywhere}
 #second-brain h1{font-size:clamp(30px,6vw,52px);line-height:1.1;margin:12px 0} #second-brain h2{font-size:22px;margin:22px 0 12px}
 #second-brain fieldset{border:0;padding:0;min-width:0}#second-brain form{margin:18px 0;padding:16px;border:1px solid #8da9bc55;border-radius:10px}
 #second-brain label{display:block;margin:12px 0 6px}#second-brain input,#second-brain textarea,#second-brain select{box-sizing:border-box;display:block;width:100%;max-width:100%;font:inherit;font-size:16px;padding:12px;background:#101c2d;color:#eefbff;border:1px solid #8da9bc;border-radius:6px}
 #second-brain textarea{resize:vertical;min-height:110px}#second-brain button{min-height:44px;margin-top:12px;padding:10px 16px;white-space:normal}#second-brain summary,#brain-legacy>summary{cursor:pointer;min-height:44px;padding:12px}
 #second-brain pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px}#second-brain a{color:#45e9ff}#second-brain details{margin-top:12px}#brain-legacy{margin:20px 0}
 @media(max-width:600px){#second-brain{margin:12px 0;padding:14px}#second-brain form{padding:10px}#second-brain button{width:100%}}
 </style>`;
 const script=String.raw`<script>
 (()=>{const jevMessage=${jevOwnerMessage.toString()};const el=id=>document.getElementById(id);let epoch=0;let allocation=null;let shown=new Map();let questionPreview=null;let autoTimer=null;let updating=false;let autoGeneration=0;
 const status=text=>{el('brain-status').textContent=text;};
 const reportFields=['title','source','text','reportId','findingId','repository','revision','observedAt','reproduction','acceptance','limitations'];
 const clearReport=()=>{for(const key of reportFields)el('brain-report-'+key).value='';el('brain-report-related').replaceChildren(new Option('No related record',''));el('brain-report-relation').value='relatedTo';el('brain-report-work').replaceChildren();el('brain-repair-brief').value='';el('brain-repair-copy').disabled=true;el('brain-repair-export').disabled=true;};
 const stopUpdates=()=>{autoGeneration++;if(autoTimer!==null)clearTimeout(autoTimer);autoTimer=null;el('brain-refresh-auto').checked=false;};
 const clearQuestion=()=>{questionPreview=null;el('brain-ask-preview').textContent='';el('brain-ask-answer').replaceChildren();el('brain-ask-consent').checked=false;el('brain-ask-send').disabled=true;};
 const clear=()=>{epoch++;stopUpdates();clearQuestion();el('brain-ask-query').value='';el('brain-ask-private').checked=false;el('brain-refresh-status').textContent='Automatic refresh is off.';clearReport();shown.clear();el('brain-bounties').replaceChildren();el('brain-bounty-url').value='';el('brain-bounty-brief').value='';el('brain-bounty-copy').disabled=true;el('brain-bounty-panel').hidden=el('brain-project').value!=='sara';el('brain-answer').replaceChildren();el('brain-mode').textContent='Provider status unavailable until authenticated refresh.';el('brain-tracking').replaceChildren();el('brain-changes').textContent='Choose a starting time. No previous-session time is assumed.';el('brain-since').value='';el('brain-question').value='';el('brain-import-id').value='';el('brain-attempt').value='';el('brain-related').replaceChildren(new Option('No related record',''));el('brain-relation').value='relatedTo';el('brain-note').value='';el('brain-source').value='';el('brain-observed').value='';el('brain-handoff').value='';el('brain-sources').replaceChildren();el('brain-history').textContent='';el('brain-obligations').textContent='';el('brain-jev-result').textContent='';el('brain-jev-details').textContent='';el('brain-budget').textContent='';el('brain-query-public').checked=false;allocation=null;el('brain-budget-approve').disabled=true;};
 async function api(path,body){const headers={Authorization:'Bearer '+(sessionStorage.getItem('sara-owner-token')||'')};if(body)headers['content-type']='application/json';const r=await fetch(path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});if(!r.ok){if(r.status===401){clear();el('brain-fields').disabled=true;}throw new Error(r.status===401?'Owner authentication required.':'Request failed; no successful refresh is claimed.');}return r.json();}
 const sourceLink=(container,m)=>{if(m.source.startsWith('https://')){const a=document.createElement('a');a.href=m.source;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Open source';container.append(a);}};
 function cards(container,label,group){const h=document.createElement('h3');h.textContent=label;container.append(h);const count=document.createElement('p');count.textContent=group.total?'Showing '+group.items.length+'/'+group.total+' records'+(group.omitted?' · '+group.omitted+' omitted':''):'Unknown — no current records.';container.append(count);
 for(const m of group.items){const d=document.createElement('details'),summary=document.createElement('summary');summary.textContent=m.state+' · '+m.text.slice(0,95);d.append(summary);const text=document.createElement('p');text.textContent=m.text+(m.excerptTruncated?'… [excerpt]':'');d.append(text);const info=document.createElement('p');info.textContent=m.verification+' · observed '+(m.observedAt||'unknown')+' · checked '+(m.lastVerifiedAt||'not verified')+' · saved '+m.ingestedAt+(m.observedBeforeWindow?' · observation predates this interval':'');d.append(info);const id=document.createElement('p');id.textContent=m.id;d.append(id);sourceLink(d,m);
 for(const r of m.related){const p=document.createElement('p');p.textContent=r.relationship+' · '+r.state+' · '+r.id+' ';sourceLink(p,r);d.append(p);}
 const link=document.createElement('button');link.type='button';link.textContent='Link next note to this record';link.addEventListener('click',()=>{el('brain-related').value=m.id;el('brain-relation').value='relatedTo';el('brain-note').focus();});d.append(link);container.append(d);}}
 function tracking(view){const t=view.tracking;const selected=el('brain-related').value;shown=new Map();for(const group of [t.decisions,t.blockers,t.nextActions,t.pendingApprovals,t.changes])for(const m of group.items)shown.set(m.id,m);for(const m of view.records)if(!shown.has(m.id))shown.set(m.id,{id:m.id,text:m.statement,observedAt:m.projectEvidence.observedAt});
 el('brain-related').replaceChildren(new Option('No related record',''));for(const m of shown.values())el('brain-related').append(new Option(m.text.slice(0,70)+' · '+m.id.slice(-8),m.id));if(shown.has(selected))el('brain-related').value=selected;
 const reportSelected=el('brain-report-related').value;el('brain-report-related').replaceChildren(new Option('No related record',''));for(const m of shown.values())el('brain-report-related').append(new Option(m.text.slice(0,70)+' · '+m.id.slice(-8),m.id));if(shown.has(reportSelected))el('brain-report-related').value=reportSelected;
 el('brain-tracking').replaceChildren();cards(el('brain-tracking'),'Decisions (reported)',t.decisions);cards(el('brain-tracking'),'Blockers (reported; resolution unknown)',t.blockers);cards(el('brain-tracking'),'Proposed next steps (authorization not established)',t.nextActions);cards(el('brain-tracking'),'Pending approvals (not granted)',t.pendingApprovals);
 el('brain-changes').replaceChildren();const p=document.createElement('p');p.textContent=t.changes.since?'Since '+t.changes.since+' · as of '+t.changes.asOf+'. '+t.changes.notice:'Choose a starting time. No previous-session time is assumed.';el('brain-changes').append(p);if(t.changes.since)cards(el('brain-changes'),'Records saved in this interval',t.changes);}
 function answer(value){const container=el('brain-answer');container.replaceChildren();if(!value){container.textContent='Ordinary search. Use a quick question for a source-linked category answer.';return;}const summary=document.createElement('p');summary.textContent=value.title+' · '+value.status+' · as of '+value.asOf;container.append(summary);const notice=document.createElement('p');notice.textContent=value.notice+' Showing '+value.sources.length+'/'+value.total+' sources'+(value.omitted?' · '+value.omitted+' omitted':'')+'.';container.append(notice);
 for(const m of value.sources){const d=document.createElement('details'),label=document.createElement('summary');label.textContent=m.state+' · '+m.excerpt.slice(0,95);d.append(label);const text=document.createElement('p');text.textContent=m.excerpt+(m.excerptTruncated?'… [excerpt]':'');d.append(text);const info=document.createElement('p');info.textContent=m.verification+' · observed '+(m.observedAt||'unknown')+' · checked '+(m.lastVerifiedAt||'not verified');d.append(info);const id=document.createElement('p');id.textContent=m.id;d.append(id);sourceLink(d,m);container.append(d);}}
 function renderReports(work){const container=el('brain-report-work');container.replaceChildren();el('brain-repair-brief').value='';el('brain-repair-copy').disabled=true;el('brain-repair-export').disabled=true;const p=document.createElement('p');p.textContent=work.notice+' Showing '+work.items.length+'/'+work.total+(work.omitted?' · '+work.omitted+' omitted':'')+'.';container.append(p);const ticket=epoch;
 for(const item of work.items){const d=document.createElement('div'),title=document.createElement('p');title.textContent=item.title+' · observed '+(item.observedAt||'unknown');d.append(title);sourceLink(d,item);const b=document.createElement('button');b.type='button';b.textContent='Prepare repair brief';b.addEventListener('click',()=>{if(ticket!==epoch||document.body.dataset.owner!=='connected')return;el('brain-repair-brief').value=item.brief;el('brain-repair-copy').disabled=false;el('brain-repair-export').disabled=false;el('brain-repair-brief').focus();});d.append(b);container.append(d);}}
 async function refresh(){const ticket=++epoch;const project=el('brain-project').value;const [view,data]=await Promise.all([api('/api/second-brain/brief?project='+encodeURIComponent(project)+'&q='+encodeURIComponent(el('brain-question').value)+'&since='+encodeURIComponent(el('brain-since').value)),api('/api/second-brain/status').catch(()=>null)]);if(ticket!==epoch||project!==el('brain-project').value||document.body.dataset.owner!=='connected')return;
 el('brain-mode').textContent=data?data.providerMode:'Provider status unavailable; refresh failed.';el('brain-obligations').textContent=data?JSON.stringify({obligations:data.obligations,recentImports:data.recentImports},null,2):'Runtime refresh failed. Existing obligations have not been changed.';answer(view.answer);
 tracking(view);renderReports(view.reportWork);el('brain-handoff').value=view.handoff;el('brain-sources').replaceChildren();for(const m of view.records){const d=document.createElement('details');const s=document.createElement('summary');s.textContent=m.projectEvidence.verification+' · '+m.statement.slice(0,95);d.append(s);const p=document.createElement('pre');p.textContent=JSON.stringify(m,null,2);d.append(p);if(m.source.startsWith('https://')){const a=document.createElement('a');a.href=m.source;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Open source';d.append(a);}el('brain-sources').append(d);}
 el('brain-history').textContent=JSON.stringify({conflicts:view.conflicts,history:view.history},null,2);status('As of '+view.asOf+' · '+view.totalRecords+' records · '+view.conflicts.length+' conflicting records. Local deterministic search; unknowns remain unknown.');}
 const run=fn=>async e=>{if(e)e.preventDefault();try{await fn();}catch(_){status('Request failed or interrupted. Existing records are preserved; retry to reconcile.');}};
 async function updateGitHub(){if(updating||document.body.dataset.owner!=='connected')return;const project=el('brain-project').value,ticket=epoch;updating=true;try{const result=await api('/api/second-brain/refresh',{project});if(ticket!==epoch||project!==el('brain-project').value||document.body.dataset.owner!=='connected')return;await refresh();if(project!==el('brain-project').value||document.body.dataset.owner!=='connected')return;el('brain-refresh-status').textContent='GitHub refresh: '+result.status+'. Next permitted check: '+result.nextCheckAt+'. '+result.coverage;}catch(_){if(project===el('brain-project').value&&document.body.dataset.owner==='connected')el('brain-refresh-status').textContent='GitHub refresh failed. Existing evidence is retained.';}finally{updating=false;}}
 function scheduleUpdates(generation){if(generation!==autoGeneration||!el('brain-refresh-auto').checked||document.body.dataset.owner!=='connected')return;autoTimer=setTimeout(async()=>{autoTimer=null;if(generation!==autoGeneration||!el('brain-refresh-auto').checked||document.body.dataset.owner!=='connected')return;if(document.visibilityState==='visible')await updateGitHub();scheduleUpdates(generation);},900000);}
 el('brain-refresh-now').addEventListener('click',run(updateGitHub));
 el('brain-refresh-auto').addEventListener('change',run(async()=>{if(!el('brain-refresh-auto').checked){stopUpdates();el('brain-refresh-status').textContent='Automatic refresh stopped.';return;}const generation=++autoGeneration;await updateGitHub();scheduleUpdates(generation);}));
 el('brain-ask-query').addEventListener('input',clearQuestion);el('brain-ask-private').addEventListener('change',clearQuestion);
 el('brain-ask-form').addEventListener('submit',run(async()=>{clearQuestion();const ticket=epoch,project=el('brain-project').value,query=el('brain-ask-query').value,includePrivate=el('brain-ask-private').checked;const result=await api('/api/second-brain/question/preview',{project,query,includePrivate});if(ticket!==epoch||project!==el('brain-project').value||document.body.dataset.owner!=='connected'||query!==el('brain-ask-query').value||includePrivate!==el('brain-ask-private').checked)return;questionPreview=result;el('brain-ask-preview').textContent=(result.configured?'AI analyst configured; allowance still checked at dispatch.':'AI analyst disabled or unconfigured. Local search is available.')+'\n'+result.notice+'\n'+result.text+'\nInput sources:\n'+result.sources.map(s=>s.ref+' '+s.source+' · '+s.dataClass+' · '+s.id+(s.truncated?' · excerpt truncated':'')).join('\n');el('brain-ask-send').disabled=!result.configured||!result.sources.length;}));
 el('brain-ask-send').addEventListener('click',run(async()=>{const p=questionPreview;if(!p||!el('brain-ask-consent').checked){status('Review and approve the displayed context first.');return;}const ticket=epoch;el('brain-ask-send').disabled=true;const result=await api('/api/second-brain/question/ask',{project:p.project,query:p.query,includePrivate:p.includePrivate,digest:p.digest,approveDisclosure:true});if(ticket!==epoch||questionPreview!==p||p.project!==el('brain-project').value||document.body.dataset.owner!=='connected')return;const container=el('brain-ask-answer');container.replaceChildren();const label=document.createElement('p');label.textContent=result.mode==='ai_analysis'?'AI analysis · not independently verified':'AI analysis unavailable';container.append(label);const text=document.createElement('p');text.textContent=result.outputText||result.message;container.append(text);for(const source of result.sources||[]){const item=document.createElement('p');item.textContent=source.ref+' · supplied context · '+source.id+' ';sourceLink(item,source);container.append(item);}el('brain-ask-consent').checked=false;}));
 el('brain-capture').addEventListener('submit',run(async()=>{const p=el('brain-project').value;const submitted=el('brain-note').value;const related=el('brain-related').value;const relation=el('brain-relation').value;if(related&&!shown.has(related)){status('Choose a record in this project.');return;}if(related&&relation==='supersedes'&&(!shown.get(related).observedAt||!el('brain-observed').value)){status('Correction needs known original and newer correction observation times. Use Related evidence if the original observation is unknown.');return;}await api('/api/second-brain/notes',{project:p,text:submitted,kind:el('brain-kind').value,source:el('brain-source').value,observedAt:el('brain-observed').value,...(related?{[relation]:[related]}:{})});if(el('brain-project').value===p&&el('brain-note').value===submitted)el('brain-note').value='';await refresh();}));
 el('brain-report-capture').addEventListener('submit',run(async()=>{const ticket=epoch,p=el('brain-project').value;const body={project:p};for(const key of reportFields)body[key]=el('brain-report-'+key).value;const related=el('brain-report-related').value;if(related){if(!shown.has(related))throw new Error('Select same-project evidence');body[el('brain-report-relation').value]=[related];}await api('/api/second-brain/reports',body);if(ticket!==epoch||el('brain-project').value!==p||document.body.dataset.owner!=='connected')return;for(const key of reportFields)if(el('brain-report-'+key).value===body[key])el('brain-report-'+key).value='';await refresh();if(el('brain-project').value===p&&document.body.dataset.owner==='connected')status('Report excerpt saved as a private reported claim. Open Prepare repair brief; no repair has started.');}));
 el('brain-repair-copy').addEventListener('click',run(async()=>{if(document.body.dataset.owner!=='connected'||!el('brain-repair-brief').value)return;try{await navigator.clipboard.writeText(el('brain-repair-brief').value);status('Repair preparation copied. Execution remains unapproved.');}catch(_){el('brain-repair-brief').focus();el('brain-repair-brief').select();status('Select and copy the repair brief using your phone’s copy menu.');}}));
 el('brain-repair-export').addEventListener('click',()=>{if(document.body.dataset.owner!=='connected'||!el('brain-repair-brief').value)return;const u=URL.createObjectURL(new Blob([el('brain-repair-brief').value],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download='SARA-'+el('brain-project').value+'-repair-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
 el('brain-changes-form').addEventListener('submit',run(refresh));el('brain-last-day').addEventListener('click',run(async()=>{el('brain-since').value=new Date(Date.now()-86400000).toISOString();await refresh();}));
 document.querySelectorAll('[data-brain-question]').forEach(button=>button.addEventListener('click',run(async()=>{el('brain-question').value=button.dataset.brainQuestion;await refresh();if(document.body.dataset.owner==='connected')el('brain-answer-title').focus();})));
 el('brain-search').addEventListener('submit',run(refresh));el('brain-project').addEventListener('change',run(async()=>{clear();await refresh();}));
 el('brain-import').addEventListener('submit',run(async()=>{const kind=el('brain-import-kind').value;const v=await api('/api/second-brain/import',{project:el('brain-project').value,kind,id:el('brain-import-id').value,attempt:el('brain-attempt').value?Number(el('brain-attempt').value):undefined});await refresh();status(v.message||'Imported bounded source evidence. This does not prove full repository acceptance.');}));
 async function loadBounties(){if(el('brain-project').value!=='sara')return;const ticket=epoch;const board=await api('/api/second-brain/bounties?project=sara');if(ticket!==epoch||el('brain-project').value!=='sara'||document.body.dataset.owner!=='connected')return;
 el('brain-bounties').replaceChildren();el('brain-bounty-brief').value='';el('brain-bounty-copy').disabled=true;const summary=document.createElement('p');summary.textContent=board.notice+' As of '+board.asOf+'. Showing '+board.candidates.length+'/'+board.totalCurrent+' current records; '+board.history.length+' historical or stale observations.';el('brain-bounties').append(summary);
 for(const c of board.candidates){const d=document.createElement('details'),h=document.createElement('summary');h.textContent=c.status+' · '+c.title;d.append(h);const p=document.createElement('p');p.textContent='Issue '+c.issueState+' · observed '+c.observedAt+' · checked '+(c.checkedAt||'unknown')+'. Comments '+c.commentsRead+'/'+c.commentsKnown+(c.commentsPartial?' (partial).':'.')+' Reward, payout eligibility and competing PRs remain unverified.';d.append(p);sourceLink(d,c);const reasons=document.createElement('ul');for(const reason of c.blockers){const li=document.createElement('li');li.textContent=reason;reasons.append(li);}d.append(reasons);
 const comments=document.createElement('details'),heading=document.createElement('summary');heading.textContent='Reported comment excerpts';comments.append(heading);for(const item of c.reportedComments){const text=document.createElement('p');text.textContent=(item.body?item.body.text+(item.body.truncated?'… [excerpt]':''):'No comment body.')+' · '+item.updatedAt;comments.append(text);sourceLink(comments,item);}d.append(comments);
 const select=document.createElement('button');select.type='button';select.textContent='Prepare task brief';select.addEventListener('click',()=>{el('brain-bounty-brief').value=c.brief;el('brain-bounty-copy').disabled=false;el('brain-bounty-brief').focus();});d.append(select);const refreshButton=document.createElement('button');refreshButton.type='button';refreshButton.textContent='Use source for refresh';refreshButton.addEventListener('click',()=>{el('brain-bounty-url').value=c.source;el('brain-bounty-url').focus();});d.append(refreshButton);el('brain-bounties').append(d);}
 if(board.history.length){const p=document.createElement('p');p.textContent='History is retained. Re-import a source to check its current state.';el('brain-bounties').append(p);for(const item of board.history)sourceLink(el('brain-bounties'),item);}}
 el('brain-bounty-load').addEventListener('click',run(loadBounties));
 el('brain-bounty-import').addEventListener('submit',run(async()=>{if(el('brain-project').value!=='sara')return;const ticket=epoch;const result=await api('/api/second-brain/bounties',{project:'sara',url:el('brain-bounty-url').value});if(ticket!==epoch||el('brain-project').value!=='sara'||document.body.dataset.owner!=='connected')return;el('brain-bounty-url').value='';await refresh();await loadBounties();if(el('brain-project').value==='sara'&&document.body.dataset.owner==='connected')status(result.message);}));
 el('brain-bounty-copy').addEventListener('click',run(async()=>{if(!el('brain-bounty-brief').value)return;try{await navigator.clipboard.writeText(el('brain-bounty-brief').value);status('Task brief copied. No work or submission was authorized.');}catch(_){el('brain-bounty-brief').focus();el('brain-bounty-brief').select();status('Select and copy the task brief using your phone’s copy menu.');}}));
 el('brain-budget-review').addEventListener('click',run(async()=>{const ticket=epoch;const reviewed=await api('/api/second-brain/jev/reallocation');if(ticket!==epoch)return;allocation=reviewed;el('brain-budget').textContent=JSON.stringify(reviewed,null,2);el('brain-budget-approve').disabled=Boolean(reviewed.blockers&&reviewed.blockers.length)||!(reviewed.transferableUsd>0);}));
 el('brain-budget-approve').addEventListener('click',run(async()=>{if(!allocation)return;const approved=allocation;el('brain-budget-approve').disabled=true;const result=await api('/api/second-brain/jev/reallocation',{targetId:approved.targetId,confirm:true});allocation=null;el('brain-budget').textContent=JSON.stringify(result,null,2);status('Reviewed allowance reassigned. Provider setup and live qualification are separate.');}));
 el('brain-jev').addEventListener('click',run(async()=>{if(!el('brain-query-public').checked){status('Approve disclosure of this public query before calling Jev.');return;}const ticket=epoch;const result=await api('/api/second-brain/jev/evaluate',{project:el('brain-project').value,query:el('brain-question').value,approvePublicQuery:true});if(ticket!==epoch)return;const message=jevMessage(result);el('brain-jev-result').textContent=message;el('brain-jev-details').textContent=JSON.stringify(result,null,2);status(message);}));
 el('brain-copy').addEventListener('click',run(async()=>{try{await navigator.clipboard.writeText(el('brain-handoff').value);status('Handoff copied.');}catch(_){el('brain-handoff').focus();el('brain-handoff').select();status('Select and copy the highlighted handoff using your phone’s copy menu.');}}));
 el('brain-export').addEventListener('click',()=>{const u=URL.createObjectURL(new Blob([el('brain-handoff').value],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download='SARA-'+el('brain-project').value+'-handoff.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
 let connected=false;new MutationObserver(()=>{const next=document.body.dataset.owner==='connected';if(next===connected)return;connected=next;el('brain-fields').disabled=!next;if(!next){clear();status('Owner authentication required.');return;}run(refresh)();}).observe(document.body,{attributes:true,attributeFilter:['data-owner']});
 })();</script>`;
 return html.replace(/(<main[^>]*>)/,`$1${panel}`).replace('</main>','</details></main>').replace('</head>',css+'</head>').replace('</body>',script+'</body>');
}
