import {arraySchema as a,objectSchema as o,integerSchema as i,textSchema as t,idSchema as id,enumSchema as e,CapabilityInputError,type Schema,type Json} from '../schema.ts';
import type {CapabilityDefinition,ExecutionContext,ExecutionOutput,FrozenCase} from '../types.ts';
import {nullable as n,bool,rows,data,strings,requireUnique,suppliedAnalysis,digest,type Data} from '../engineering/common.ts';
const ids=a(id,256),texts=a(t(1024),256),money=i(0,1e12),score=i(-1e12,1e12),authority=e('READ_ONLY','DRAFT_ONLY','REVERSIBLE_AUTHORIZED','CONSEQUENTIAL_REQUIRES_OWNER','PROHIBITED');
const task=o({id,capabilityId:id,dependencies:ids,authorityClass:authority,completionCriteria:texts,evidenceRequirements:texts,input:{type:'json'},obligation:bool,score:n(score),permission:e('PERMITTED','UNKNOWN','PROHIBITED'),prerequisitesSatisfied:bool,evidenceSufficient:bool});
const tasks=a(task,128);
type Known={id:string;enabled:boolean;authorityClass:string};
type Context=ExecutionContext&{capabilityReadiness?:readonly Known[]};
function ordered(list:Data[]):string[]{requireUnique(list,'id');const map=new Map(list.map(v=>[String(v.id),v])),result:string[]=[],visiting=new Set<string>(),done=new Set<string>();
 function visit(id:string){if(visiting.has(id))throw new CapabilityInputError('DEPENDENCY_CYCLE');if(done.has(id))return;const row=map.get(id);if(!row)throw new CapabilityInputError('MISSING_DEPENDENCY');visiting.add(id);for(const d of strings(row.dependencies!))visit(d);visiting.delete(id);done.add(id);result.push(id);}
 for(const row of list)visit(String(row.id));return result;
}
export function prioritizeTasks(list:Data[]):{eligible:Data[];blocked:Data[]} {
 requireUnique(list,'id');const eligible:Data[]=[],blocked:Data[]=[];
 for(const row of list){if(row.permission!=='PERMITTED'||!row.prerequisitesSatisfied||!row.evidenceSufficient||row.authorityClass==='PROHIBITED')blocked.push(row);else eligible.push(row);}
 eligible.sort((a,b)=>Number(b.obligation)-Number(a.obligation)||Number(b.score!==null)-Number(a.score!==null)||Number(b.score??0)-Number(a.score??0)||String(a.id).localeCompare(String(b.id)));
 return {eligible,blocked};
}
/** Bounded supported goal families produce work contracts, never invented inputs or authority. */
export function deriveGoalTasks(goal:string):Data[] {
 const lower=goal.toLowerCase();let ids:string[]=[];
 if(/\b(?:triage|inspect|diagnose)\b/.test(lower)&&/\bci(?: failure)?\b/.test(lower))ids=['ci-failure-triage'];
 else if(/\b(?:bug|defect|regression|software|ci failure)\b/.test(lower))ids=['bug-reproduction-planner','root-cause-analyzer','diagnostic-experiment-designer','minimal-fix-selector','test-gap-mapper','repository-change-impact-analyzer','pull-request-risk-review','release-readiness-gate','production-proof-validator'];
 else if(/\bnico\b/.test(lower))ids=['nico-run-health-diagnoser','nico-scanner-completeness-validator','nico-review-readiness-validator','nico-approval-provenance-verifier','nico-export-integrity-verifier','nico-delivery-readiness-gate'];
 else if(/\b(?:customer|website|service|proposal)\b/.test(lower))ids=['support-intake-triage','website-maintenance-scope-estimator','market-demand-validator','quote-margin-guard','proposal-compiler','customer-acceptance-verifier','delivery-evidence-pack-compiler'];
 else if(/\b(?:inbox|secretary|brief|meeting|email)\b/.test(lower))ids=['inbox-priority-classifier','email-thread-action-extractor','commitment-tracker','follow-up-detector','daily-owner-brief'];
 return ids.map((capabilityId,index)=>({id:`goal-step-${index+1}`,capabilityId,dependencies:index?[`goal-step-${index}`]:[],authorityClass:['proposal-compiler','delivery-evidence-pack-compiler','daily-owner-brief'].includes(capabilityId)?'DRAFT_ONLY':'READ_ONLY',completionCriteria:[`Validated ${capabilityId} output satisfies the exact supplied acceptance contract`],evidenceRequirements:['Exact subject identity and capability-specific inputs are required before execution'],input:null,obligation:false,score:null,permission:'UNKNOWN',prerequisitesSatisfied:false,evidenceSufficient:false}));
}
function queue(input:Data,ctx:Context):ExecutionOutput {const list=rows(input.tasks!).length?rows(input.tasks!):deriveGoalTasks(String(input.goal)),order=ordered(list),unknowns:string[]=[];
 const result=list.map(row=>{const contract=ctx.capabilityReadiness?.find(c=>c.id===row.capabilityId);const missing=!contract?.enabled;const derived=rows(input.tasks!).length===0;const mismatch=!derived&&contract&&contract.authorityClass!==row.authorityClass;if(missing)unknowns.push(String(row.capabilityId));return {...row,...(derived&&contract?{authorityClass:contract.authorityClass}:{}),state:missing?'MISSING_CAPABILITY':mismatch?'AUTHORITY_MISMATCH':row.input===null||strings(row.completionCriteria!).length===0?'INCOMPLETE_CONTRACT':'PLANNED',registeredAuthorityClass:contract?.authorityClass??null};});
 return suppliedAnalysis({goalId:input.goalId!,goal:input.goal!,tasks:result,dependencyOrder:order,missingCapabilities:[...new Set(unknowns)].sort(),planDigest:digest({goalId:input.goalId,goal:input.goal,tasks:result}),executionAuthorized:false,status:result.length&&result.every(t=>t.state==='PLANNED')?'PLAN_READY':'INCOMPLETE_EVIDENCE'});
}
function rebalance(input:Data):ExecutionOutput {const list=rows(input.tasks!),{eligible,blocked}=prioritizeTasks(list);const previous=strings(input.previousOrder!);if(new Set(previous).size!==previous.length)throw new CapabilityInputError('DUPLICATE_PRIOR_ID');const ideal=eligible.map(r=>String(r.id));const relevant=previous.filter(id=>ideal.includes(id));let material=Boolean(input.materialFactsChanged)||relevant.length!==ideal.length;
 for(let p=0;p<ideal.length&&!material;p++){const old=eligible.find(r=>r.id===relevant[p]),next=eligible[p];if(!old||!next){material=true;break;}if(old.obligation!==next.obligation||Math.abs(Number(old.score??0)-Number(next.score??0))>Number(input.minimumScoreDelta))material=true;}
 return suppliedAnalysis({order:material?ideal:relevant,blockedIds:blocked.map(r=>r.id!),changed:material&&digest(ideal)!==digest(previous),reason:material?'MATERIAL_ELIGIBILITY_OBLIGATION_OR_SCORE_CHANGE':'UNCHANGED_ORDER_WITHIN_THRESHOLD',executionAuthorized:false});
}
function stop(input:Data):ExecutionOutput {const attempts=rows(input.attempts!);requireUnique(attempts,'id');let spent=0;for(const r of attempts)spent+=Number(r.costMicroUsd);const reasons:string[]=[];
 if(attempts.some(r=>r.outcome==='SUCCESS'))reasons.push('WORK_ALREADY_COMPLETED');
 if(attempts.some(r=>r.outcome==='DETERMINISTIC_FAILURE'))reasons.push('DETERMINISTIC_FAILURE_REQUIRES_REPAIR');
 if(attempts.length>=Number(input.maximumAttempts))reasons.push('ATTEMPT_CEILING');
 if(spent+Number(input.nextCostMicroUsd)>Number(input.costCeilingMicroUsd))reasons.push('COST_CEILING');
 if(input.nextExpectedNetMicroUsd===null)reasons.push('ECONOMIC_EVIDENCE_REQUIRED');else if(Number(input.nextExpectedNetMicroUsd)<=0)reasons.push('NONPOSITIVE_EXPECTED_VALUE');
 const completed=reasons.includes('WORK_ALREADY_COMPLETED'),must=Boolean(input.ownerMustComplete);
 return suppliedAnalysis({decision:completed?'COMPLETE':reasons.length?must?'BLOCKED_MUST_COMPLETE':'PAUSE':'CONTINUE_CANDIDATE',reasons,spentMicroUsd:spent,remainingMicroUsd:Math.max(0,Number(input.costCeilingMicroUsd)-spent),ownerBlockerRequired:must&&reasons.length>0&&!completed,abandoned:false,reservationsReleased:false,executionAuthorized:false});
}
function idle(input:Data,ctx:Context):ExecutionOutput {const list=rows(input.tasks!);const safe=list.filter(t=>{const c=ctx.capabilityReadiness?.find(c=>c.id===t.capabilityId);return c?.enabled&&['READ_ONLY','DRAFT_ONLY'].includes(c.authorityClass)&&c.authorityClass===t.authorityClass;});const ranked=prioritizeTasks(safe);return suppliedAnalysis({selectedId:input.higherPriorityWorkExists?null:ranked.eligible[0]?.id??null,excludedIds:list.filter(t=>!ranked.eligible.includes(t)).map(t=>t.id!),reason:input.higherPriorityWorkExists?'HIGHER_PRIORITY_WORK_EXISTS':ranked.eligible.length?'QUALIFIED_BOUNDED_CANDIDATE':'NO_ELIGIBLE_SAFE_WORK',executionAuthorized:false});}
function reconcile(input:Data):ExecutionOutput {const list=rows(input.jobs!);requireUnique(list,'id');const actions=list.map(job=>({id:job.id!,action:job.completed?'CLOSE':job.supersededBy!==null?'SUPERSEDE':job.externalCompletion==='UNKNOWN'?'RECONCILE_EXTERNAL':job.blocked?'ESCALATE':job.hasDurableState?'RESUME_EXISTING':'INSPECT_MISSING_STATE',reason:job.completed?'Completion evidence is reported.':job.supersededBy!==null?'A replacement identity is reported; retain original history.':job.externalCompletion==='UNKNOWN'?'External state must be reconciled before retry.':job.blocked?'Preserve the exact blocker.':job.hasDurableState?'Reuse the existing job identity and accounting.':'Do not create another job to escape missing state.'}));return suppliedAnalysis({actions,newJobsCreated:0,historyDeleted:false,executionAuthorized:false});}
function gaps(input:Data,ctx:Context):ExecutionOutput {const attempts=rows(input.encounters!);requireUnique(attempts,'id');const groups=new Map<string,Data[]>();for(const r of attempts){const key=String(r.capabilityId);groups.set(key,[...(groups.get(key)??[]),r]);}const candidates:Data[]=[];for(const [capabilityId,events] of groups){const failed=events.filter(e=>e.outcome==='MISSING'||e.outcome==='FAILED');if(failed.length>=Number(input.minimumOccurrences)){const current=ctx.capabilityReadiness?.find(c=>c.id===capabilityId);candidates.push({capabilityId,occurrences:events.length,failures:failed.length,currentlyEnabled:current?.enabled??false,evidenceIds:failed.flatMap(e=>strings(e.evidenceIds!)),recommendation:current?.enabled?'REQUALIFY_EXISTING':'LEARNING_CANDIDATE'});}}return suppliedAnalysis({candidates,codeInstalled:false,authorityExpanded:false});}
function obsolete(input:Data):ExecutionOutput {const caps=rows(input.capabilities!);requireUnique(caps,'id');const recommendations=caps.flatMap(c=>{const reasons:string[]=[];if(c.supersededBy!==null)reasons.push('SUPERSEDED');if(c.compatible===false)reasons.push('INCOMPATIBLE');if(Number(c.failures)>0&&Number(c.failures)>=Number(c.successes))reasons.push('UNDERPERFORMING');if(c.netContributionMicroUsd!==null&&Number(c.netContributionMicroUsd)<0)reasons.push('ECONOMICALLY_HARMFUL');if(Number(c.uses)===0)reasons.push('UNUSED');return reasons.length?[{id:c.id!,reasons,evidenceIds:c.evidenceIds!,recommendedAction:reasons.includes('INCOMPATIBLE')?'OWNER_REVIEW_QUARANTINE':'REVIEW_REQUALIFICATION_OR_RETIREMENT'}]:[];});return suppliedAnalysis({recommendations,controlsChanged:false,historyDeleted:false,automaticDisable:false});}
const sample:Data={id:'read',capabilityId:'ci-failure-triage',dependencies:[],authorityClass:'READ_ONLY',completionCriteria:['root evidence classified'],evidenceRequirements:['log'],input:{},obligation:false,score:10,permission:'PERMITTED',prerequisitesSatisfied:true,evidenceSufficient:true};
const known={capabilityReadiness:[{id:'ci-failure-triage',enabled:true,authorityClass:'READ_ONLY'}]} as Partial<ExecutionContext>;
const specs:Record<string,{input:Schema;output:Schema;execute:(input:Data,ctx:Context)=>ExecutionOutput;description:string;cases:FrozenCase[]}>= {
 'goal-to-work-queue-compiler':{description:'Compile explicit goal and task contracts into an ordered dependency plan with current capability readiness, authority mismatches and completion requirements.',input:o({goalId:id,goal:t(4096),tasks}),output:o({goalId:id,goal:t(4096),tasks:a(o({...task.properties!,state:t(128),registeredAuthorityClass:n(authority)}),128),dependencyOrder:ids,missingCapabilities:ids,planDigest:t(64),executionAuthorized:bool,status:e('PLAN_READY','INCOMPLETE_EVIDENCE')}),execute:queue,cases:[{name:'unregistered-gap',input:{goalId:'goal',goal:'triage supplied failure',tasks:[{...sample,capabilityId:'not-a-registered-capability'}]},check:r=>data(r.output).status==='INCOMPLETE_EVIDENCE'},{name:'known-contract-plan',input:{goalId:'goal',goal:'triage supplied failure',tasks:[sample]},context:known,check:r=>data(r.output).status==='PLAN_READY'}]},
 'priority-rebalancer':{description:'Apply eligibility and hard obligations before economic scores, preserving prior order until a supplied material fact or score threshold changes.',input:o({tasks,previousOrder:ids,minimumScoreDelta:i(0,1e12),materialFactsChanged:bool}),output:o({order:ids,blockedIds:ids,changed:bool,reason:t(128),executionAuthorized:bool}),execute:rebalance,cases:[{name:'anti-churn',input:{tasks:[sample,{...sample,id:'other',score:11}],previousOrder:['read','other'],minimumScoreDelta:2,materialFactsChanged:false},check:r=>strings(data(r.output).order!)[0]==='read'},{name:'required-commitment-before-wealth',input:{tasks:[{...sample,id:'profit',score:1000},{...sample,id:'commitment',score:-1,obligation:true},{...sample,id:'unauthorized',score:1000000,permission:'UNKNOWN'}],previousOrder:[],minimumScoreDelta:1,materialFactsChanged:true},check:r=>strings(data(r.output).order!)[0]==='commitment'&&strings(data(r.output).blockedIds!).includes('unauthorized')}]},
 'stop-loss-controller':{description:'Pause retries at explicit attempt/cost/economic boundaries while exposing mandatory owner-work blockers and retaining reservations.',input:o({attempts:a(o({id,costMicroUsd:money,outcome:e('SUCCESS','TRANSIENT_FAILURE','DETERMINISTIC_FAILURE','UNKNOWN')}),128),maximumAttempts:i(0,128),nextCostMicroUsd:money,costCeilingMicroUsd:money,nextExpectedNetMicroUsd:n(score),ownerMustComplete:bool}),output:o({decision:e('COMPLETE','BLOCKED_MUST_COMPLETE','PAUSE','CONTINUE_CANDIDATE'),reasons:texts,spentMicroUsd:i(),remainingMicroUsd:money,ownerBlockerRequired:bool,abandoned:bool,reservationsReleased:bool,executionAuthorized:bool}),execute:stop,cases:[{name:'must-complete-not-abandoned',input:{attempts:[],maximumAttempts:2,nextCostMicroUsd:1,costCeilingMicroUsd:0,nextExpectedNetMicroUsd:10,ownerMustComplete:true},check:r=>data(r.output).decision==='BLOCKED_MUST_COMPLETE'&&data(r.output).abandoned===false}]},
 'idle-value-selector':{description:'Select a qualified read/draft candidate only when no higher-priority work exists; idle time never creates authority.',input:o({tasks,higherPriorityWorkExists:bool}),output:o({selectedId:n(id),excludedIds:ids,reason:t(128),executionAuthorized:bool}),execute:idle,cases:[{name:'unknown-capability-not-idle-work',input:{tasks:[{...sample,capabilityId:'not-a-registered-capability'}],higherPriorityWorkExists:false},check:r=>data(r.output).selectedId===null},{name:'known-safe-candidate',input:{tasks:[sample],higherPriorityWorkExists:false},context:known,check:r=>data(r.output).selectedId==='read'}]},
 'unfinished-work-reconciler':{description:'Classify stranded supplied job records as resume, reconcile, close, supersede or escalate without duplicate jobs or releasing accounting.',input:o({jobs:a(o({id,completed:bool,supersededBy:n(id),externalCompletion:e('KNOWN','UNKNOWN'),blocked:bool,hasDurableState:bool}),128)}),output:o({actions:a(o({id,action:e('CLOSE','SUPERSEDE','RECONCILE_EXTERNAL','ESCALATE','RESUME_EXISTING','INSPECT_MISSING_STATE'),reason:t(1024)}),128),newJobsCreated:i(0,0),historyDeleted:bool,executionAuthorized:bool}),execute:reconcile,cases:[{name:'uncertain-external-state',input:{jobs:[{id:'job',completed:false,supersededBy:null,externalCompletion:'UNKNOWN',blocked:false,hasDurableState:true}]},check:r=>rows(data(r.output).actions!)[0]!.action==='RECONCILE_EXTERNAL'}]},
 'capability-gap-detector':{description:'Identify repeated missing or failed capability work as bounded requalification/learning candidates; never install code or broaden authority.',input:o({encounters:a(o({id,capabilityId:id,outcome:e('SUCCESS','FAILED','MISSING'),evidenceIds:ids}),256),minimumOccurrences:i(1,256)}),output:o({candidates:a(o({capabilityId:id,occurrences:i(),failures:i(),currentlyEnabled:bool,evidenceIds:a(id,2000),recommendation:e('REQUALIFY_EXISTING','LEARNING_CANDIDATE')}),256),codeInstalled:bool,authorityExpanded:bool}),execute:gaps,cases:[{name:'repeated-missing-gap',input:{encounters:[{id:'a',capabilityId:'unknown',outcome:'MISSING',evidenceIds:[]},{id:'b',capabilityId:'unknown',outcome:'MISSING',evidenceIds:[]}],minimumOccurrences:2},check:r=>rows(data(r.output).candidates!).length===1&&data(r.output).codeInstalled===false}]},
 'capability-obsolescence-detector':{description:'Recommend review for unused, superseded, incompatible, failing or economically harmful capabilities while preserving all controls and history.',input:o({capabilities:a(o({id,uses:i(),successes:i(),failures:i(),supersededBy:n(id),compatible:n(bool),netContributionMicroUsd:n(score),evidenceIds:ids}),128)}),output:o({recommendations:a(o({id,reasons:texts,evidenceIds:ids,recommendedAction:t(128)}),128),controlsChanged:bool,historyDeleted:bool,automaticDisable:bool}),execute:obsolete,cases:[{name:'underperformance-recommends-only',input:{capabilities:[{id:'cap',uses:2,successes:0,failures:2,supersededBy:null,compatible:true,netContributionMicroUsd:-10,evidenceIds:['failure']} ]},check:r=>rows(data(r.output).recommendations!).length===1&&data(r.output).automaticDisable===false}]},
};
export const selfManagementDefinitions:readonly CapabilityDefinition[]=Object.entries(specs).map(([id,s])=>({id,version:'1.0.0',description:s.description,inputSchema:s.input,outputSchema:s.output,effect:id==='goal-to-work-queue-compiler'?'DRAFT_ONLY':'PURE',authorityClass:id==='goal-to-work-queue-compiler'?'DRAFT_ONLY':'READ_ONLY',sourceFiles:['self-management/definitions.ts','engineering/common.ts'],qualificationRequirements:['frozen-contract','bounded-input','negative-and-missing-data','authority-before-value','obligation-before-value','determinism','no-duplicate-external-effects','existing-durable-receipts'],execute:s.execute,cases:s.cases}));
