import {arraySchema as a,objectSchema as o,integerSchema as i,textSchema as t,idSchema as id,enumSchema as e,CapabilityInputError,type Json,type Schema} from '../schema.ts';
import type {CapabilityDefinition,ExecutionOutput,FrozenCase} from '../types.ts';
import {nullable as n,bool,rows,data,strings,requireUnique,suppliedAnalysis,digest,type Data} from '../engineering/common.ts';

const money=i(0,1_000_000_000_000),signed=i(-Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER),ppm=i(0,1_000_000),texts=a(t(1024),128);
const costSchema=o({directCashMicroUsd:n(money),modelApiMicroUsd:n(money),infrastructureMicroUsd:n(money),toolingMicroUsd:n(money),allocatedMicroUsd:n(money),modeledLaborMicroUsd:n(money)});
const valueSchema=o({benefitMicroUsd:n(money),benefitBasis:t(1024,0),successProbabilityPpm:n(ppm),probabilityBasis:t(1024,0),cost:costSchema,riskReserveMicroUsd:n(money),opportunityCostMicroUsd:n(money),repeatabilityPoints:i(0,100),strategicPoints:i(0,100),deadline:n(t(128))});
const costKeys=['directCashMicroUsd','modelApiMicroUsd','infrastructureMicroUsd','toolingMicroUsd'];
function sum(values:Json[]):number|null {if(values.some(v=>v===null))return null;const total=values.reduce<number>((s,v)=>s+Number(v),0);if(!Number.isSafeInteger(total))throw new CapabilityInputError('ARITHMETIC_OVERFLOW');return total;}
function mul(value:number,probability:number):number{return Number(BigInt(value)*BigInt(probability)/1_000_000n);}
function amount(c:Data):number|null{return sum(costKeys.map(k=>c[k]!));}
export function evaluateWorkValue(input:Data):Data {
 const cash=amount(data(input.cost!)),unknowns:string[]=[];
 if(input.benefitMicroUsd===null||!input.benefitBasis)unknowns.push('Expected benefit and its basis are required.');
 if(input.successProbabilityPpm===null||!input.probabilityBasis)unknowns.push('Success probability and its basis are required.');
 if(cash===null)unknowns.push('One or more expected cash costs are unknown.');
 if(input.riskReserveMicroUsd===null||input.opportunityCostMicroUsd===null)unknowns.push('Risk reserve or opportunity cost is unknown.');
 const expected=unknowns.length?null:mul(Number(input.benefitMicroUsd),Number(input.successProbabilityPpm));
 const score=expected===null?null:expected-cash!-Number(input.riskReserveMicroUsd)-Number(input.opportunityCostMicroUsd);
 return {expectedBenefitMicroUsd:expected,expectedCashMicroUsd:cash,comparableScoreMicroUsd:score,rawComponents:input,unknowns,
  basis:'SUPPLIED_EXPECTATIONS_NOT_REALIZED_REVENUE',confidence:'UNASSESSED',executionAuthorized:false};
}
function value(input:Data):ExecutionOutput{return suppliedAnalysis(evaluateWorkValue(input));}
function quote(input:Data):ExecutionOutput {
 const cash=amount(data(input.cost!)),reserve=input.riskReserveMicroUsd,price=input.proposedPriceMicroUsd,minimum=Number(input.minimumMarginPpm);
 const total=cash===null||reserve===null?null:cash+Number(reserve);
 const contribution=total===null||price===null?null:Number(price)-total;
 const margin=contribution===null||price===0?null:Number(BigInt(contribution)*1_000_000n/BigInt(Number(price)));
 const status=margin===null?'INCOMPLETE_EVIDENCE':BigInt(contribution!)*1_000_000n<BigInt(Number(price))*BigInt(minimum)?'BLOCKED':'MARGIN_SATISFIED';
 return suppliedAnalysis({status,expectedCashMicroUsd:cash,riskReserveMicroUsd:reserve!,allocatedMicroUsd:data(input.cost!).allocatedMicroUsd!,modeledLaborMicroUsd:data(input.cost!).modeledLaborMicroUsd!,proposedPriceMicroUsd:price!,contributionMicroUsd:contribution,marginPpm:margin,minimumMarginPpm:minimum,acceptanceAuthorized:false,spendingAuthorized:false});
}
function price(input:Data):ExecutionOutput {
 const cash=amount(data(input.cost!)),reserve=input.riskReserveMicroUsd,support=input.expectedSupportMicroUsd,margin=Number(input.minimumMarginPpm);
 const total=cash===null||reserve===null||support===null?null:cash+Number(reserve)+Number(support);
 const minimum=total===null?null:Number((BigInt(total)*1_000_000n+BigInt(1_000_000-margin)-1n)/BigInt(1_000_000-margin));
 return suppliedAnalysis({status:minimum===null?'INCOMPLETE_EVIDENCE':'COST_FLOOR_CALCULATED',minimumPriceMicroUsd:minimum,recommendedRangeMicroUsd:minimum===null?null:{minimum,maximum:null},demandEvidenceRefs:input.demandEvidenceRefs!,competitiveEvidenceRefs:input.competitiveEvidenceRefs!,valueBasis:input.valueBasis!,assumptions:['Cost floor uses supplied cash, risk and support estimates.','Demand and competitor references are unverified inputs.','Allocated and modeled labor costs remain separate; no market premium is fabricated.'],offerAuthorized:false});
}
function account(input:Data):ExecutionOutput {
 const entries=rows(input.entries!);requireUnique(entries,'id');const jobs=new Map<string,Data>();
 for(const entry of entries){const job=String(entry.jobId);if(!jobs.has(job))jobs.set(job,{jobId:job,realizedRevenueMicroUsd:0,predictedRevenueMicroUsd:0,refundsMicroUsd:0,modelApiMicroUsd:0,directExternalMicroUsd:0,allocatedMicroUsd:0,modeledLaborMicroUsd:0,unknownCostIds:[],sourceRefs:[]});
  const row=jobs.get(job)!;(row.sourceRefs as Json[]).push(entry.sourceId!);const key=entry.kind==='REVENUE'?(entry.realized?'realizedRevenueMicroUsd':'predictedRevenueMicroUsd'):({REFUND:'refundsMicroUsd',MODEL_API:'modelApiMicroUsd',DIRECT_EXTERNAL:'directExternalMicroUsd',ALLOCATION:'allocatedMicroUsd',MODELED_LABOR:'modeledLaborMicroUsd'} as Record<string,string>)[String(entry.kind)]!;
  if(entry.amountMicroUsd===null){(row.unknownCostIds as Json[]).push(entry.id!);continue;}
  if(!entry.realized&&!['ALLOCATION','MODELED_LABOR','REVENUE'].includes(String(entry.kind)))throw new CapabilityInputError('ACTUAL_COST_REQUIRES_REALIZED_BASIS');
  row[key]=sum([row[key]!,entry.amountMicroUsd!])!;
 }
 const result=[...jobs.values()].sort((a,b)=>String(a.jobId).localeCompare(String(b.jobId))).map(row=>{const gross=(row.unknownCostIds as Json[]).length?null:Number(row.realizedRevenueMicroUsd)-Number(row.refundsMicroUsd)-Number(row.modelApiMicroUsd)-Number(row.directExternalMicroUsd);return {...row,grossContributionMicroUsd:gross,netContributionMicroUsd:gross===null?null:gross-Number(row.allocatedMicroUsd)-(input.includeModeledLabor?Number(row.modeledLaborMicroUsd):0),accountingModel:input.includeModeledLabor?'CASH_MINUS_ALLOCATION_MINUS_MODELED_LABOR':'CASH_MINUS_ALLOCATION'};});
 return suppliedAnalysis({jobs:result,ledgerChanged:false,financialAttestationCreated:false,inputDigest:digest(input)},['This report calculates supplied entries; only the existing owner-attested ledger establishes realized financial events.']);
}
function rank(input:Data):ExecutionOutput {
 const opportunities=rows(input.opportunities!);requireUnique(opportunities,'id');const ranked:Data[]=[],blocked:Data[]=[];
 for(const row of opportunities){const reasons:string[]=[];if(row.permission!=='PERMITTED')reasons.push('AUTHORITY_REQUIRED');if(!row.prerequisitesSatisfied)reasons.push('PREREQUISITES');if(!row.evidenceSufficient)reasons.push('EVIDENCE_REQUIRED');
  const valuation=evaluateWorkValue(data(row.value!));const out={id:row.id!,obligation:row.obligation!,valuation,reasons};if(reasons.length)blocked.push(out);else ranked.push(out);
 }
 ranked.sort((a,b)=>Number(b.obligation)-Number(a.obligation)||Number(data(b.valuation!).comparableScoreMicroUsd!==null)-Number(data(a.valuation!).comparableScoreMicroUsd!==null)||Number(data(b.valuation!).comparableScoreMicroUsd??0)-Number(data(a.valuation!).comparableScoreMicroUsd??0)||String(a.id).localeCompare(String(b.id)));
 return suppliedAnalysis({ranked,blocked,selectedId:ranked[0]?.id??null,executionAuthorized:false,authorityBasis:'SUPPLIED_ELIGIBILITY_ADVISORY_ONLY'});
}
function budget(input:Data):ExecutionOutput {
 const requests=rows(input.requests!);requireUnique(requests,'id');const ceiling=data(input.ceilings!),used=data(input.alreadyUsed!),remaining:Data={};
 for(const key of Object.keys(ceiling)){const r=Number(ceiling[key])-Number(used[key]);if(r<0)throw new CapabilityInputError('EXISTING_USAGE_EXCEEDS_CEILING');remaining[key]=r;}
 const allocated:Data[]=[],blocked:Data[]=[];
 for(const request of [...requests].sort((a,b)=>Number(b.obligation)-Number(a.obligation)||Number(b.priority)-Number(a.priority)||String(a.id).localeCompare(String(b.id)))){const needs=data(request.resources!),missing=Object.keys(remaining).filter(k=>Number(needs[k])>Number(remaining[k]));if(missing.length){blocked.push({id:request.id!,missingResources:missing});continue;}for(const key of Object.keys(remaining))remaining[key]=Number(remaining[key])-Number(needs[key]);allocated.push({id:request.id!,resources:needs});}
 return suppliedAnalysis({allocated,blocked,remaining,ownerCeilingChanged:false,reservationsCreated:false,executionAuthorized:false},['The existing authoritative budget and reservation engine must approve any actual allocation.']);
}
const resource=o({modelCalls:i(0,100000),apiCalls:i(0,100000),computeSeconds:i(0,1000000),timeSeconds:i(0,1000000),cashMicroUsd:money});
const valueOut=o({expectedBenefitMicroUsd:n(money),expectedCashMicroUsd:n(signed),comparableScoreMicroUsd:n(signed),rawComponents:valueSchema,unknowns:texts,basis:t(128),confidence:e('UNASSESSED'),executionAuthorized:bool});
const baseCost={directCashMicroUsd:10,modelApiMicroUsd:5,infrastructureMicroUsd:0,toolingMicroUsd:0,allocatedMicroUsd:2,modeledLaborMicroUsd:50};
export const valueFixture:Data={benefitMicroUsd:100,benefitBasis:'supplied signed scope price',successProbabilityPpm:800000,probabilityBasis:'supplied historic frequency',cost:baseCost,riskReserveMicroUsd:5,opportunityCostMicroUsd:10,repeatabilityPoints:0,strategicPoints:0,deadline:null};
const specs:Record<string,{input:Schema;output:Schema;execute:(input:Data)=>ExecutionOutput;description:string;cases:FrozenCase[]}>= {
 'economic-value-of-work':{description:'Calculate supplied expected monetary value while preserving probability basis, cash, allocation, modeled labor, risk and strategic dimensions separately.',input:valueSchema,output:valueOut,execute:value,cases:[{name:'expected-value-arithmetic',input:valueFixture,check:r=>data(r.output).comparableScoreMicroUsd===50},{name:'missing-probability',input:{...valueFixture,successProbabilityPpm:null},check:r=>data(r.output).comparableScoreMicroUsd===null}]},
 'quote-margin-guard':{description:'Gate supplied quotes against explicit cash cost, risk reserve and minimum margin without accepting work or spending.',input:o({cost:costSchema,riskReserveMicroUsd:n(money),proposedPriceMicroUsd:n(money),minimumMarginPpm:ppm}),output:o({status:e('INCOMPLETE_EVIDENCE','BLOCKED','MARGIN_SATISFIED'),expectedCashMicroUsd:n(signed),riskReserveMicroUsd:n(money),allocatedMicroUsd:n(money),modeledLaborMicroUsd:n(money),proposedPriceMicroUsd:n(money),contributionMicroUsd:n(signed),marginPpm:n(signed),minimumMarginPpm:ppm,acceptanceAuthorized:bool,spendingAuthorized:bool}),execute:quote,cases:[{name:'cash-margin',input:{cost:baseCost,riskReserveMicroUsd:5,proposedPriceMicroUsd:100,minimumMarginPpm:800000},check:r=>data(r.output).marginPpm===800000&&data(r.output).status==='MARGIN_SATISFIED'},{name:'zero-price',input:{cost:baseCost,riskReserveMicroUsd:5,proposedPriceMicroUsd:0,minimumMarginPpm:1},check:r=>data(r.output).status==='INCOMPLETE_EVIDENCE'}]},
 'service-pricing-engine':{description:'Calculate an explicit price floor from supplied cash, support burden, risk and margin, retaining demand/value/competitive assumptions without inventing a market premium.',input:o({cost:costSchema,riskReserveMicroUsd:n(money),expectedSupportMicroUsd:n(money),minimumMarginPpm:i(0,999999),demandEvidenceRefs:texts,competitiveEvidenceRefs:texts,valueBasis:t(2048,0)}),output:o({status:e('INCOMPLETE_EVIDENCE','COST_FLOOR_CALCULATED'),minimumPriceMicroUsd:n(signed),recommendedRangeMicroUsd:n(o({minimum:signed,maximum:{type:'null'}})),demandEvidenceRefs:texts,competitiveEvidenceRefs:texts,valueBasis:t(2048,0),assumptions:texts,offerAuthorized:bool}),execute:price,cases:[{name:'round-up-floor',input:{cost:baseCost,riskReserveMicroUsd:5,expectedSupportMicroUsd:5,minimumMarginPpm:600000,demandEvidenceRefs:[],competitiveEvidenceRefs:[],valueBasis:''},check:r=>data(r.output).minimumPriceMicroUsd===63}]},
 'profitability-accountant':{description:'Attribute supplied revenue, refunds and actual costs by job, keeping predictions, allocations and modeled labor separate and preserving failed jobs.',input:o({entries:a(o({id,jobId:id,sourceId:id,kind:e('REVENUE','REFUND','MODEL_API','DIRECT_EXTERNAL','ALLOCATION','MODELED_LABOR'),amountMicroUsd:n(money),realized:bool}),1000),includeModeledLabor:bool}),output:o({jobs:a(o({jobId:id,realizedRevenueMicroUsd:signed,predictedRevenueMicroUsd:signed,refundsMicroUsd:signed,modelApiMicroUsd:signed,directExternalMicroUsd:signed,allocatedMicroUsd:signed,modeledLaborMicroUsd:signed,unknownCostIds:texts,sourceRefs:a(id,1000),grossContributionMicroUsd:n(signed),netContributionMicroUsd:n(signed),accountingModel:t(128)}),1000),ledgerChanged:bool,financialAttestationCreated:bool,inputDigest:t(64)}),execute:account,cases:[{name:'prediction-is-not-revenue',input:{entries:[{id:'forecast',jobId:'failed-job',sourceId:'fixture',kind:'REVENUE',amountMicroUsd:1000000,realized:false},{id:'spent',jobId:'failed-job',sourceId:'fixture',kind:'MODEL_API',amountMicroUsd:20,realized:true}],includeModeledLabor:false},check:r=>rows(data(r.output).jobs!)[0]!.netContributionMicroUsd===-20}]},
 'revenue-opportunity-ranker':{description:'Rank supplied eligible opportunities by obligation before expected net monetary value; block unauthorized or incomplete work regardless of profit.',input:o({opportunities:a(o({id,permission:e('PERMITTED','UNKNOWN','PROHIBITED'),obligation:bool,prerequisitesSatisfied:bool,evidenceSufficient:bool,value:valueSchema}),128)}),output:o({ranked:a(o({id,obligation:bool,valuation:valueOut,reasons:texts}),128),blocked:a(o({id,obligation:bool,valuation:valueOut,reasons:texts}),128),selectedId:n(id),executionAuthorized:bool,authorityBasis:t(128)}),execute:rank,cases:[{name:'obligation-before-profit-and-authority-before-both',input:{opportunities:[{id:'unauthorized',permission:'UNKNOWN',obligation:false,prerequisitesSatisfied:true,evidenceSufficient:true,value:{...valueFixture,benefitMicroUsd:1000000}},{id:'paying',permission:'PERMITTED',obligation:false,prerequisitesSatisfied:true,evidenceSufficient:true,value:valueFixture},{id:'commitment',permission:'PERMITTED',obligation:true,prerequisitesSatisfied:true,evidenceSufficient:true,value:{...valueFixture,benefitMicroUsd:0}}]},check:r=>data(r.output).selectedId==='commitment'&&rows(data(r.output).blocked!)[0]!.id==='unauthorized'}]},
 'resource-budget-planner':{description:'Allocate supplied model/API/compute/time/cash resources deterministically under unchanged ceilings, obligations first; no reservation or budget authority is created.',input:o({ceilings:resource,alreadyUsed:resource,requests:a(o({id,obligation:bool,priority:i(0,100),resources:resource}),128)}),output:o({allocated:a(o({id,resources:resource}),128),blocked:a(o({id,missingResources:texts}),128),remaining:resource,ownerCeilingChanged:bool,reservationsCreated:bool,executionAuthorized:bool}),execute:budget,cases:[{name:'budget-exhaustion',input:{ceilings:{modelCalls:1,apiCalls:0,computeSeconds:1,timeSeconds:1,cashMicroUsd:0},alreadyUsed:{modelCalls:0,apiCalls:0,computeSeconds:0,timeSeconds:0,cashMicroUsd:0},requests:[{id:'spend',obligation:true,priority:100,resources:{modelCalls:0,apiCalls:0,computeSeconds:0,timeSeconds:0,cashMicroUsd:1}}]},check:r=>rows(data(r.output).allocated!).length===0&&rows(data(r.output).blocked!).length===1}]},
};
export const economicDefinitions:readonly CapabilityDefinition[]=Object.entries(specs).map(([id,s])=>({id,version:'1.0.0',description:s.description,inputSchema:s.input,outputSchema:s.output,effect:'PURE',authorityClass:'READ_ONLY',sourceFiles:['economic/definitions.ts','engineering/common.ts'],qualificationRequirements:['integer-arithmetic','unknown-values','actual-predicted-separation','authority-before-value','budget-boundaries','frozen-contract','determinism'],execute:s.execute,cases:s.cases}));
