import {projectAuthoritativeJobAccounting} from './accounting.ts';
import {arraySchema as a,objectSchema as o,integerSchema as i,textSchema as t,idSchema as id,enumSchema as e,CapabilityInputError,type Json,type Schema} from '../schema.ts';
import type {CapabilityDefinition,ExecutionContext,ExecutionOutput,FrozenCase} from '../types.ts';
import {nullable as n,bool,rows,data,strings,requireUnique,suppliedAnalysis,digest,verifyEvidence,type Data} from '../engineering/common.ts';

const money=i(0,1_000_000_000_000),signed=i(-Number.MAX_SAFE_INTEGER,Number.MAX_SAFE_INTEGER),ppm=i(0,1_000_000),texts=a(t(1024),128);
const costSchema=o({directCashMicroUsd:n(money),modelApiMicroUsd:n(money),infrastructureMicroUsd:n(money),toolingMicroUsd:n(money),allocatedMicroUsd:n(money),modeledLaborMicroUsd:n(money)});
const valueRequired=['benefitMicroUsd','benefitBasis','successProbabilityPpm','probabilityBasis','cost','riskReserveMicroUsd','opportunityCostMicroUsd','repeatabilityPoints','strategicPoints','deadline'];
const demandResources=o({timeSeconds:n(i(0,1e9)),computeSeconds:n(i(0,1e9)),modelCalls:n(i(0,1e6)),apiCalls:n(i(0,1e6))});
const valueSchema=o({workId:id,customerValuePoints:n(i(0,100)),resourceDemand:demandResources,benefitMicroUsd:n(money),benefitBasis:t(1024,0),successProbabilityPpm:n(ppm),probabilityBasis:t(1024,0),cost:costSchema,riskReserveMicroUsd:n(money),opportunityCostMicroUsd:n(money),repeatabilityPoints:i(0,100),strategicPoints:i(0,100),deadline:n(t(128))},valueRequired);
const costKeys=['directCashMicroUsd','modelApiMicroUsd','infrastructureMicroUsd','toolingMicroUsd'];
function sum(values:Json[]):number|null {if(values.some(v=>v===null))return null;const total=values.reduce<number>((s,v)=>s+Number(v),0);if(!Number.isSafeInteger(total))throw new CapabilityInputError('ARITHMETIC_OVERFLOW');return total;}
function mul(value:number,probability:number):number{return Number(BigInt(value)*BigInt(probability)/1_000_000n);}
function amount(c:Data):number|null{return sum(costKeys.map(k=>c[k]!));}
export function evaluateWorkValue(input:Data):Data {
 const cash=amount(data(input.cost!)),unknowns:string[]=[];
 if(input.deadline!==null&&(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(String(input.deadline))||!Number.isFinite(Date.parse(String(input.deadline)))))throw new CapabilityInputError('INVALID_DEADLINE');
 const resources=input.resourceDemand?data(input.resourceDemand):{};
 const comparableDimensions={customerValuePoints:input.customerValuePoints??null,strategicPoints:input.strategicPoints!,repeatabilityPoints:input.repeatabilityPoints!,deadlineEpochMs:input.deadline===null?null:Date.parse(String(input.deadline)),timeSeconds:resources.timeSeconds??null,computeSeconds:resources.computeSeconds??null,modelCalls:resources.modelCalls??null,apiCalls:resources.apiCalls??null};
 if(input.benefitMicroUsd===null||!input.benefitBasis)unknowns.push('Expected benefit and its basis are required.');
 if(input.successProbabilityPpm===null||!input.probabilityBasis)unknowns.push('Success probability and its basis are required.');
 if(cash===null)unknowns.push('One or more expected cash costs are unknown.');
 if(input.riskReserveMicroUsd===null||input.opportunityCostMicroUsd===null)unknowns.push('Risk reserve or opportunity cost is unknown.');
 const expected=unknowns.length?null:mul(Number(input.benefitMicroUsd),Number(input.successProbabilityPpm));
 const score=expected===null?null:expected-cash!-Number(input.riskReserveMicroUsd)-Number(input.opportunityCostMicroUsd);
 return {workId:input.workId??null,comparableDimensions,expectedBenefitMicroUsd:expected,expectedCashMicroUsd:cash,comparableScoreMicroUsd:score,rawComponents:input,unknowns,
  basis:'SUPPLIED_EXPECTATIONS_NOT_REALIZED_REVENUE',confidence:'UNASSESSED',executionAuthorized:false};
}
function value(input:Data):ExecutionOutput{return suppliedAnalysis(evaluateWorkValue(input));}
function quote(input:Data):ExecutionOutput {
 const cash=amount(data(input.cost!)),reserve=input.riskReserveMicroUsd,price=input.proposedPriceMicroUsd,minimum=Number(input.minimumMarginPpm);
 const total=cash===null||reserve===null?null:cash+Number(reserve);
 const contribution=total===null||price===null?null:Number(price)-total;
 const margin=contribution===null||price===0?null:Number(BigInt(contribution)*1_000_000n/BigInt(Number(price)));
 const status=margin===null?'INCOMPLETE_EVIDENCE':BigInt(contribution!)*1_000_000n<BigInt(Number(price))*BigInt(minimum)?'BLOCKED':'MARGIN_SATISFIED';
 return suppliedAnalysis({status,expectedCashMicroUsd:cash,riskReserveMicroUsd:reserve!,allocatedMicroUsd:data(input.cost!).allocatedMicroUsd!,modeledLaborMicroUsd:data(input.cost!).modeledLaborMicroUsd!,proposedPriceMicroUsd:price!,contributionMicroUsd:contribution,marginPpm:margin,minimumMarginPpm:minimum,acceptanceAuthorized:false,spendingAuthorized:false});
}
function price(input:Data,context:ExecutionContext):ExecutionOutput {
 const cash=amount(data(input.cost!)),reserve=input.riskReserveMicroUsd,support=input.expectedSupportMicroUsd,margin=Number(input.minimumMarginPpm);
 const market=input.market?data(input.market):null,complexity=market?market.complexityAdditionalCashMicroUsd!:0;
 const total=cash===null||reserve===null||support===null||complexity===null?null:cash+Number(reserve)+Number(support)+Number(complexity);
 const floor=total===null?null:(BigInt(total)*1_000_000n+BigInt(1_000_000-margin)-1n)/BigInt(1_000_000-margin);
 if(floor!==null&&floor>BigInt(Number.MAX_SAFE_INTEGER))throw new CapabilityInputError('ARITHMETIC_OVERFLOW');
 const minimum=floor===null?null:Number(floor),used:Data[]=[],excluded:Data[]=[],assumptions=['Cost floor includes supplied direct cash, risk reserve, support and explicit incremental complexity cost.','Allocated and modeled labor costs remain separate.','No proposal, market demand or realized customer benefit is established by this calculation.'];
 const inspect=(observation:Data,kind:string):boolean=>{
  const {proofIds,...bound}=observation;let reason:string|null=null;
  if(observation.scopeDigest!==market!.scopeDigest||observation.billingUnit!==market!.billingUnit)reason='INCOMPARABLE_SCOPE_OR_BILLING_UNIT';
  const verified=observation.basis==='VERIFIED'&&strings(proofIds!).some(proofId=>{const record=context.evidence.find(e=>e.id===proofId||e.receiptId===proofId);return record&&record.integrity==='KERNEL_RECEIPT'&&record.provenance!=='SUPPLIED'&&record.sourceId===observation.sourceId&&record.contentDigest===digest(bound)&&verifyEvidence(context,[proofId],{provenance:record.provenance,claim:'service-pricing-observation',identity:{serviceId:String(market!.serviceId),scopeDigest:String(market!.scopeDigest),observationId:String(observation.id),observationDigest:digest(bound)}}).passed;});
  if(!reason&&observation.basis==='VERIFIED'&&!verified)reason='MISSING_OR_STALE_VERIFIED_OBSERVATION';
  if(reason){excluded.push({id:observation.id!,kind,reason});return false;}
  used.push({id:observation.id!,kind,sourceId:observation.sourceId!,verified,observationDigest:digest(bound)});return true;
 };
 let range:Data|null=minimum===null?null:{minimum,maximum:null},status=minimum===null?'INCOMPLETE_EVIDENCE':'COST_FLOOR_CALCULATED';
 if(market){
  const demands=rows(market.demands!),competitors=rows(market.competitors!),delivered=market.deliveredValue?data(market.deliveredValue):null;
  requireUnique([...demands,...competitors,...(delivered?[delivered]:[])],'id');
  const acceptedDemand=demands.filter(d=>inspect(d,'DEMAND')),offers=competitors.filter(d=>inspect(d,'COMPETITOR')),valueValid=delivered&&inspect(delivered,'DELIVERED_VALUE');
  const supportRows=acceptedDemand.filter(d=>d.kind==='SUPPORT'),counter=acceptedDemand.some(d=>d.kind==='COUNTEREVIDENCE');
  if(counter){status='CONTESTED_DEMAND';range=null;}
  else if(minimum!==null&&supportRows.length){
   const ceilings=supportRows.map(d=>Number(d.amountMicroUsd));
   if(valueValid)ceilings.push(mul(Number(delivered!.amountMicroUsd),Number(delivered!.maximumCapturePpm)));
   const ceiling=Math.min(...ceilings),offerMinimum=offers.length?Math.min(...offers.map(o=>Number(o.amountMicroUsd))):minimum,offerMaximum=offers.length?Math.max(...offers.map(o=>Number(o.amountMicroUsd))):ceiling;
   if(ceiling<minimum){status='BLOCKED_MARKET_BELOW_FLOOR';range=null;}
   else {const maximum=Math.min(ceiling,Math.max(minimum,offerMaximum));range={minimum:Math.min(maximum,Math.max(minimum,offerMinimum)),maximum};status=used.every(o=>o.verified)?'EVIDENCE_BOUND_RANGE':'CONDITIONAL_RANGE';}
   assumptions.push('Supported willingness to pay and the explicit value-capture fraction bound the ceiling; comparable competitor offers guide the interval within that ceiling and the cost floor.');
   if(offers.some(o=>Number(o.amountMicroUsd)<minimum))assumptions.push('Some competitor prices cannot satisfy this cost model; the cost floor remains binding.');
  }else assumptions.push('No qualifying supporting demand observations: market references cannot justify a price range.');
  if(used.some(o=>!o.verified))assumptions.push('Supplied observations remain unverified assumptions; the conditional range is not independently observed market demand.');
 }
 return suppliedAnalysis({status,minimumPriceMicroUsd:minimum,recommendedRangeMicroUsd:range,demandEvidenceRefs:input.demandEvidenceRefs!,competitiveEvidenceRefs:input.competitiveEvidenceRefs!,valueBasis:input.valueBasis!,usedObservations:used,excludedObservations:excluded,complexityAdditionalCashMicroUsd:complexity,assumptions,offerAuthorized:false});
}

function account(input:Data,context:ExecutionContext):ExecutionOutput {
 const jobIds=input.authoritativeJobIds?strings(input.authoritativeJobIds):[];
 if(new Set(jobIds).size!==jobIds.length)throw new CapabilityInputError('DUPLICATE_JOB_ID');
 if(jobIds.length&&input.entries&&rows(input.entries).length)throw new CapabilityInputError('MIXED_ACCOUNTING_AUTHORITY');
 if(!jobIds.length&&!input.entries)throw new CapabilityInputError('ACCOUNTING_ENTRIES_OR_AUTHORITATIVE_JOBS_REQUIRED');
 const projection=jobIds.length?projectAuthoritativeJobAccounting(jobIds,context):null;
 const entries=projection?.entries??rows(input.entries!);requireUnique(entries,'id');const jobs=new Map<string,Data>();
 for(const entry of entries){const job=String(entry.jobId);if(!jobs.has(job))jobs.set(job,{jobId:job,realizedRevenueMicroUsd:0,predictedRevenueMicroUsd:0,refundsMicroUsd:0,modelApiMicroUsd:0,directExternalMicroUsd:0,allocatedMicroUsd:0,modeledLaborMicroUsd:0,unknownCostIds:[],sourceRefs:[]});
  const row=jobs.get(job)!;(row.sourceRefs as Json[]).push(entry.sourceId!);const key=entry.kind==='REVENUE'?(entry.realized?'realizedRevenueMicroUsd':'predictedRevenueMicroUsd'):({REFUND:'refundsMicroUsd',MODEL_API:'modelApiMicroUsd',DIRECT_EXTERNAL:'directExternalMicroUsd',ALLOCATION:'allocatedMicroUsd',MODELED_LABOR:'modeledLaborMicroUsd'} as Record<string,string>)[String(entry.kind)]!;
  if(entry.amountMicroUsd===null){(row.unknownCostIds as Json[]).push(entry.id!);continue;}
  if(!entry.realized&&!['ALLOCATION','MODELED_LABOR','REVENUE'].includes(String(entry.kind)))throw new CapabilityInputError('ACTUAL_COST_REQUIRES_REALIZED_BASIS');
  row[key]=sum([row[key]!,entry.amountMicroUsd!])!;
 }
 const result=[...jobs.values()].sort((a,b)=>String(a.jobId).localeCompare(String(b.jobId))).map(row=>{const gross=(row.unknownCostIds as Json[]).length?null:Number(row.realizedRevenueMicroUsd)-Number(row.refundsMicroUsd)-Number(row.modelApiMicroUsd)-Number(row.directExternalMicroUsd);const net=gross===null?null:gross-Number(row.allocatedMicroUsd)-(input.includeModeledLabor?Number(row.modeledLaborMicroUsd):0);return {...row,recordedGrossContributionMicroUsd:gross,recordedNetContributionMicroUsd:net,grossContributionMicroUsd:projection?.unknowns.length?null:gross,netContributionMicroUsd:projection?.unknowns.length?null:net,accountingModel:input.includeModeledLabor?'CASH_MINUS_ALLOCATION_MINUS_MODELED_LABOR':'CASH_MINUS_ALLOCATION'};});
 return suppliedAnalysis({jobs:result,basis:projection?'AUTHORITATIVE_JOB_STATE':'SUPPLIED_ENTRIES',basisDigest:projection?.basisDigest??null,accountingUnknowns:projection?.unknowns??['Caller-supplied entries have not been independently attested.'],missingJobIds:projection?.missingJobIds??[],unattributedEntries:projection?.unattributedEntries??[],unattributedEntryCount:projection?.unattributedEntryCount??0,jobStatuses:projection?.jobStatuses??[],fullProfitabilityProven:false,ledgerChanged:false,financialAttestationCreated:false,inputDigest:digest(input)},projection?.unknowns??['This report calculates supplied entries; only the existing owner-attested ledger establishes realized financial events.']);
}
export const DEFAULT_VALUE_ORDER=['MONEY','DEADLINE','CUSTOMER_VALUE','STRATEGIC','REPEATABILITY','TIME','COMPUTE','MODEL_CALLS','API_CALLS'] as const;
export function compareWorkValues(a:Data,b:Data,order:readonly string[]=DEFAULT_VALUE_ORDER):number {
 const dimensions:Record<string,string>={DEADLINE:'deadlineEpochMs',CUSTOMER_VALUE:'customerValuePoints',STRATEGIC:'strategicPoints',REPEATABILITY:'repeatabilityPoints',TIME:'timeSeconds',COMPUTE:'computeSeconds',MODEL_CALLS:'modelCalls',API_CALLS:'apiCalls'};
 for(const dimension of order){const av=dimension==='MONEY'?a.comparableScoreMicroUsd:data(a.comparableDimensions!)[dimensions[dimension]!],bv=dimension==='MONEY'?b.comparableScoreMicroUsd:data(b.comparableDimensions!)[dimensions[dimension]!];if(av===null||bv===null){if(av!==bv)return av===null?1:-1;continue;}const ascending=['DEADLINE','TIME','COMPUTE','MODEL_CALLS','API_CALLS'].includes(dimension),delta=ascending?Number(av)-Number(bv):Number(bv)-Number(av);if(delta)return delta;}
 return 0;
}
function rank(input:Data):ExecutionOutput {
 const order=input.rankingOrder?strings(input.rankingOrder):[...DEFAULT_VALUE_ORDER];if(new Set(order).size!==order.length)throw new CapabilityInputError('DUPLICATE_RANKING_DIMENSION');
 const opportunities=rows(input.opportunities!);requireUnique(opportunities,'id');const ranked:Data[]=[],blocked:Data[]=[];
 for(const row of opportunities){const reasons:string[]=[];if(row.permission!=='PERMITTED')reasons.push('AUTHORITY_REQUIRED');if(!row.prerequisitesSatisfied)reasons.push('PREREQUISITES');if(!row.evidenceSufficient)reasons.push('EVIDENCE_REQUIRED');
  if(data(row.value!).workId!==undefined&&data(row.value!).workId!==row.id)throw new CapabilityInputError('WORK_ID_MISMATCH');
  const valuation=evaluateWorkValue(data(row.value!));const out={id:row.id!,obligation:row.obligation!,valuation,reasons};if(reasons.length)blocked.push(out);else ranked.push(out);
 }
 ranked.sort((a,b)=>Number(b.obligation)-Number(a.obligation)||compareWorkValues(data(a.valuation!),data(b.valuation!),order)||String(a.id).localeCompare(String(b.id)));
 return suppliedAnalysis({rankingOrder:order,ranked,blocked,selectedId:ranked[0]?.id??null,executionAuthorized:false,authorityBasis:'SUPPLIED_ELIGIBILITY_ADVISORY_ONLY'});
}
function budget(input:Data):ExecutionOutput {
 const requests=rows(input.requests!);requireUnique(requests,'id');const ceiling=data(input.ceilings!),used=data(input.alreadyUsed!),remaining:Data={};
 for(const key of Object.keys(ceiling)){const r=Number(ceiling[key])-Number(used[key]);if(r<0)throw new CapabilityInputError('EXISTING_USAGE_EXCEEDS_CEILING');remaining[key]=r;}
 const allocated:Data[]=[],blocked:Data[]=[];
 for(const request of [...requests].sort((a,b)=>Number(b.obligation)-Number(a.obligation)||Number(b.priority)-Number(a.priority)||String(a.id).localeCompare(String(b.id)))){const needs=data(request.resources!),missing=Object.keys(remaining).filter(k=>Number(needs[k])>Number(remaining[k]));if(missing.length){blocked.push({id:request.id!,missingResources:missing});continue;}for(const key of Object.keys(remaining))remaining[key]=Number(remaining[key])-Number(needs[key]);allocated.push({id:request.id!,resources:needs});}
 return suppliedAnalysis({allocated,blocked,remaining,ownerCeilingChanged:false,reservationsCreated:false,executionAuthorized:false},['The existing authoritative budget and reservation engine must approve any actual allocation.']);
}
const resource=o({modelCalls:i(0,100000),apiCalls:i(0,100000),computeSeconds:i(0,1000000),timeSeconds:i(0,1000000),cashMicroUsd:money});
const comparableDimensions=o({customerValuePoints:n(i(0,100)),strategicPoints:i(0,100),repeatabilityPoints:i(0,100),deadlineEpochMs:n(signed),timeSeconds:n(i(0,1e9)),computeSeconds:n(i(0,1e9)),modelCalls:n(i(0,1e6)),apiCalls:n(i(0,1e6))});
const valueOut=o({workId:n(id),comparableDimensions,expectedBenefitMicroUsd:n(money),expectedCashMicroUsd:n(signed),comparableScoreMicroUsd:n(signed),rawComponents:valueSchema,unknowns:texts,basis:t(128),confidence:e('UNASSESSED'),executionAuthorized:bool});
const baseCost={directCashMicroUsd:10,modelApiMicroUsd:5,infrastructureMicroUsd:0,toolingMicroUsd:0,allocatedMicroUsd:2,modeledLaborMicroUsd:50};
export const valueFixture:Data={benefitMicroUsd:100,benefitBasis:'supplied signed scope price',successProbabilityPpm:800000,probabilityBasis:'supplied historic frequency',cost:baseCost,riskReserveMicroUsd:5,opportunityCostMicroUsd:10,repeatabilityPoints:0,strategicPoints:0,deadline:null};
const observationFields={id,sourceId:id,basis:e('SUPPLIED','VERIFIED'),proofIds:a(id,32),scopeDigest:t(64,64),billingUnit:e('JOB','MONTH','HOUR'),amountMicroUsd:money};
const marketSchema=o({serviceId:id,scopeDigest:t(64,64),billingUnit:e('JOB','MONTH','HOUR'),complexityAdditionalCashMicroUsd:n(money),demands:a(o({...observationFields,kind:e('SUPPORT','COUNTEREVIDENCE')}),64),competitors:a(o(observationFields),64),deliveredValue:n(o({...observationFields,maximumCapturePpm:ppm}))});
const rankingOrder=a(e(...DEFAULT_VALUE_ORDER),9,1);
const specs:Record<string,{input:Schema;output:Schema;execute:(input:Data,context:ExecutionContext)=>ExecutionOutput;description:string;cases:FrozenCase[]}>= {
 'economic-value-of-work':{description:'Calculate supplied expected monetary value while preserving probability basis, cash, allocation, modeled labor, risk and strategic dimensions separately.',input:valueSchema,output:valueOut,execute:value,cases:[{name:'expected-value-arithmetic',input:valueFixture,check:r=>data(r.output).comparableScoreMicroUsd===50},{name:'missing-probability',input:{...valueFixture,successProbabilityPpm:null},check:r=>data(r.output).comparableScoreMicroUsd===null}]},
 'quote-margin-guard':{description:'Gate supplied quotes against explicit cash cost, risk reserve and minimum margin without accepting work or spending.',input:o({cost:costSchema,riskReserveMicroUsd:n(money),proposedPriceMicroUsd:n(money),minimumMarginPpm:ppm}),output:o({status:e('INCOMPLETE_EVIDENCE','BLOCKED','MARGIN_SATISFIED'),expectedCashMicroUsd:n(signed),riskReserveMicroUsd:n(money),allocatedMicroUsd:n(money),modeledLaborMicroUsd:n(money),proposedPriceMicroUsd:n(money),contributionMicroUsd:n(signed),marginPpm:n(signed),minimumMarginPpm:ppm,acceptanceAuthorized:bool,spendingAuthorized:bool}),execute:quote,cases:[{name:'cash-margin',input:{cost:baseCost,riskReserveMicroUsd:5,proposedPriceMicroUsd:100,minimumMarginPpm:800000},check:r=>data(r.output).marginPpm===800000&&data(r.output).status==='MARGIN_SATISFIED'},{name:'zero-price',input:{cost:baseCost,riskReserveMicroUsd:5,proposedPriceMicroUsd:0,minimumMarginPpm:1},check:r=>data(r.output).status==='INCOMPLETE_EVIDENCE'}]},
 'service-pricing-engine':{description:'Recommend a conditional or evidence-bound price range from exact comparable offers, demand, delivered value, explicit complexity costs, support, risk and minimum margin without fabricating premiums.',input:o({cost:costSchema,riskReserveMicroUsd:n(money),expectedSupportMicroUsd:n(money),minimumMarginPpm:i(0,999999),demandEvidenceRefs:texts,competitiveEvidenceRefs:texts,valueBasis:t(2048,0),market:marketSchema},['cost','riskReserveMicroUsd','expectedSupportMicroUsd','minimumMarginPpm','demandEvidenceRefs','competitiveEvidenceRefs','valueBasis']),output:o({status:e('INCOMPLETE_EVIDENCE','COST_FLOOR_CALCULATED','CONDITIONAL_RANGE','EVIDENCE_BOUND_RANGE','BLOCKED_MARKET_BELOW_FLOOR','CONTESTED_DEMAND'),usedObservations:a(o({id,kind:t(32),sourceId:id,verified:bool,observationDigest:t(64)}),129),excludedObservations:a(o({id,kind:t(32),reason:t(128)}),129),complexityAdditionalCashMicroUsd:n(money),minimumPriceMicroUsd:n(signed),recommendedRangeMicroUsd:n(o({minimum:signed,maximum:n(signed)})),demandEvidenceRefs:texts,competitiveEvidenceRefs:texts,valueBasis:t(2048,0),assumptions:texts,offerAuthorized:bool}),execute:price,cases:[{name:'round-up-floor',input:{cost:baseCost,riskReserveMicroUsd:5,expectedSupportMicroUsd:5,minimumMarginPpm:600000,demandEvidenceRefs:[],competitiveEvidenceRefs:[],valueBasis:''},check:r=>data(r.output).minimumPriceMicroUsd===63}]},
 'profitability-accountant':{description:'Attribute supplied revenue, refunds and actual costs by job, keeping predictions, allocations and modeled labor separate and preserving failed jobs.',input:o({authoritativeJobIds:a(id,32),entries:a(o({id,jobId:id,sourceId:id,kind:e('REVENUE','REFUND','MODEL_API','DIRECT_EXTERNAL','ALLOCATION','MODELED_LABOR'),amountMicroUsd:n(money),realized:bool}),1000),includeModeledLabor:bool},['includeModeledLabor']),output:o({basis:e('SUPPLIED_ENTRIES','AUTHORITATIVE_JOB_STATE'),basisDigest:n(t(64)),accountingUnknowns:a(t(2048),1000),missingJobIds:a(id,32),unattributedEntries:a(o({id,kind:t(128),source:t(128),amountMicroUsd:signed,realized:bool,recurringMonthly:bool}),128),unattributedEntryCount:i(),jobStatuses:a(o({jobId:id,status:t(128)}),32),fullProfitabilityProven:bool,jobs:a(o({jobId:id,realizedRevenueMicroUsd:signed,predictedRevenueMicroUsd:signed,refundsMicroUsd:signed,modelApiMicroUsd:signed,directExternalMicroUsd:signed,allocatedMicroUsd:signed,modeledLaborMicroUsd:signed,unknownCostIds:texts,sourceRefs:a(id,1000),recordedGrossContributionMicroUsd:n(signed),recordedNetContributionMicroUsd:n(signed),grossContributionMicroUsd:n(signed),netContributionMicroUsd:n(signed),accountingModel:t(128)}),1000),ledgerChanged:bool,financialAttestationCreated:bool,inputDigest:t(64)}),execute:account,cases:[{name:'prediction-is-not-revenue',input:{entries:[{id:'forecast',jobId:'failed-job',sourceId:'fixture',kind:'REVENUE',amountMicroUsd:1000000,realized:false},{id:'spent',jobId:'failed-job',sourceId:'fixture',kind:'MODEL_API',amountMicroUsd:20,realized:true}],includeModeledLabor:false},check:r=>rows(data(r.output).jobs!)[0]!.netContributionMicroUsd===-20}]},
 'revenue-opportunity-ranker':{description:'Rank supplied eligible opportunities by obligation before expected net monetary value; block unauthorized or incomplete work regardless of profit.',input:o({rankingOrder,opportunities:a(o({id,permission:e('PERMITTED','UNKNOWN','PROHIBITED'),obligation:bool,prerequisitesSatisfied:bool,evidenceSufficient:bool,value:valueSchema}),128)},['opportunities']),output:o({rankingOrder,ranked:a(o({id,obligation:bool,valuation:valueOut,reasons:texts}),128),blocked:a(o({id,obligation:bool,valuation:valueOut,reasons:texts}),128),selectedId:n(id),executionAuthorized:bool,authorityBasis:t(128)}),execute:rank,cases:[{name:'obligation-before-profit-and-authority-before-both',input:{opportunities:[{id:'unauthorized',permission:'UNKNOWN',obligation:false,prerequisitesSatisfied:true,evidenceSufficient:true,value:{...valueFixture,benefitMicroUsd:1000000}},{id:'paying',permission:'PERMITTED',obligation:false,prerequisitesSatisfied:true,evidenceSufficient:true,value:valueFixture},{id:'commitment',permission:'PERMITTED',obligation:true,prerequisitesSatisfied:true,evidenceSufficient:true,value:{...valueFixture,benefitMicroUsd:0}}]},check:r=>data(r.output).selectedId==='commitment'&&rows(data(r.output).blocked!)[0]!.id==='unauthorized'}]},
 'resource-budget-planner':{description:'Allocate supplied model/API/compute/time/cash resources deterministically under unchanged ceilings, obligations first; no reservation or budget authority is created.',input:o({ceilings:resource,alreadyUsed:resource,requests:a(o({id,obligation:bool,priority:i(0,100),resources:resource}),128)}),output:o({allocated:a(o({id,resources:resource}),128),blocked:a(o({id,missingResources:texts}),128),remaining:resource,ownerCeilingChanged:bool,reservationsCreated:bool,executionAuthorized:bool}),execute:budget,cases:[{name:'budget-exhaustion',input:{ceilings:{modelCalls:1,apiCalls:0,computeSeconds:1,timeSeconds:1,cashMicroUsd:0},alreadyUsed:{modelCalls:0,apiCalls:0,computeSeconds:0,timeSeconds:0,cashMicroUsd:0},requests:[{id:'spend',obligation:true,priority:100,resources:{modelCalls:0,apiCalls:0,computeSeconds:0,timeSeconds:0,cashMicroUsd:1}}]},check:r=>rows(data(r.output).allocated!).length===0&&rows(data(r.output).blocked!).length===1}]},
};
// Frozen cases cover the expanded arithmetic/identity surface, separate from external observations.
const frozenObservation={id:'demand',sourceId:'synthetic-intake',basis:'SUPPLIED',proofIds:[],scopeDigest:'a'.repeat(64),billingUnit:'JOB',amountMicroUsd:240};
const frozenMarket={serviceId:'service',scopeDigest:'a'.repeat(64),billingUnit:'JOB',complexityAdditionalCashMicroUsd:10,demands:[{...frozenObservation,kind:'SUPPORT'}],competitors:[{...frozenObservation,id:'competitor',amountMicroUsd:180}],deliveredValue:{...frozenObservation,id:'value',amountMicroUsd:1000,maximumCapturePpm:200000}};
const frozenPrice={cost:{...baseCost,directCashMicroUsd:40,modelApiMicroUsd:0},riskReserveMicroUsd:5,expectedSupportMicroUsd:5,minimumMarginPpm:500000,demandEvidenceRefs:[],competitiveEvidenceRefs:[],valueBasis:'Supplied customer outcome estimate',market:frozenMarket};
specs['service-pricing-engine']!.cases.push(
 {name:'market-range-with-explicit-complexity',input:frozenPrice,check:r=>data(r.output).status==='CONDITIONAL_RANGE'&&data(data(r.output).recommendedRangeMicroUsd!).maximum===180&&data(r.output).minimumPriceMicroUsd===120},
 {name:'contradictory-demand-does-not-become-recommendation',input:{...frozenPrice,market:{...frozenMarket,demands:[{...frozenObservation,kind:'COUNTEREVIDENCE'}]}},check:r=>data(r.output).status==='CONTESTED_DEMAND'&&data(r.output).recommendedRangeMicroUsd===null},
 {name:'unattested-verified-market-claim-is-excluded',input:{...frozenPrice,market:{...frozenMarket,demands:[{...frozenObservation,basis:'VERIFIED',proofIds:['untrusted'],kind:'SUPPORT'}]}},check:r=>data(r.output).status==='COST_FLOOR_CALCULATED'&&rows(data(r.output).excludedObservations!).length===1});
specs['economic-value-of-work']!.cases.push({name:'work-identity-and-separate-dimensions',input:{...valueFixture,workId:'job',customerValuePoints:70,resourceDemand:{timeSeconds:60,computeSeconds:5,modelCalls:0,apiCalls:null}},check:r=>data(r.output).workId==='job'&&data(data(r.output).comparableDimensions!).customerValuePoints===70&&data(r.output).comparableScoreMicroUsd===50});
specs['profitability-accountant']!.cases.push({name:'authoritative-jobs-require-kernel-state',input:{authoritativeJobIds:['missing'],includeModeledLabor:false},check:r=>rows(data(r.output).jobs!).length===0&&strings(data(r.output).missingJobIds!).includes('missing')&&data(r.output).basisDigest===null});
export const economicDefinitions:readonly CapabilityDefinition[]=Object.entries(specs).map(([id,s])=>({id,version:['economic-value-of-work','service-pricing-engine','profitability-accountant','revenue-opportunity-ranker'].includes(id)?'1.1.0':'1.0.0',description:s.description,inputSchema:s.input,outputSchema:s.output,effect:'PURE',authorityClass:'READ_ONLY',sourceFiles:['economic/definitions.ts',...(id==='profitability-accountant'?['economic/accounting.ts']:[]),'engineering/common.ts'],qualificationRequirements:['integer-arithmetic','unknown-values','actual-predicted-separation','authority-before-value','budget-boundaries','frozen-contract','determinism'],execute:s.execute,cases:s.cases}));
