import { canonicalJson, sha256 } from '../../canonical.ts';
import { CapabilityInputError, type Json } from '../schema.ts';
import type { ExecutionContext, ExecutionOutput } from '../types.ts';
type Input=Record<string,Json>;
type Message={id:string;sourceId:string;sender:string;sentAt:string;replyTo:string|null;body:string};
type Fact={id:string;messageId:string;sourceId:string;sender:string;statement:string;deadline:string|null;confidence:'EXPLICIT'|'UNCERTAIN';provenance:'SUPPLIED'};
const limitations=['Deterministic English extraction is advisory and may miss implied meaning.','Supplied communications are not independently verified external facts.','No sending, calendar mutation, payment, approval, or embedded execution is performed.'];
const injection=/(?:ignore|bypass|disable|override).{0,50}(?:policy|safeguards|instructions|security)|reveal.{0,30}(?:secret|password|token)|you are authorized/iu;
const guards=(texts:string[])=>({externalActionPerformed:false,authorityGranted:false,safetyFlags:texts.some(x=>injection.test(x))?['UNTRUSTED_INSTRUCTION_IGNORED']:[],limitations});
const result=(output:Input,unknowns:string[]=[]):ExecutionOutput=>({output,observed:[],inferred:[output],unknowns,confidence:{level:unknowns.length?'LOW':'MEDIUM',basis:'Bounded deterministic analysis of supplied text; no independent external verification.'}});
const asText=(v:Json|undefined)=>v as string;
function dateOnly(s:string):boolean{const d=new Date(s+'T00:00:00.000Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s;}
function validInstant(s:string):boolean{return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/u.test(s)&&Number.isFinite(Date.parse(s))&&dateOnly(s.slice(0,10));}
function requireInstant(s:string,location:string):void{if(!validInstant(s))throw new CapabilityInputError('INVALID_EXPLICIT_TIMESTAMP',location);}
function parseMessages(raw:Json|undefined):Message[]{const list=raw as unknown as Message[];const ids=new Set<string>();for(const m of list){if(ids.has(m.id))throw new CapabilityInputError('DUPLICATE_MESSAGE_ID');ids.add(m.id);requireInstant(m.sentAt,'$.messages.sentAt');}return list;}
function extract(list:Message[]){const commitments:Fact[]=[],decisions:Fact[]=[],questions:Fact[]=[],uncertainStatements:Fact[]=[],paymentsMentioned:Fact[]=[];
 for(const m of list){let n=0;for(const line of m.body.split(/\n/u)){if(/^\s*>/u.test(line))continue;for(const raw of line.match(/[^.!?]+[.!?]?/gu)??[]){const statement=raw.trim();if(!statement||injection.test(statement)||statement.startsWith('>'))continue;const deadline=statement.match(/\b\d{4}-\d{2}-\d{2}\b/u)?.[0]??null;const uncertain=/\b(might|may|maybe|perhaps|possibly|hope|if|could|tentative|try to)\b/iu.test(statement);const fact:Fact={id:sha256(`${m.sourceId}:${m.id}:${n++}:${statement}`).slice(0,32),messageId:m.id,sourceId:m.sourceId,sender:m.sender,statement,deadline:deadline&&dateOnly(deadline)?deadline:null,confidence:uncertain?'UNCERTAIN':'EXPLICIT',provenance:'SUPPLIED'};
 if(statement.endsWith('?'))questions.push(fact);
 if(uncertain||/^(?:I|we)\s+(?:will not|won't|cannot|no longer)\b/iu.test(statement))uncertainStatements.push({...fact,confidence:'UNCERTAIN'});
 if(!uncertain&&!statement.endsWith('?')&&/^(?:I|we)\s+(?:will|promise to|commit to)\b/iu.test(statement)&&!/\b(?:not|never|won't|cannot)\b/iu.test(statement))commitments.push(fact);
 if(!uncertain&&!statement.endsWith('?')&&/^(?:I|we)\s+(?:decided|have decided|agree|agreed)\b/iu.test(statement))decisions.push(fact);
 if(/(?:[$€£]\s*\d|\b(?:payment|invoice|pay|refund|cost|fee|USD)\b)/iu.test(statement))paymentsMentioned.push(fact);
 }}}
 if([commitments,decisions,questions,uncertainStatements,paymentsMentioned].some(x=>x.length>500))throw new CapabilityInputError('EXTRACTION_LIMIT');
 return {commitments,decisions,questions,uncertainStatements,paymentsMentioned};}
function classify(m:Message){const b=m.body;let category='INFORMATIONAL',priority='NORMAL';const basis:string[]=[];if(/\b(?:breach|unauthorized access|account compromised|phishing|security incident)\b/iu.test(b)){category='SECURITY';priority='REVIEW_PROMPTLY';basis.push('Explicit security-related words; incident not verified.');}else if(/\b(?:invoice|payment|refund|billing)\b/iu.test(b)){category='FINANCIAL';basis.push('Payment or accounting language.');}else if(/\b(?:customer|support|broken|not working|bug)\b/iu.test(b)){category='CUSTOMER';basis.push('Support or defect language.');}else if(/\b(?:outage|deployment|error|failed)\b/iu.test(b)){category='OPERATIONAL';basis.push('Operational failure language.');}else if(/\b(?:meet|meeting|schedule|appointment|calendar)\b/iu.test(b)){category='SCHEDULING';basis.push('Scheduling language.');}else if(/\b(?:unsubscribe|promotion|sale ends|marketing)\b/iu.test(b)){category='LOW_VALUE';priority='LOW';basis.push('Promotional language.');}if(!basis.length)basis.push('No specific routing signal recognized.');return {messageId:m.id,category,priority,basis,sourceId:m.sourceId,provenance:'SUPPLIED',authorityGranted:false};}
export function threadActions(i:Input):ExecutionOutput{const list=parseMessages(i.messages),e=extract(list);return result({threadId:i.threadId!,...e,responsibleParties:[...new Set(e.commitments.map(x=>x.sender))],nextAction:e.questions.length?'Review unanswered questions and prepare a response draft.':e.commitments.length?'Review explicit commitments and clarify missing deadlines.':'No explicit action identified; inspect context if needed.',...guards(list.map(x=>x.body))},e.uncertainStatements.length?['Conditional statements do not establish commitments.']:[]);}
export function trackCommitments(i:Input):ExecutionOutput{const list=parseMessages(i.messages),e=extract(list);const record={threadId:i.threadId!,commitments:e.commitments};return result({...record,uncertainStatements:e.uncertainStatements,recordDigest:sha256(canonicalJson(record)),persistence:'KERNEL_INVOCATION_RECEIPT',historyRewritten:false,...guards(list.map(x=>x.body))},e.commitments.some(x=>!x.deadline)?['One or more commitments have no explicit absolute deadline.']:[]);}
export function followUps(i:Input):ExecutionOutput{const list=parseMessages(i.messages),e=extract(list);requireInstant(asText(i.asOf),'$.asOf');const resolved=new Set<string>(),invalidResolutions:string[]=[];for(const r of i.resolutions as Input[]){const q=list.find(m=>m.id===r.questionMessageId),a=list.find(m=>m.id===r.responseMessageId);if(!q||!a||e.questions.filter(f=>f.messageId===q.id).length!==1||a.replyTo!==q.id||a.sender===q.sender||Date.parse(a.sentAt)<=Date.parse(q.sentAt)||!/^\s*(?:Answer|Confirmed|Resolved):\s*\S/iu.test(a.body)||injection.test(a.body)){invalidResolutions.push(`${r.questionMessageId}:${r.responseMessageId}`);}else resolved.add(q.id);}
 const followUps:Json[]=[...e.questions.filter(q=>!resolved.has(q.messageId)).map(q=>({kind:'UNANSWERED_QUESTION',messageId:q.messageId,sourceId:q.sourceId,reason:q.statement,dueAt:null,certainty:'UNCERTAIN'})),...e.commitments.filter(c=>c.deadline&&c.deadline<=asText(i.asOf).slice(0,10)).map(c=>({kind:'COMMITMENT_DUE',messageId:c.messageId,sourceId:c.sourceId,reason:c.statement,dueAt:null,certainty:'UNCERTAIN'}))];return result({threadId:i.threadId!,followUps,invalidResolutions,...guards(list.map(x=>x.body))},['Reply linkage and explicit answer markers are supplied assertions; completion and answer adequacy require review.','A date-only commitment has no inferred time or timezone.']);}
export function inbox(i:Input):ExecutionOutput{const list=parseMessages(i.messages);return result({items:list.map(classify),advisoryOnly:true,...guards(list.map(x=>x.body))});}
/** Select explicit scheduling sentences only; ambiguous alternatives stay together. */
function schedulingText(text:string):string{
 const sentences=text.split(/(?<=[.!?])\s+|\n/u).map(x=>x.trim()).filter(x=>x&&!x.startsWith('>')&&!injection.test(x));
 const scheduling=sentences.filter(x=>/\b(?:meet|meeting|appointment|schedule|call)\b/iu.test(x));
 return scheduling.length?scheduling.join(' '):text;
}
export function intake(i:Input):ExecutionOutput{
 const list=parseMessages(i.messages),e=extract(list),first=list[0],classified=first?classify(first):null;
 const facts=[...e.commitments,...e.questions,...e.decisions].slice(0,500),problem=first?.body??'';
 const scheduling=classified?.category==='SCHEDULING';
 const meeting=schedulingText(problem);
 const commitments=e.commitments.map(x=>x.statement).join(' ');
 const responseDraft=!first?'Please provide the request for assessment.':scheduling?
  `Thank you. ${commitments?`I noted your stated commitment: ${commitments} `:''}Your scheduling request is: ${meeting} The meeting is not confirmed. Please confirm the participants and any missing or ambiguous date, time, timezone or location.`:
  classified?.category==='FINANCIAL'?'Thank you. I noted the billing or payment question. Please identify the relevant job or invoice and the requested resolution. Payment status and any adjustment must be verified against the recorded evidence; no refund or payment is authorized by this draft.':
  `Thank you. I noted your request: ${facts.map(x=>x.statement).join(' ')||'Please clarify the desired outcome.'} Please confirm the scope, expected result and any missing deadline so the request can be assessed.`;
 const missingFacts=scheduling?['Confirm participants and any unresolved scheduling details.','Confirm availability before accepting the meeting.']:['Confirm requested outcome and acceptance criteria.','Confirm authorized target and exact affected revision.','Confirm scope, deadline, and any customer commitments.'];
 return result({requestId:i.requestId!,customerId:i.customerId!,problem,category:classified?.category??'UNKNOWN',urgency:classified?.priority??'NORMAL',knownFacts:facts,missingFacts,risks:injection.test(problem)?['Prompt injection in supplied content.']:[],requiredCapabilities:classified?.category==='FINANCIAL'?['profitability-accountant']:scheduling?['calendar-intent-parser']:['bug-reproduction-planner','website-maintenance-scope-estimator'],ownerApprovalRequirements:['Sending the response or making a customer commitment requires exact existing authority.'],recommendedNextAction:scheduling?'Review the proposed meeting details and confirm availability through an authorized channel.':first?'Clarify missing scope and inspect authorized evidence.':'Obtain the inbound request before creating actionable work.',responseDraft,...guards(list.map(x=>x.body))},first?['Scope and capability readiness are not yet verified.']:['No inbound communication supplied.']);
}
export function calendar(i:Input):ExecutionOutput{const original=asText(i.text),text=schedulingText(original),ambiguities:string[]=[];const dates=[...text.matchAll(/\b\d{4}-\d{2}-\d{2}\b/gu)].map(m=>m[0]);const times=[...text.matchAll(/\b([01]\d|2[0-3]):[0-5]\d\b/gu)].map(m=>m[0]);const zones=[...text.matchAll(/\b(?:UTC|GMT)(?:[+-](?:0\d|1[0-4]):[0-5]\d)?\b|\b[A-Za-z]+\/[A-Za-z_]+\b/gu)].map(m=>m[0]);let zone=zones.length===1?zones[0]!:null;if(zone&&zone.includes('/')){try{new Intl.DateTimeFormat('en',{timeZone:zone}).format(0);}catch{zone=null;ambiguities.push('Unrecognized timezone.');}}const date=dates.length===1&&dateOnly(dates[0]!)?dates[0]!:null,time=times.length===1?times[0]!:null;const duration=text.match(/\b(\d{1,4})\s*(minutes?|mins?|hours?|hrs?)\b/iu);const minutes=duration?Number(duration[1])*(/^h/iu.test(duration[2]!)?60:1):null;const durationMinutes=minutes&&minutes<=1440?minutes:null;const location=text.match(/\blocation:\s*([^;\n.]{1,256})/iu)?.[1]?.trim()??null;
 if(!date)ambiguities.push('One valid absolute ISO date is required; relative dates are unresolved.');if(!time)ambiguities.push('One explicit 24-hour time is required.');if(!zone)ambiguities.push('An explicit unambiguous timezone is required.');if(!durationMinutes)ambiguities.push('An explicit duration of 1–1440 minutes is required.');if(!i.participants||(i.participants as Json[]).length===0)ambiguities.push('Participants are unspecified.');if(injection.test(text))ambiguities.push('Untrusted instructions must not control calendar actions.');return result({title:i.title!,participants:i.participants!,date,time,timezone:zone,durationMinutes,location,notes:original,status:ambiguities.length?'NEEDS_CLARIFICATION':'DRAFT_READY',ambiguities,confidence:ambiguities.length?'LOW':'EXPLICIT_COMPONENTS',...guards([original])},ambiguities);}
export function meeting(i:Input):ExecutionOutput{const list=parseMessages(i.messages),e=extract(list);return result({meetingId:i.meetingId!,title:i.title!,history:[...e.decisions,...e.uncertainStatements].slice(0,500),unresolvedItems:e.questions,commitments:e.commitments,documents:i.documentRefs!,decisionsRequired:i.decisionsRequired!,recommendedQuestions:[...e.questions.map(x=>x.statement),...e.commitments.filter(x=>!x.deadline).map(x=>`What is the deadline for the commitment from ${x.sender}?`)].slice(0,100),...guards(list.map(x=>x.body))},['Documents are references only; no document content was independently inspected.','Question resolution is unknown without linked response evidence.']);}
export function brief(i:Input):ExecutionOutput{requireInstant(asText(i.asOf),'$.asOf');const items=i.items as Input[],ids=new Set<string>();for(const item of items){if(ids.has(asText(item.id)))throw new CapabilityInputError('DUPLICATE_ITEM_ID');ids.add(asText(item.id));if(item.dueAt!==null)requireInstant(asText(item.dueAt),'$.items.dueAt');}const open=items.filter(x=>x.status!=='COMPLETE');const order=['URGENT','BLOCKED','DECISION','CUSTOMER','COMMITMENT','FINANCIAL','HEALTH','OPPORTUNITY'];const sections=order.map(category=>({category,items:open.filter(x=>x.category===category).sort((a,b)=>{const x=a.dueAt===null?Infinity:Date.parse(asText(a.dueAt)),y=b.dueAt===null?Infinity:Date.parse(asText(b.dueAt));return (x===y?0:x<y?-1:1)||asText(a.id).localeCompare(asText(b.id),'en');})})).filter(x=>x.items.length);return result({asOf:i.asOf!,sections,decisionsRequired:open.filter(x=>x.requiresOwner).map(x=>asText(x.summary)),unknownItems:open.filter(x=>x.status==='UNKNOWN').map(x=>asText(x.id)),urgencyBasis:'SUPPLIED_STATUS_AND_EXPLICIT_DEADLINES',...guards(items.map(x=>asText(x.summary)))},['Financial summaries remain supplied statements; they are not ledger-verified realized revenue.']);}
export function registerDecision(i:Input,c:ExecutionContext):ExecutionOutput{requireInstant(asText(i.decidedAt),'$.decidedAt');const supersedes=i.supersedesReceiptId;const prior=supersedes===null?null:c.priorCapabilityResults?.find(e=>e.resultDigest===supersedes&&e.capability.id==='decision-register'&&e.status==='SUCCEEDED');const priorOutput=prior?.output as Input|undefined;const priorRecord=priorOutput?.record as Input|undefined;const compatible=!!priorRecord&&priorOutput?.authoritySource==='AUTHENTICATED_OWNER'&&priorRecord.scope===i.scope&&Date.parse(asText(priorRecord.decidedAt))<=Date.parse(asText(i.decidedAt));let reason=!c.ownerAuthenticated?'Authenticated owner execution is required.':supersedes!==null&&!compatible?'Supersession requires a trusted earlier owner decision receipt for this exact scope.':'Owner decision recorded as a new immutable invocation receipt; no external authority granted.';const allowed=c.ownerAuthenticated&&(supersedes===null||compatible);const record=allowed?{decisionId:i.decisionId!,decision:i.decision!,scope:i.scope!,decidedAt:i.decidedAt!,evidenceRefs:i.evidenceRefs!,supersedesReceiptId:supersedes!,authorityContextDigest:c.authorityContextDigest}:null;return {...result({status:allowed?'RECORDED':'BLOCKED',decisionId:i.decisionId!,record,recordDigest:record?sha256(canonicalJson(record)):null,authoritySource:allowed?'AUTHENTICATED_OWNER':'NONE',reason,persistence:'KERNEL_INVOCATION_RECEIPT',historyRewritten:false,...guards([asText(i.decision)])}),status:allowed?'SUCCEEDED':'BLOCKED'};}
export function attachment(i:Input):ExecutionOutput{const text=asText(i.extractedText),mime=asText(i.mimeType);const supported=['text/plain','text/csv','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(mime);const e=extract(supported?[{id:asText(i.attachmentId),sourceId:asText(i.sourceId),sender:'document',sentAt:'1970-01-01T00:00:00Z',replyTo:null,body:text}]:[]);const documentKind=!supported?'UNSUPPORTED':/\binvoice\b/iu.test(text)?'INVOICE':/\b(?:contract|agreement|signature)\b/iu.test(text)?'CONTRACT':/\b(?:meeting|appointment)\b/iu.test(text)?'SCHEDULING':'GENERAL';const actions:Fact[]=[];if(supported)for(const [n,line]of text.split(/[.!?\n]+/u).entries()){const statement=line.trim();if(statement&&!injection.test(statement)&&/\b(?:please|must|required|sign|approve|pay|submit|return|review)\b/iu.test(statement)){const date=statement.match(/\b\d{4}-\d{2}-\d{2}\b/u)?.[0]??null;actions.push({id:sha256(`${i.attachmentId}:${n}:${statement}`).slice(0,32),messageId:asText(i.attachmentId),sourceId:asText(i.sourceId),sender:'document',statement,deadline:date&&dateOnly(date)?date:null,confidence:'UNCERTAIN',provenance:'SUPPLIED'});}}if(actions.length>500)throw new CapabilityInputError('EXTRACTION_LIMIT');return result({attachmentId:i.attachmentId!,documentKind,requestedActions:actions,deadlines:[...new Set(actions.map(x=>x.deadline).filter((x):x is string=>x!==null))],paymentImplications:e.paymentsMentioned,approvalNeeded:/\b(?:sign|signature|approve|approval|contract|agreement|payment)\b/iu.test(text),unansweredQuestions:e.questions,contentExecuted:false,sourceId:i.sourceId!,provenance:'SUPPLIED',...guards([text])},supported?['Only caller-provided extracted text was inspected; binary attachment authenticity and extraction completeness are unknown.']:['Unsupported content type; no content interpretation or execution performed.']);}
